templates/index.html

- Replace partner logos
- Run the site using the command `./run`
- View the site locally in your web browser at: [http://0.0.0.0:8002](http://0.0.0.0:8002)
- Make sure partners logo are replaced with [these](https://github.com/canonical-web-and-design/web-squad/issues/1534)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1534

Replace partner logos

---

static/sass/_pattern_headings.scss
templates/base.html
templates/careers/admin.html
templates/careers/careers_base.html
templates/careers/commercial-ops.html
templates/careers/design.html
templates/careers/diversity.html
templates/careers/engineering.html
templates/careers/ethics.html
templates/careers/finance.html
templates/careers/hr.html
templates/careers/legal.html
templates/careers/lifestyle.html
templates/careers/management.html
templates/careers/marketing.html
templates/careers/progression.html
templates/careers/project-management.html
templates/careers/project.html
templates/careers/sales.html
templates/careers/shared/_left-navigation.html
templates/careers/tech-ops.html
templates/careers/travel.html

- Add content to the following careers pages:
- Fix drop-down navigation on mobile version for all careers pages
- Go to [/careers/design](http://0.0.0.0:8002/careers/design) and navigate to all pages from left navigation menu. Compare the overview tab for the pages mentioned above to the content from [google drive](https://drive.google.com/drive/u/1/folders/1eppuIK_ETt7zIyrqDE6VDtDkjYlPJD4T)
- Make sure the drop-down navigation menu on mobile is functional
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1566

Add content to the overview tab of careers pages

---

static/sass/_pattern_strip.scss
static/sass/styles.scss
templates/careers/careers_base.html

- adjusted spacing between filter inputs on career pages
- built available role list element (with dummy data)
- Check out this branch
- Run `./run`
- Visit http://0.0.0.0:8002/careers/design
- Click 'Available roles'
- See that there is a proper amount of space between the "Filter by" and "Sort by" elements
- See that the available role items match the [design](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/49839913-0355-4344-a84d-759c2e822d45)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1538

Create available roles elements

---

static/js/navigation.js
static/sass/_pattern_navigation.scss
static/sass/_pattern_strip.scss
static/sass/styles.scss
templates/base.html
templates/careers/_secondary-navigation.html
templates/partial/_navigation-careers.html
templates/partial/_navigation-partners.html
templates/partial/_navigation-products.html
templates/partial/_navigation.html
templates/partners/_secondary-navigation.html
webapp/app.py

Added the drop-down mega menu navigation.
Add the second level navigation
- Click the Products navigation item
- Check matches [the design](https://app.zeplin.io/project/5d5566ee83622d9b72e8801d/screen/5da4639ca1d84f309d063e7c) and [the copy doc](https://docs.google.com/document/d/16ltouT0Yo-2RccGiE_irzrCloYaEleqFyU34fmT9OiQ/edit#) 
- Click the Partners navigation item
- Check matches [the design](https://app.zeplin.io/project/5d5566ee83622d9b72e8801d/screen/5da4639f85f67a23e56b4080) and [the copy doc](https://docs.google.com/document/d/1M2CrdIi1IWsSFNkmk5yNk_w835IXZUK395fwAgDhbsQ/edit#)
- Click the Careers navigation item
- Check matches [the design](https://app.zeplin.io/project/5d5566ee83622d9b72e8801d/screen/5da4639ff2c331081a5ee065) and [the copy …

Mega menu navigation

---

templates/partial/_careers-available-roles.html

- Add empty state message to all `careers` pages
- Go to [/careers/engineering](http://0.0.0.0:8002/careers/engineering) 
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/42

Add empty state for careers pages

---

static/js/careers-game.js
static/js/dynamic-image-load.js
static/js/navigation.js
static/sass/_pattern_buttons.scss
static/sass/_pattern_cards.scss
templates/careers/results.html
templates/index.html
templates/partial/_navigation.html
webapp/app.py

- Add ids to `products`, `partners` & `careers` section on the home page
- Change close button style on `/careers/start`
- Go to [http://0.0.0.0:8002](http://0.0.0.0:8002) and check if adding `#products`, `#partners` or `#careers` to the url takes you to the right section on the page
- Go to [/careers/start](http://0.0.0.0:8002/careers/start), select a card and click `That's me` button. Check if the close button looks round and nice.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1845

Add ids to products, partners & careers sections

---

templates/careers/careers_base.html

- Add `id`s to the navigation tabs on `/careers/{department}` pages
- Go to [/careers/sales#available-roles](http://0.0.0.0:8002/careers/sales#available-roles) and change click on `Send your CV`. Check if the url hash is changing
- Change the url to `/careers/sales#overview` and see if the content is changing accordingly 
- Go to [/careers/hr](http://0.0.0.0:8002/careers/hr) and check if you see the overview section
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1731

Add ids to the navigation tabs on careers pages

---

.github/pull_request_template.md
templates/partial/_navigation.html

- Remove partners` from the navigation
- Add GitHub PR template
- Go to http://0.0.0.0:8002 and check you only have 'products' and 'careers' in the navigation bar
Fixes #74

Remove partners from the navigation

---

templates/base.html
templates/careers/all.html
templates/careers/design.html
templates/partial/_careers-available-roles.html

- Update '/careers/design' page
- Add `meta_copydoc` to `/careers/all` and `/careers/design`
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/design
- Compare to [copy doc](https://docs.google.com/document/d/1zpAVnQ1qE-oAmZoxTpfOPFu12zbotBqrD_To9ry0oAQ/edit#)
Fixes #80

Update /careers/design page

---

templates/careers/design.html
templates/careers/engineering.html

- Update `/careers/engineering` page
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/engineering
- Compare to [copy doc](https://docs.google.com/document/d/14gNX9sCgQUM1H0Hfl46R3Wvw0E91XjsuyStMV4KvKME)
Fixes #81

81 update careers engineering

---

templates/careers/admin.html
templates/careers/all.html
templates/careers/commercial-ops.html
templates/careers/design.html
templates/careers/engineering.html
templates/careers/finance.html
templates/careers/hr.html
templates/careers/legal.html
templates/careers/marketing.html
templates/careers/project-management.html
templates/careers/sales.html
templates/careers/tech-ops.html

- Update `/careers/finance` page
- Change `Apply now` link on all careers pages
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/finance
- Compare to [copy doc](https://docs.google.com/document/d/1R4i26Ov-ccfrXm8uSdSRApxgXDH3HwZVY8qWQqPpIjg)
Fixes #82

82 update careers finance

---

templates/careers/index.html

Update the careers overview page content
- Check it matches the [copydoc](https://docs.google.com/document/d/1pNyOXfR07FiBr6TmEMRdB7NZUB5SeBz6COuSxO3ylC0/edit#)
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/78

Update the careers overview page content

---

templates/careers/_secondary-navigation.html
templates/careers/index.html
templates/partial/_navigation-careers.html

- Fix `commercial-sop` and `admin` link in the navigation
- Make all navs consistent in terms of naming
- Click on `careers` at the top and then on `commercial-ops` and after `admin`. See that the navigation works.
Fixes #75 #76

Fix commercial-ops and admin link in the nav

---

templates/index.html

- Show default partners on home page
- Check the partner list and compare to [design](https://app.zeplin.io/project/5d5566ee83622d9b72e8801d/screen/5d9b4b74e301820685aebb72)
Fixes #71

Show default partners on home page

---

templates/careers/admin.html
templates/careers/all.html
templates/careers/commercial-ops.html
templates/careers/design.html
templates/careers/diversity.html
templates/careers/engineering.html
templates/careers/ethics.html
templates/careers/finance.html
templates/careers/hr.html
templates/careers/legal.html
templates/careers/lifestyle.html
templates/careers/marketing.html
templates/careers/progression.html
templates/careers/project-management.html
templates/careers/sales.html
templates/careers/tech-ops.html
templates/careers/travel.html

- Update `/careers/tech-ops` page
- Update `/careers/sales` page
- Update all other careers pages with copy doc link and metadata if available
- Remove some unnecessary markup
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/tech-ops and http://0.0.0.0:8002/careers/sales
- Compare to [tech-ops copy](https://docs.google.com/document/d/1wzuu4pnd2Sx2BDONaaR9EaYUSjx7diTu6PzvYYwbMA8/edit) and [sales copy](https://docs.google.com/document/d/1fGBFiIfy7C58UXcJ0Q7q6VKxClxBfPyeWBSyO9GrStI/edit)
Fixes #86 
Fixes #105

86 update careers techops

---

static/sass/styles.scss
templates/contact-us.html
templates/partial/_navigation.html

- Add office addresses to the `/contact-us` page
- View the site locally in your web browser at: http://0.0.0.0:8002/contact-us
- Compare to [design and text](https://github.com/canonical-web-and-design/canonical.com/issues/107)
- Make sure the addresses are visible if you disable JS
- Check the location of the offices on maps is correct (I got the coordinates from https://canonical.com/about)
Fixes #107

Add office addresses to the contact page

---

templates/careers/_secondary-navigation.html
templates/careers/commercial-ops.html
templates/careers/design.html
templates/careers/hr.html
templates/careers/index.html
templates/careers/results.html
templates/partial/_careers-navigation.html
templates/partial/_navigation-careers.html

- Added missing overview copy to /careers/commercial-ops
- Updated copy in search results message
- Updated careers category titles in line with copy docs
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/commercial-ops
- See that the overview copy matches the [copy doc](https://docs.google.com/document/d/1y2bqWcHW2rRrb5gA7XTt8_A0q6zPOLkkOIwCIaNLpTk/edit)
- Visit /careers/start, play the game and submit your choices, then see that the "Looks like you're interested in..." copy makes sense.
Fixes #116

Copy updates

---

tests/test_greenhouse_api.py
webapp/greenhouse_api.py

Added a parsing function to the returned feed department data to align with the site content.
- Click through and check to engineer and we and design have roles available
- The others do not yet
- Compare to the `department - external` here: https://boards-api.greenhouse.io/v1/boards/Canonical/jobs

Parse the feed departments to work with the site

---

static/sass/_pattern_navigation.scss

Increased padding of nav items on x-small screens, to align with logo
- View the page at <460px, and see that the header logo and nav are aligned to the left
Fixes #123

increase padding on nav on x-small screens

---

static/js/careers-filter-and-sort.js
templates/careers/_filters.html
templates/careers/base.html
templates/careers/results.html
templates/partial/_careers-available-roles.html
templates/partial/_careers-job-list.html

- fixed dropdown filters on /careers/results
- fixed issue where refreshing the page after using the dropdown filter would cause the 'coreskills' values to be lost
- select some options, submit them - you should land on /careers/results
- using the dropdown, filter the results
- see that the results are indeed filtered
- refresh the page, see that the page loads successfully, and the relevant results are shown
Fixes #125

Fix filters on results

---

templates/careers/index.html
templates/careers/lifestyle.html
templates/careers/travel.html

- replaced large file size images with optimised versions
- Open the network tab in dev tools
- Visit /careers, /careers/travel and /careers/lifestyle, checking the network tab each time to ensure that images loaded are all < 200kb
Fixes #135

replace large file size images with optimised versions

---

tests/test_routes.py
webapp/app.py

- removed route regex, set explicit list of career departments to match against
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/engineering
- See that the page loads correctly
- Go to /careers/engineering1234
- See that the page 404s
Fixes #134

Set explicit list of careers department routes

---

templates/careers/base-tabs.html
templates/partial/_careers-available-roles.html
webapp/app.py

- Disabled ability to submit CV on career departments.
- Fixed non-department /career pages 404ing
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/engineering
- See that there are only two tabs, "overview" and "available roles"
- Visit /careers/start, /careers/lifsetyle and /careers/all
- See that none of them 404

remove "send your cv" tab

---

templates/careers/results.html

- Fixed invalid HTML that was causing missing "no results" message when filtering job results
- Select 5 choices and submit them
- On the results page, filter by "Part-time"
- See that "Sorry, there are no open positions matching your criteria." is visible

Fix missing "no results" message when filtering job results

---

Dockerfile
package.json

Switch over to multistage build to fix the problem with node version in the build for production.
``` bash
./run clean  # To prove we don't need it
DOCKER_BUILDKIT=1 docker build --tag ccom --build-arg BUILD_ID=abuild .
docker run -ti -p 8555:80 ccom
```
Go to http://localhost:8555, check it works a charm.
Then, do:
``` bash
$ curl -I http://localhost:8555
X-VCS-Revision: abuild
```
^ Check you see the `BUILD_ID` there.

Multistage build

---

static/sass/_pattern_footer.scss
templates/careers/index.html
templates/index.html
templates/partial/_careers-job-list.html
templates/partial/_footer.html

- Addressed the points raised [here](https://github.com/canonical-web-and-design/canonical.com/issues/147):
- Numerous grammar corrections
- Replaced pipes with middots in footer link list
- Removed 'Support' item from product table, as it isn't a standalone item in the [copy doc](https://docs.google.com/document/d/16ltouT0Yo-2RccGiE_irzrCloYaEleqFyU34fmT9OiQ/edit#)
- Updated heading sizes on /careers/results and other job listings to be h3, rather than h2
- Removed ellipsis from career department descriptions on /careers
- Check …

Scott's post-launch fixes for Peter's pre-launch snags

---

webapp/app.py

Fix the routing for tech ops
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/tech-ops#available-roles
- Check it loads job roles
- Check a few other departments all work too

Fix tech ops available job view

---

webapp/app.py

This is an alternate fix for #154 - that roles weren't loading properly for the tech-ops page.
The reason this was happening was because the complex route definition for the `department_group` view wasn't matching `tech-ops` or `admin`, and so instead of using this view they were falling back to the default `TemplateFinder` view (and therefore didn't contain the context they needed).
I think it's simpler to declare these routes explicitly so it's harder to make mistakes.
We could further avoid confusion by moving the templates for these pages, e.g. into `careers/groups`. This way, if you fail to hit the correct view you'd get a 404, rather than what looks at first glance like success.
- View the site locally in …

A better fix for techops roles

---

templates/base_index.html
templates/careers/start.html
templates/partners/become-a-partner.html

- Added the social meta data to the base_index.
- Added a social image, title, desc to the careers/start page
- See that the page's social data works on twitter, etc...
Fixed #151

Add social metadata to base + careers/start page

---

templates/careers/index.html

- Add missing row of departments to /careers
- Compare to the [copy doc](https://docs.google.com/document/d/1pNyOXfR07FiBr6TmEMRdB7NZUB5SeBz6COuSxO3ylC0/edit?ts=5e217d85#)
Fixes #159

Add missing row of departments to /careers

---

templates/404.html
templates/500.html
templates/careers/admin.html
templates/careers/all.html
templates/careers/apply.html
templates/careers/commercial-ops.html
templates/careers/design.html
templates/careers/diversity.html
templates/careers/engineering.html
templates/careers/ethics.html
templates/careers/finance.html
templates/careers/hr.html
templates/careers/index.html
templates/careers/job-detail.html
templates/careers/legal.html
templates/careers/lifestyle.html
templates/careers/marketing.html
templates/careers/progression.html
templates/careers/project-management.html
templates/careers/results.html
templates/careers/sales.html
templates/careers/start.html
templates/careers/tech-ops.html
templates/careers/travel.html
templates/contact-us.html

- Added missing meta data to all pages
- Updated all copy docs
- Click through and see that all pages have been updated.  It will be more visible once #158 is live

Add missing meta data to pages

---

webapp/app.py
webapp/greenhouse_api.py

Add check for job id and return 404 if not found
- Go to http://0.0.0.0:8002/careers/1952359 and check the job loads
- Go to http://0.0.0.0:8002/careers/195235923 and check the site 404's
- Go to https://canonical.com/careers/195235923 and see it 500's

Add check for job id

---

static/js/navigation.js

* Renamed remaining ubuntu.com events to canonical.com
* Removed takeover impression events
- Google Analytics (combo tracker)-> realtime group -> filter "content" view on the domain serving the PR -> switch to "events" view, and navigate around the site, ensure you don't see impression or ubuntu.com event categories

GA events clean-up

---

templates/index.html

Simple fix to openstack grid HTML attributes

Fix missing spaces in HTML attributes

---

static/sass/_pattern_animations.scss

Override the opacity set for animations when reduced motion is set. As this stops all animations by Vanilla we need to just display the text.
- On Ubuntu 18.04 install a package called dconf Editor with `sudo apt install dconf-editor`
- Open it and go to `/org/gnome/desktop/interface/ and toggle` the “Enable-Animations” option to OFF.
- Visit https://canonical.com and see there is no text
- Go to the demo and see that there is text
- Smile with glee as you remember to turn back on Enable-Animations setting
- Close down dconf and forget it forever

Support disabling reduced motion

---

templates/base_index.html

- Check the styles and navigation works as before
- Check in the source that the styles.css and navigation.js have query params to bust the cache

Add versioned_static to cache bust local assets

---

redirects.yaml

Added redirect from contributors ubuntu.com
- Go to /contributors and check it redirects to https://ubuntu.com/legal/contributors
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/172

Add rediect from contributors

---

templates/careers/job-detail.html

Re-added job application JS that was accidentally removed during the careers section refactor.
- Go to /careers/1504935:
- Click the Locate Me button, you should see either "Location unavailable", or the Location field filled automatically.
- Fill out the rest of the form, but leave the CV field blank, attempt to submit it. You should not be able to.
Fixes #153 & #179

add missing validation and application js

---

.stylelintrc
package.json
run
static/sass/_pattern_animations.scss
static/sass/_pattern_buttons.scss
static/sass/_pattern_cards.scss
static/sass/_pattern_careers-modal.scss
static/sass/_pattern_footer.scss
static/sass/_pattern_forms.scss
static/sass/_pattern_headings.scss
static/sass/_pattern_lists.scss
static/sass/_pattern_media-object.scss
static/sass/_pattern_navigation.scss
static/sass/_pattern_strip.scss
static/sass/_pattern_tabs.scss
static/sass/styles.scss
yarn.lock

Replaces sass-lint with stylelint and fixed resulting linting errors
- Run `./run exec yarn lint-scss`
- Check that there are no linting errors
Fixes #191

Replace sass-lint with stylelint

---

templates/base_index.html

Updated the page title to "Canonical | Publisher of Ubuntu"
- Check that the page title is "Canonical | Publisher of Ubuntu"
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7094

Update page title

---

static/sass/_pattern_cards.scss
static/sass/_pattern_strip.scss
templates/partners/desktop.html

Updated desktop partner page
[copy](https://docs.google.com/document/d/1MBVH4kou0Q7yO_Lq6DPQpZL_rc0K1-nVfvg4aF3biSc/edit#)
[design](https://usercontent.irccloud-cdn.com/file/TZtWqNTC/Partner%20-%20Desktop.png)
Note: some aspects of the design are unimplemented 
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/desktop
- Check the design, copy and responsiveness at all viewports
Fixes #2566

Update desktop partners page, add strip and card variants

---

.circleci/config.yml
.env
requirements.txt

Update flask-base to 0.5.1

---

templates/partners/become-a-partner.html
templates/partners/thank-you.html

- Update become a partner page
- Add `/partners/thank-you` page
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/become-a-partner
- Compare to [copy doc](https://docs.google.com/document/d/1Ihh9s3i72saCYaheXRVRn1Meg5lYN5U1gFbdvLMdWcc/edit)
- Go to `/partners/thank-you` and see the thank-you page. Note that the links on this page won't work properly as we have redirects to partners.ubuntu.com
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2569

Update become a partner page

---

package.json
static/sass/_pattern_strip.scss
templates/partners/channel-and-reseller.html
templates/partners/cloud.html
yarn.lock

- Add `/partners/channel-and-reseller` page
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/channel-and-reseller
- Compare to [copy doc](https://docs.google.com/document/d/1rn2f4wL8wxnILlnmfchkNQV2RzsYUMcRaCfP-d6V_5Q)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2567

Add channel-and-reseller page

---

templates/partners/ihv-and-oem.html
tests/test_routes.py
webapp/app.py
webapp/partners.py

- Add IHV and OEM partners page
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/ihv-and-oem
- Compare to [copy doc](https://docs.google.com/document/d/1p8Et43R14AGiFn9g7ro9VLXZh26gph9Kk5K6_lc8W8U/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2565

Add IHV and OEM partners page

---

templates/partners/system-integrators.html
webapp/app.py
webapp/partners.py

- Add global system integrators partners page
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/system-integrators
- Compare to [copy doc](https://docs.google.com/document/d/1PgdZCn16zMVA3LVcLihN03DYFLLqkHIqTqfsgx_LHFg)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2561

Add system-integrators partners page

---

static/js/careers-filter-and-sort.js
webapp/greenhouse.py

Made the access to the metadata object query by id instead of index in the returned payload. If the id is not found `None` is returned instead of index out of bounds which causes a 500.
Also, fixed all the filters in the job listing view.
- Click through all the departments and check the roles list works for all of them
- Then try the All roles at the bottom and check that renders ok
- Use the filter and sort options and check they do what you expect
- Click on Careers in the main navigation then click "Explore a career at Canonical"
- Play the game and see the resulting list of jobs is rendered without 500
- Check filters and sort work …

Refactor API access of metadata to be more resilient

---

templates/index.html

- Update homepage partner logos
- See that aws has a new logos, super micro is there, google is not there and azure is not there
Fixes #236

Update homepage partner logos

---

templates/partners/desktop.html
templates/partners/devices-and-iot.html
templates/partners/find-a-partner.html
templates/partners/ihv-and-oem.html

- Fix desktop partners logos
- Add min-width on logo img tags as some svgs have no size and therefore do not appear
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/desktop
- See HP, Dell, Lenovo logos
Fixes #237

Fix desktop partners logos

---

static/sass/_pattern_strip.scss
templates/partners/channel-and-reseller.html
templates/partners/gsi.html
webapp/partners.py

- Logo clouds only appear if there are 2 or more featured partners.  For channel-and-reseller and gsi I hid the strip if there are no partners
- I moved the suru css into the scss strip file
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/channel-and-reseller
- See that http://0.0.0.0:8002/partners/channel-and-reseller and http://0.0.0.0:8002/partners/gsi have no logo clouds or empty ones
Fixes #238

Fix up channel and gsi logo clouds

---

templates/partners/find-a-partner.html

- Remove programmes not on the site from the /partners/find-a-partner filter
- Removed HPC as well as no companies in the list
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/find-a-partner
- See that the programme list has only pages on the site

Remove programmes not on the site from the /partners/find-a-partner filter

---

templates/partners/channel-and-reseller.html
templates/partners/desktop.html
templates/partners/devices-and-iot.html
templates/partners/find-a-partner.html
templates/partners/gsi.html
templates/partners/ihv-and-oem.html

- Fix logo cloud min-width
- Fix logic hiding some clouds
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/channel-and-reseller
- See that the logos appear and are mostly visible - cannot get all right as b systems is poor quality

Fix logo cloud min-width

---

templates/index.html
templates/partners/_secondary-navigation.html
templates/partners/channel-and-reseller.html
templates/partners/gsi.html
templates/partners/ihv-and-oem.html
templates/partners/index.html

- Update partner-portal link per Katie
- Changed the CTA on the /partners/gsi page
- **NOTE** blocked on portal getting ssl certs
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/gsi
- See that the link to the partner portal is now https://partner-portal.canonical.com
- See that the gsi banner cta is to contact us

Update partner-portal link

---

templates/partners/desktop.html

Remove extra pasted sentence
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/desktop
- See that 'Information about Canonical. Canonical produces Ubuntu, provides commercial services for enterprise users, and works with industry partners on delivery and certification.' was removed from the 'Works out of the box' box
Fixes #259

Remove extra pasted sentence

---

templates/partners/gsi.html

Update gsi partner page with webinars and resources
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/gsi
- Compare to and resolve the [copy doc](https://docs.google.com/document/d/1PgdZCn16zMVA3LVcLihN03DYFLLqkHIqTqfsgx_LHFg/edit#)
Fixes #261

Update gsi partner page with webinars and resources

---

templates/projects/directory.html

- Updated the table in /projects/directory to match [this sheet](https://docs.google.com/a/canonical.com/spreadsheets/d/14Smfpq9ttrPt2jPx70NB3QTixH_6h7Ktnp1CihjT1So/notify/show?rev=269&fromRev=269&s=AM5m-fjBmO5P7oZf2ZUzq5lltH01TIK0Aw&usp=gmail)
- View the site locally in your web browser at: http://0.0.0.0:8002/projects/directory
- Ensure that the content of the table matches the google sheet
Fixes #265

Update table in /projects/directory

---

static/js/careers-filter-and-sort.js
templates/careers/_filters.html

Added the ability to filter jobs by location on the careers pages
- Ensure that jobs are properly filtered by location, and that the new field is compatible with the existing "Filter by" and "Sort by" fields.
- Ensure that the code is sensible and in line with any Canonical style guides
Fixes #189

Add location filter to careers pages

---

templates/base_index.html

- To migrate to the new cookie policy, it is safer to move canonical.com out of the ubuntu.com GTM container - this is that move.
- See that it is correctly using the new `GTM-M5BPGQ6` container
Fixes #284

Change GTM tag

---

templates/partners/find-a-partner.html

- Stop squishing and better align /partners/find-a-partner logos as reported by @zprood
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/find-a-partner logos
- Compare HP or Hwawei's logos on live to this branch

Stop squishing and better align /partners/find-a-partner logos

---

templates/partial/navigation-careers.html

Fix links in career mega-menu
- View the site locally in your web browser at: http://0.0.0.0:8002/projects and click on the careers menu item and look at the links for regions and 
- See that all the region and 'Lifestyle Ethics Travel Progression Diversity' work, both large and small screens
Fixes #301

Fix links in career mega-menu

---

templates/index.html

- Swap Yahoo! Japan with Huawei logo
- See Huawie's logo and no Yahoo! Japan
Fixes #313

Swap Yahoo! Japan with Huawei logo

---

static/sass/_pattern_forms.scss

Make /career filters fit on one row
- See that the filters fit on 1 row
Fixes #322

Make /career filters fit on one row

---

templates/partners/gsi.html

-Fix link to gsi partners on /partners/gsi
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/gsi
- See that the link to all partners is now correct `/partners/find-a-partner?filters=global-system-integrators`

Fix link to gsi partners on /partners/gsi

---

.env
requirements.txt
static/sass/styles.scss
templates/careers/job-detail.html
webapp/app.py

Clean up typography on job descriptions by removing inline styles and empty paragraphs.
- Click through different job descriptions
- Ensure typography is consistent

Clean up typography on job descriptions

---

templates/base_index.html
templates/careers/job-detail.html

- Added core skills to the job listing's meta data
- View the site locally in your web browser at: view-source:http://0.0.0.0:8002/careers/2114847/apparmor-security-engineer-remote
- See that core skills appear `<meta property="keywords" content="Contributor, Developer, Fixer, Inventor, Problem Solver">`
- Go to another non-job page and see that they do not.

Add meta keywords for jobs to get core skills

---

templates/careers/base_job-details.html
templates/careers/job-detail.html

- Remove side nav 
- Add "Apply" buttons to job details page
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/2948002/commercial-director-hpc-remote
- See that there is no navigaton on the side
- See that there is an 'Apply' button and see that it moves you down the page
Fixes [#3819](https://github.com/canonical-web-and-design/web-squad/issues/3819)

Remove side nav and add "Apply" buttons to job details page

---

static/sass/_pattern_strip.scss
templates/careers/all.html
templates/careers/base-tabs.html
templates/careers/base-template.html
templates/careers/diversity.html
templates/careers/ethics.html
templates/careers/progression.html
templates/careers/results.html

Made the hero's a bit smaller top: 2rem, bottom: 4rem (from 6rem) per tooling meeting
- See the smaller heros

Shorten heros

---

templates/careers/base-tabs.html

- Make available roles first
- Rename 'Overview' to 'Department overviews'
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/web-and-design
- See that the roles show on load and click 'Department overivew' and see that this loads
Fixes #354

Make available roles first

---

static/js/careers-game.js

Hide `that's me` button on empty game card
- [EDIT: ] Oops! missed one step. select some cards and now click the empty cards.
Actual Behavior on click after card selected. see the empty button 2nd card
Fixed to no button display at all.

Fixed add button on empty game card careers

---

templates/careers/sitemap.xml
templates/partners/sitemap.xml
templates/sitemap-index.xml
templates/sitemap-links.xml
webapp/app.py

Add sitemap generated for careers, partners and the rest
- `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8002/sitemap.xml
- Make sure the links actually exist
- You will have to replace: https://canonical.com/ with http://0.0.0.0:8002/

Add sitemap to site

---

templates/base_index.html
templates/careers/job-detail.html
webapp/greenhouse.py

- Add rich structure data for career pages
- https://developers.google.com/search/docs/data-types/job-posting
- This should help us to integrate our jobs posting in Google job pages
- `dotrun`
- http://0.0.0.0:8002/careers/2948052/commercial-director-automotive-remote
- This is a remote job:
- Make sure the structured is well parsed in https://search.google.com/test/rich-results
- Make sure that the data has full-time and remote
- http://0.0.0.0:8002/careers/2593748/iot-sales-director-Office%20Based%20-%20Taipei,%20Taiwan
- This is an office based job
- Make sure the structured is well parsed in https://search.google.com/test/rich-results
- Make sure in the JSON there is an address

Add Rich structure data for career pages

---

templates/partial/_careers-navigation.html

Fixed the count next to the "All roles" link, which was previously always showing 0.
- Check that the count shown next to the "All roles" link in the careers navigation sidebar is not zero (it should be equal to the sum of the count for each department)
Fixes #396

Fix "All roles" count

---

templates/partial/_navigation.html

Moved the skip link above the main nav so it's the first focussable element on the page
- Press the tab key, if the focus isn't already on the page, it should reveal the skip link on the first press

Move skip link above main navigation

---

templates/careers/rss.xml
webapp/app.py

- Add rss feed for careers sections
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/feed
- You should get a feed with all the jobs open. Each job should have a link a description and a title
Fixes #405

Add rss feed for career section

---

static/js/navigation.js
static/sass/_pattern_navigation.scss
templates/partial/_navigation.html

Update navigation pattern classes to match Vanilla recommendation
- View the site locally in your web browser at: https://canonical-com-410.demos.haus/partners
- Check that the nav dropdown works, and that the text in the nav doesn't overlap the dropdown (compare to https://staging.canonical.com/partners)

Update navigation pattern classes to match Vanilla recommendation

---

templates/careers/base.html
templates/careers/job-detail.html
templates/careers/rss.xml

- On career pages add the metatag rss so RSS clients can notify the user to subscribe
- Fix None issue for jobs that don't have description in RSS feed
- `dotrun`
- http://0.0.0.0:8002/careers/feed
- Make sure no description have None
- http://0.0.0.0:8002/careers/all
- http://0.0.0.0:8002/careers/2593683/associate-iot-systems-engineer-remote
- Both should have the metatag:
`<link rel="alternate" type="application/rss+xml"  href="/careers/feed" title="All job roles | Canonical Careers">`

Add rss feed tag

---

Dockerfile
package.json

- Updates  Dockerfile 'yarn run' to use --production tag

Updates yarn run to use --production tag

---

templates/index.html

Under juju section on https://canonical.com/#products change link from jaas.ai to juju.is
- `dotrun`
- Open the website locally on http://0.0.0.0:8002/#products
- Make sure that Juju section is linked to https://juju.is
Fixes #420

Change jaas.ai link to juju.is

---

templates/index.html

Added the missing class `js-active-target` to fix the highlight issue with the nav bar when scrolling.
- Please scroll down and up the page and check if the nav bar gets highlighted properly. 
Fixes #418

Add missing class

---

templates/partial/_footer.html

- Removed Facebook icon and link from homepage footer and added LinkedIn as per [request](https://github.com/canonical-web-and-design/canonical.com/issues/423#issue-997113587)
- View page at: https://canonical-com-425.demos.haus
- Scroll to the footer - see the Facebook link has been removed and the LinkedIn one has been added
- Check the link works and directs you to Canonical's LinkedIn page. 
Fixes #423

Add LinkedIn link and remove Facebook 

---

templates/careers/results.html
templates/partial/_careers-available-roles.html
templates/partial/_careers-navigation.html
webapp/app.py
webapp/greenhouse.py

- Updated the structure of Vacancy on the backend side
- Updated the templates where there is a reference to vacancy.department
*FYI: Departments is a list where a vacancy can have one or multiple departments*
1. go to https://canonical-com-428.demos.haus/careers/all and make sure that the page is not broken
2. Here is an example of each vacancy case:
```json
[
{
"jobId": 3382736,
"jobTitle": "Chief of Staff, Global Support Services",
"department": "techops",
"departments": ["techops"]
},
{
"jobId": 3062022,
"jobTitle": "Cloud Engineering - open source, remote",
"department": "techops",
"departments": ["engineering", "techops", "operations"]
}
]
```
The first one (with the id: `3382736`) is a job that belongs to only one department and the second one (with the id: `3062022`) belongs to …

Replaced the field "department" with "departments"

---

static/sass/_pattern_navigation.scss
templates/partial/_navigation.html

- Hide nav items by default
- Add menu toggle button
- Go to the website https://canonical-com-432.demos.haus/ ,make sure to open the devtools and toggle the mobile view
- Make sure the nav items aren't shown by default
- The menu toggle button should work
- Make sure that the navbar is usable
- Go to the page: https://canonical-com-432.demos.haus/careers
- Make sure the nav items aren't shown by default
- The menu toggle button should work
- Make sure that the navbar is usable
Fixes #431

Fixes navigation bar on mobile

---

.gitignore
static/sass/_pattern_cards.scss
static/sass/_pattern_footer.scss
templates/careers/start.html

- changed selected skill width from 100% to 50%
- set skill `min-height` to 8rem in mobile
- fixed footer overlay in mobile
Fixes #157 
footer overlay
changed skills grid

Career game mobile fix

---

templates/partners/_secondary-navigation.html
templates/partners/index.html

- Add `IoT Device Programme`on the `/partners` page
- Add `IoT device` on the secondary menu 
- View the site locally in your web browser at: http://0.0.0.0:8002/partners
- Refer to this [doc](https://docs.google.com/document/d/1SwCceQv625Kdc3wAvzSFBBA3qt3CxzDmc0DAfo3LJfs/edit) and [brief](https://docs.google.com/document/d/1vOIffTaJL8LeQVj-kuc1XU9p1-SQFVvQWYZHEjcDKZ8/edit)
Fixes [#4634](https://github.com/canonical-web-and-design/web-squad/issues/4634)

Add iot-device page on /partners

---

static/js/file-validation.js

**Note** Haven't addressed the form limit issue, this just adds a warning message
Adds a warning message if the CV that is being uploaded is over 1MB
- Go to canonical.com/careers, choose a job, try to add a document over the size of 1MB to check the warning appears
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/269

Add warning message if CV size is over 1MB

---

requirements.txt
webapp/app.py

Enable image template tag to work on canonical.com
- Run the site using the command `./run`
- Refer to [this page](https://github.com/canonical-web-and-design/canonicalwebteam.image-template)
- Try this image template tag below instead of `<img>` tag and please check if the image displays properly.
`{{
image(
url="https://assets.ubuntu.com/v1/450d7c2f-openstack-hero.svg",
alt="",
width="534",
height="319",
hi_def=True,
fill=True,
loading="auto",
attrs={"class": "hero", "id": "openstack-hero"},
) | safe
}}`
Fixes #456

Enable image template tag to work on canonical.com

---

static/sass/_pattern_forms.scss
static/sass/_pattern_lists.scss
templates/partial/_careers-navigation.html

- Fix the responsiveness of the filter on /careers/all
- Fix the side bar 
- Please check if the filter and the side bar is responsive on all screens. 
- [Demo](https://canonical-com-455.demos.haus/careers/all)
Fixes #448 
Filter : 
Before 
After 
Side bar:
Before
After

Fix the responsiveness of the filter on /careers/all

---

templates/about-canonical.html
templates/customer-references.html
templates/department-overview.html
templates/includes/_working-here.html
templates/leadership-bios.html
templates/leadership-team.html
templates/meet-the-team.html
templates/our-code-of-conduct.html
templates/press.html
templates/tech-culture.html
templates/working-groups.html
templates/working-here/index.html
tests/test_routes.py

The products page has been removed from the wireframes
The following pages have been created:
Company
About Canonical
Leadership team
Leadership bios
Customer ereferences
Open source
Press
Careers
"Working here" one template example (most likely need to create an "include")
Department overviews
Working groups
Meet the team (this could potentially be an include)
Our Code of Conduct
- View the following stub pages at: http://0.0.0.0:8002/
- /about-canonical
- /leadership-team
- /customer-references
- opensource
- press
- tech-culture
- department-overviews
- working-groups
- meet-the-team
- our-code-of-conduct
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4589

Page stubs

---

.env
.github/workflows/pr.yaml
konf/site.yaml
requirements.txt
templates/applications/_interview-card.html
templates/applications/application.html
webapp/app.py
webapp/application.py
webapp/greenhouse.py
webapp/utils/cipher.py

- This is a page dedicated to applications for candidates that apply to jobs. This link will be shared in the emails exchanged between the recruiter and the candidate
- A candidate can have multiple pages if the candidate applies to multiple jobs
- This page will let the candidate know what is the progress of his/her application
- The page shows a list of useful information like:
- Job link
- Next interview (with a link to convert the time to your own timezone)
- Previous interviews
- What stage is the application (WIP)
- Some useful links about Canonical (WIP)
- A form to delete the candidate application (WIP)
- The page is not indexed 
- The link is made with `first_name`, `candidate_id` and `application_id`. This is made to avoid someone doing a bruteforce to find all those links: …

Add application page for candidates

---

templates/careers/job-detail.html

- Updated the "Back to list" logic to check whether the user came from a careers page. If they didn't, the link will send them to /careers/all.
**HACKY QA ALERT**
The easiest way I could find to check this worked was to drop a link to a specific job advert in a non careers section of the page.
Also - you will need the `GREENHOUSE_API_KEY` and `HARVEST_API_KEY` env variables in your local project to be able to see job listings. I can provide them if you don't have them already.
- Run the site using the command `./run serve`/`dotrun`
- In your code editor, add `<a href="http://0.0.0.0:8002/careers/2404733/associate-field-software-engineer-emea-remote">Job listing</a>` to any page not under /careers
- View the site locally in your web browser at: …

Ensure users are sent back to a careers list from a job application

---

webapp/app.py

- Removes api call for all-departments from 'job-details' view
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/3776344/dedicated-linux-engineer-emea-remote
- Check job details page still functions appropriately
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/487

Remove api call for all-departments from 'job-details' view

---

static/js/file-validation.js

- Add file size check to cover-letter upload on job application form, the same way we check resumes.
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/3776036
- Go to a job-details page and try to attach a file over 1mb in size, it should not allow this.
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/476

Add file size check to cover-letter upload on job application form

---

templates/index.html

Replaced "Conjure Up" in the list of products with Charmed Kubeflow, as per the [copy doc request](https://docs.google.com/document/d/16ltouT0Yo-2RccGiE_irzrCloYaEleqFyU34fmT9OiQ/edit#)
- See that Charmed Kubeflow appears in the list of products, and that the link takes you to the correct site.
Fixes [#4842](https://github.com/canonical-web-and-design/web-squad/issues/4842)

replace conjure up product with charmed kubeflow

---

webapp/greenhouse.py

- Removed the "department" field from the Greenhouse query
- View the site locally in your web browser at: https://canonical-com-495.demos.haus/careers/all
- You should see vacancies, rather than a "There are no open vacancies right now" message

Remove "department" field from Greenhouse lookup

---

requirements.txt

Update flask-base to the latest 1.0.2 to fix `ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/ant/projects/canonical.com/.venv/lib/python3.8/site-packages/markupsafe/__init__.py)`
- Run `dotrun clean`
- Then `dotrun`
- Check the site works

Update flask-base to the latest 1.0.2

---

templates/careers/thank-you.html
webapp/app.py

- Create a page on `/careers/thank-you` that returns to after application submission
- [Copy doc](https://docs.google.com/document/d/1nsZWk9osMxoMlSnSNIXZCFCV8-Ho4PeLXo0qD-vF_Bk/edit#heading=h.qk8g5uz8h4br)
- Go to `/careers/all`, submit an application and check it goes to a thank you page after submission (Also check the position is correct in the text "Congratulations! Your application to our `___` has been received")
Fixes [#505](https://github.com/canonical-web-and-design/canonical.com/issues/505)

Create thank-you page

---

templates/index.html
templates/partial/navigation-products.html

- Update lxd link on mega menu and `/#products`
- Please QA the link on https://canonical-com-513.demos.haus/#products and mega menu
Fixes [#5026](https://github.com/canonical-web-and-design/web-squad/issues/5026)

Update lxd link

---

templates/partners/isv-partners.html

- Built ISV partners page as per [copy doc](https://docs.google.com/document/d/1qWWpFbwZykjAIt-Kf6iFCXPCnmmuKBbU5mzvILnO-q0/edit#heading=h.dzb0bs0676v)
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/isv-partners
- Check copy against doc
- Test 'become a partner' button and footer links
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4994

Add ISV partners page

---

templates/practice/documentation.html

- Fix side nav appearing above dropdown menu on documentation page
- Please QA all the navigations on this page - top nav, side navigation, toggle side navigation on mobile.
- Demo at Demo starting at https://canonical-com-525.demos.haus/practice/documentation
Fixes #526 

Fix side nav z-index

---

templates/partners/_secondary-navigation.html
templates/partners/isv-partners.html

- Added ISV partners page to partners subnav as per [copy doc](https://docs.google.com/document/d/1qWWpFbwZykjAIt-Kf6iFCXPCnmmuKBbU5mzvILnO-q0/edit#heading=h.dzb0bs0676v)
- Added missing bullet point to sync page with doc 
- View the site locally in your web browser at: https://canonical-com-529.demos.haus/partners/isv-partners
- See that page has been added to subnav and that link works as expected
- See that copy was updated to reflect the doc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5181

Add isv partners page to partners subnav

---

static/sass/_pattern_cards.scss
templates/partial/_partners-footer.html
templates/partners/channel-and-reseller.html

- Refresh /partners/chanell-and-reseller for canonical-v3, see [doc](https://docs.google.com/document/d/1rn2f4wL8wxnILlnmfchkNQV2RzsYUMcRaCfP-d6V_5Q/edit), [design](https://app.zeplin.io/project/624ed20e0af92866116ea26d/screen/6254185f9c8cce6c8b79ade1)
- Add `p-card.has-cta`, updates `p-card--strip-thin`
**note: I used this screenshot for the hero strip iamge, not sure if we need a better one made**
- Compare agianst design
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5155

Refresh /partners/chanell-and-reseller for canonical-v3

---

templates/partners/gsi.html

**Blocked: the section 'Grow with Canonical' does not appear in the design**
- Refresh /partners/gsi for canonical-v3 based on [design](https://app.zeplin.io/project/624ed20e0af92866116ea26d/screen/625418438b950467d5a7fda9) and [copydoc](https://docs.google.com/document/d/1PgdZCn16zMVA3LVcLihN03DYFLLqkHIqTqfsgx_LHFg/edit)
- Compare against both design and copydoc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5158

Refresh /partners/gsi for canonical-v3 

---

static/sass/_pattern_cards.scss
static/sass/_pattern_lists.scss
static/sass/_utilities_accent-border.scss
static/sass/styles.scss
templates/careers/index.html
templates/partners/desktop.html
templates/partners/ihv-and-oem.html

- Refresh /careers for canonical-v3 absed on [design](https://app.zeplin.io/project/624ed20e0af92866116ea26d/screen/6254185a9c8cce6c8b79ace1) and [copydoc](https://docs.google.com/document/d/1pNyOXfR07FiBr6TmEMRdB7NZUB5SeBz6COuSxO3ylC0/edit#)
- Updates `p-card--strip-thin` to `p-card--orange-strip` and `p-card--blue-strip` and adds a `no-border` option to the sass class
- Updates instances where these classes were used
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4713

Refresh /careers for canonical-v3

---

templates/index.html

Added Nvidia logo and update footer
- Go to https://canonical-com-548.demos.haus/
- Check logo nvidia has been added.
- Check footer is always 2019 according to [MS comment](https://docs.google.com/document/d/1WcNN2RlQQrbLSP5ZgcIsAeQAHj5h_yDW6Yd5oBMmU3M/edit?disco=AAAACqQyp-w)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5293

Update homepage logo and footer copyright year

---

templates/careers/job-detail.html

Added links to the privacy policy and the new recruitment privacy policy on job application forms.
- Visit https://canonical-com-549.demos.haus/careers/3830645/accountant-remote (or any other job listing)
- See that there is a disclaimer above the submit button linking to the two privacy notices

add links to privacy notices on application forms

---

templates/careers/results.html
tests/test_routes.py
webapp/app.py

Do not try and split a list. Check it first. 
- Go to https://canonical.com/careers/results and see you get a 500
- Go to /careers/results and see the page renders with a message stating there were no vacancies matching the selection and asking the user to try again.
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/546
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1413534/167934377-38f2a196-08cc-427c-8d93-a3fbd8f76bad.png) | ![image](https://user-images.githubusercontent.com/1413534/167934596-45bfaee8-6f02-41e3-abfe-5bb00241777d.png) |

Display user error on empty results

---

templates/partial/_navigation-careers.html
templates/partial/_navigation-company.html
templates/partial/_navigation-partners.html
templates/partial/_navigation-products.html
templates/partial/_navigation.html
webapp/app.py

- Update navigations drop-down links based on the [miro board](https://miro.com/app/board/o9J_luilNcw=/?moveToWidget=3458764526315426035&cot=14)
- Go to https://canonical-com-554.demos.haus/ and check the navigation matches the miro board and that all the links (except company/blobs, company/documentation and company/press-centre) work
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5410

Update navigation drop-down links

---

templates/careers/_filters.html

Remove part time filter from the careers list
- View the site locally in your web browser at: http://0.0.0.0:8002/career/all
- Check there is no "Part time" option in the FIlter by

Remove part time filter from the careers list

---

package.json
templates/index.html
templates/shared/_featured-news.html

**Note: This is a proof of concept and will require communication with the pdm to see what exactly information we need to pull from wordpress and thus updating of the `latest-news.js` module. We are using the `latest-news.js` module as if wordpress is down the page will still be able to load.**
- Include the `latest-news.js` module, can be found [here](https://github.com/canonical-web-and-design/latest-news)
- Add build commands to package.json
- Create custom template to render the individual cards
- Go to https://canonical-com-561.demos.haus/ and check that the most recent blog posts from the [featured tag](https://ubuntu.com/blog/tag/featured) are being rendered on the front page
- Try blocking the network request to wordpress and check the page still loads and the page flow is not …

Dynamically pull blog posts with featured tag and render then on the homepage

---

templates/careers/_filters.html

Remove the full-time option on job filters
- View the site locally in your web browser at: http://0.0.0.0:8002/career/all
- Check there is no "Full time" option in the FIlter by

Remove the full-time option on job filters

---

static/sass/styles.scss

Add "overflow-x : hidden" to `p-pull-quote--inverted` class
- View the site locally in your web browser at: http://0.0.0.0:8002/#careers or https://canonical-com-563.demos.haus/#careers and check the first column
Fixes #555

Hide horizontal scroll

---

webapp/app.py

Added a new simple route to handle /career/start as it doesn't require the vacancy data.
- Go to /careers/start?ga=123 and see it loads as expected
- Go to the live site at https://canonical.com/careers/start?ga=123 and see it 500's
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/590

Separate the careers/start route to a simple route

---

konf/site.yaml

- Separate canonical blog into a separate k8s service
- Redirect blog.canonical.com -> canonical.com/blog
- Go to https://blog.canonical.com/ should redirect now to https://canonical.com/blog
- Not sure how to QA the new /blog service, I don't think it will show up on `kubectl get deployments` until it's deploy to prod
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11841
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/572

Separate canonical.com/blog into a difference service

---

konf/site.yaml

Revert additional code of PR https://github.com/canonical-web-and-design/canonical.com/pull/592/files
- Check that https://canonical-com-594.demos.haus/blog works
- https://blog.canonical.com should redirect to https://ubuntu.com/blog

Revert blog service separation

---

static/sass/_pattern_footer.scss
templates/partial/_footer.html

- Added extra footer link only to careers pages as per [copy doc](https://docs.google.com/document/d/1ujvmMK1zUMXrUsc2zwl_hT1MrtOA9yymH1m4hyF708E/edit#)
- ~NOTE: need to confirm link url before this is ready for review~ link is https://ubuntu.com/legal/equal-employment-opportunity-commitment
- View the site locally in your web browser at: https://canonical-com-597.demos.haus/careers
- See that the Equal Employment Opportunity link is present in the footer
- Visit any other careers page like https://canonical-com-597.demos.haus/careers/start and see that the added footer link is still there
- Visit a non careers page like https://canonical-com-597.demos.haus/partners and see that the footer link is no longer …

Add extra footer link only to careers pages

---

webapp/app.py

- Fixed 500 errors on /careers/[slug] pages that don't show vacancies
- Visit https://canonical.com/
- Click "careers" in the top nav
- On the careers page, scroll to the "Diversity in our company is part of our strength" section and click the "Ethics" link
- See that the page 500s
- Visit https://canonical-com-607.demos.haus/
- Repeat the process to get to the ethics page
- Check that the page loads and doesn't result in a 500
Fixes https://github.com/canonical/canonical.com/issues/606

check "vacancies" is present in the context

---

templates/careers/job-detail.html
webapp/app.py

This was a request from Thibaut:
- updated the job detail page to allow youtube and vimeo videos added in greenhouse to show on the page
- added logic to ensure rendered iframes come only from youtube or vimeo
- visit https://canonical-com-609.demos.haus/careers/2955155
- see that a youtube video appears in the job description
The best way to verify that the youtube and vimeo restrictions work is:
- Check out this branch
- Update [this line](https://github.com/canonical/canonical.com/pull/609/files#diff-55f12a9f17b4ba61d3e37852150b7d78b8aedbe3629bc4ce8173d4b572297a54R461) to anything other than the two domains that are now
- `dotrun` the project
- visit http://0.0.0.0:8002/careers/2955155
- see that the video does not appear

update job postings to allow video embeds

---

static/sass/_pattern_application.scss
templates/careers/application/faq.html
webapp/application.py

Build an FAQ page on `/careers/application/faq`
Demo at https://canonical-com-619.demos.haus/careers/application/faq
- Compare page against [copy doc](https://docs.google.com/document/d/12_O_QtPqfv9p7kaDFdiP8Xq-kY5xa1XB-C-CRbXjDew/edit) and [design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?node-id=5916%3A8133)
Fixes #617

Build faq page

---

templates/careers/application/index.html
webapp/application.py

The application needs to display differently when candidates self-reject their applications and hiring leads reject their applications
QA below
-  If >48 hours: page is deleted (404 page displays)
-  If <48 hours AND the candidate was rejected by Canonical: status of page is unchanged (last step), remove application withdrawal section
- If <48 hours AND the candidate withdrew their application: status of page is unchanged, showing the [withdrawal confirmation page](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?node-id=5742%3A10530)
Fixes #624

Update view after rejection

---

templates/practice/documentation.html

-Add a meta tag to prevent documentation page from being indexed by search engines
Fixes #633

Add meta tag to hide documentation page from search engines

---

templates/careers/index.html

- Removed "Defining Excellence" and "Our vision of remote work" buttons as the pages they route to are still pending. 
- View the site locally in your web browser at: http://0.0.0.0:8002/careers 
- See that the 2 buttons have been removed

Remove buttons for pending pages

---

webapp/app.py

Allow href attribute on links in job descriptions
- Go to https://canonical.com/careers/3798310/technical-author-ubuntu-and-canonical-products-remote and see the link don't work
- Visit the same page on the demo and see they do
Fixes https://github.com/canonical/canonical.com/issues/640

Allow href attribute on links in job descriptions

---

templates/base_index.html

- Fix the theme color
- Go to https://canonical-com-643.demos.haus/ on Android (Chrome) or Safari (set the URL style to compact)
- Make sure that the color of the URL bar is Canonical's accent color (purple)
Fixes #641

change theme-color to Canonical's accent color

---

webapp/app.py

- Update the template path in the route
- Open the demo and add `/careers/start?_ga=2.14098167.1110780800.1665671000-167831397.1628077759` to the URL
- Check it works and in production, it doesn't
Fixes https://github.com/canonical/canonical.com/issues/657

Fix the /career/start path

---

templates/careers/index.html
templates/index.html

As requested by Emily Tu, adding tracking pixel for StackOverflow ad campaign. Instructions send to me over email.
> 1. Canonical_Homepage_Engagement Pixel_Page Views Pixel (ID: 4822915)
>     Only apply to https://canonical.com/
> 2. Canonical_Careers Page_Engagement Pixel_Page Views Pixel (ID: 4877251)
>     Only apply to https://canonical.com/careers
QA
--
Go to `/` and `/careers`. Check the code appears on those pages.

Add tracking pixels for StackOverflow advertising campaign

---

templates/careers/index.html

- Updated "View all departments" link to point to /careers/departments
- Visit https://canonical-com-662.demos.haus/careers
- Find the "View all departments" link and click it
- You should be taken to /careers/departments, not /careers/all
Fixes https://github.com/canonical/canonical.com/issues/661

update link on careers index

---

static/sass/_pattern_navigation.scss

Fix secondary nav bug
1. Click partners in the nav bar 
2. Scroll down the content and check the sticky nav bar displays above the content.
- Before
- After
Fixes #663

Fix secondary nav bug

---

static/js/source-inheritance.js
templates/base_index.html
templates/careers/base_job-details.html
templates/careers/job-detail.html

- Set a session storage key if the URL contains the param `gh_src`
- On the application page, read the session key and if populated sets the form field `mapped_url_token` which is [used by Greenhouse](https://developers.greenhouse.io/job-board.html#submit-an-application) to set the source of the application
- _Drive by_: Remove the search and filter JS from the apply page which was causing an error
- Open the demo and go to /careers/all
- Click on a job and inspect by the "Submit application" button that the input named `mapped_url_token` has a blank value
- Go back to the list
- Add the URL param `gh_src=campaign123` and load the page with that
- Check for errors in the console
- If none, visit a job again and see the `mapped_url_token` field is populated with "campaign123"
- Submit a …

Pass the gh_src URL param to the application

---

templates/partial/_navigation.html

Fixed the Products link
- Visit https://canonical-com-676.demos.haus/
- Click "Products"
- See you're scrolled to the products section on the homepage
- Visit https://canonical-com-676.demos.haus/partners
- Click "Products"
- See that you are taken back to the homepage and scrolled to the products section
Fixes https://github.com/canonical/canonical.com/issues/674

fix products link

---

static/js/careers-filter-and-sort.js

- Fix show all functionality when filtering via search bar
- View the site locally in your web browser at: https://canonical-com-690.demos.haus/careers/all?search=sales (feel free to use other keywords as well)
- Scroll to the end of the list and ensure that the "show all" button works as expected
Fixes https://github.com/canonical/canonical.com/issues/682

Fix show all functionality

---

templates/careers/application/index.html
webapp/application.py

Since some applications don't have a job post id, and this is only used in the heading, I think the simplest option is use internal Greenhouse job name if the job post is not available.
- `dotrun`
-  View the site locally in your web browser at: http://0.0.0.0:8002/
- Go to the candidate page in #698 and check that it's rendered
Fixes #698

Allow job post id to be null

---

templates/partners/become-a-partner.html

Fix Become a partner submission form. Currently it's failing with nginx error
- Go to https://canonical-com-695.demos.haus/partners/become-a-partner
- Fill out the "About you" form (you can do it with "test" data)
- If submission is successful, you should be redirected to the thank-you page
Additional checks:
- Marketo should get a submission
Fixes https://github.com/canonical/ubuntu.com/issues/12287

Fix become a partner submission form

---

templates/index.html
tests/cypress/integration/sample_spec.js

Added space in title
- Go to https://canonical-com-702.demos.haus/, check that `maintain,secure` have space now in mobile view
Before:
Fixes https://github.com/canonical/canonical.com/issues/693

Fix mobile homepage

---

static/js/navigation.js
templates/partial/_navigation.html

Fix 'products' navigation link
Updated the GA events id, so that they use a more unique name.
- Go to https://canonical-com-703.demos.haus/
- Click on the "Products" link in the navigation, make sure it now scrolls to the "products" section
Fixes https://github.com/canonical/canonical.com/issues/696

Fix 'products' navigation link

---

static/js/careers-filter-and-sort.js
static/sass/_pattern_search-form.scss
templates/careers/_search.html
templates/careers/all.html
templates/careers/base.html
templates/partial/_careers-available-roles.html
templates/partial/_careers-navigation.html
webapp/app.py

- Applied styling updates based on [mock-up](https://www.figma.com/file/UsovUAf4zELQgGd9bxhiVe/Careers?node-id=310%3A1822&t=JxZNmeLpAdpskinS-0)
- Applied requested order to departments
- View the site locally in your web browser at: https://canonical-com-697.demos.haus/careers/all
- See that the page matches the mock-up and that filters work as expected
Fixes https://warthogs.atlassian.net/browse/WD-677

Apply redesign and re-order departments

---

webapp/app.py
webapp/partners.py

Remove the dependency on the partners API from the index view.
Fixes #196
Go to [the demo](https://canonical-com-717.demos.haus), check the homepage works.

Remove get_partner_groups from homepage view

---

templates/careers/diversity/identity.html
templates/careers/diversity/index.html
templates/careers/ethics.html
templates/careers/lifestyle.html
templates/careers/progression.html
templates/careers/travel.html

- Removed filters from pages that no longer need them.
These pages used to be tabs that were accessible via the all roles page. The design of that page has changed and no longer includes these tabs, it doesn't make sense to show the filters on these pages anymore. 
- Visit the following pages:
- https://canonical-com-711.demos.haus/careers/diversity/identity
- https://canonical-com-711.demos.haus/careers/diversity
- https://canonical-com-711.demos.haus/careers/ethics
- https://canonical-com-711.demos.haus/careers/lifestyle
- https://canonical-com-711.demos.haus/careers/progression
- https://canonical-com-711.demos.haus/travel
- See that department and location filters have been removed 
Fixes …

Remove filters from pages no longer tied to all roles

---

templates/partial/_navigation.html

Made the Products nav item's URL absolute, not relative
- Visit https://canonical-com-718.demos.haus/
- Click "Products"
- See that you're taken to the Products section on the homepage
- Visit any other page i.e. /blog
- Click "Products"
- See that you're taken the same section on the homepage
Fixes https://github.com/canonical/canonical.com/issues/715

fix products nav issue

---

webapp/app.py

- added missing view helper to the blog
- Visit https://canonical-com-719.demos.haus/blog/archives?year=2019&month=5
- A page with blog listings should appear (on live this same URL leads to a 500)
Fixes https://github.com/canonical/canonical.com/issues/716

add missing month_name context method

---

templates/careers/engineering.html

- Fixed typo on engineering dept page
- View the site locally in your web browser at: https://canonical-com-738.demos.haus/careers/engineering
- See that the CTA copy says "See all Engineering roles" instead of "Se all Engineering roles"
Fixes https://warthogs.atlassian.net/browse/WD-1000

Fix typo on engineering dept page

---

templates/careers/application/index.html

- Comments out the html responsible for application withdrawal as it is currently throwing an error on sentry. This is a temporary fix.
- Go to [this link](https://pastebin.canonical.com/p/NGsqcPqNKT/) and scroll to the bottom of the page. See that application withdrawal is not visible.
Fixes https://github.com/canonical/canonical.com/issues/740

Hide application withdrawal

---

templates/careers/_search.html

- The package used (Fuse JS) can take strings and arrays of strings, see [docs](https://fusejs.io/api/options.html#keys). This pr adds 'skills' to the list of keys
- Go to [canonical.com/careers](https://canonical.com/careers), the current live page,  and input the skill 'analysers'. You will get no results.
- Go to https://canonical-com-739.demos.haus/careers demo, and input the skill 'analysers'. You will get some results.
Fixes https://github.com/canonical/canonical.com/issues/681

Expand careers search to also search by skills

---

templates/partial/_navigation.html

Remove Working at Canonical from the menu temporarily
- Click Careers in the navigation
- See there is no "Working at Canonical" link

WD-1142 Remove Working at Canonical from the menu

---

static/js/careers-filter-and-sort.js
templates/careers/_search.html
tests/test_greenhouse.py
webapp/app.py
webapp/greenhouse.py

Make the number of returned roles on https://canonical-com-751.demos.haus/careers/all for each department matches the numbers declared on https://canonical-com-751.demos.haus/careers.
The issue was that https://canonical-com-751.demos.haus/careers/all wasn't respecting the fact that many vacancies actually have more than one department assigned - it was just matching based on the first department.
- WD-1163: Turn vacancy.departments into a proper array
- WD-1163: Rename departments within greenhouse.py
In doing this work I've run into many ideas for restructuring the code, and a couple more bugs. I've stored them in this Jira issue:
https://warthogs.atlassian.net/browse/WD-1216
Go to https://canonical-com-751.demos.haus/careers, look at the numbers. Now click through to …

WD-1163: Fix number of roles in /careers/all

---

templates/base_index.html
templates/careers/_vacancies-modal.html
templates/careers/apply.html
templates/careers/career-explorer.html
templates/partners/find-a-partner.html

Otherwise, whenever these files are changed they will take a whole day
to work in production (because /static files have stale-while-revalidate: 86400)
Go to these pages:
https://canonical-com-753.demos.haus/
https://canonical-com-753.demos.haus/careers
https://canonical-com-753.demos.haus/careers/all
https://canonical-com-753.demos.haus/partners/find-a-partner
https://canonical-com-753.demos.haus/careers/career-explorer
Check they still work, especially JavaScript functions. Look in source, check all `/static/js` links have `?v=xxxx` suffixes.

Add cachebusting version strings to all /static/js files

---

templates/practice/documentation.html

Remove a broken link from /practice/documentation, based on the [copydoc](https://docs.google.com/document/d/10tOsj5kKZRddQYYkb1PgxsES47Qic8XJc9xpRaYHd7s/edit)
- Go to https://canonical-com-758.demos.haus/practice/documentation and check the link has been removed
Fixes https://warthogs.atlassian.net/browse/WD-1351

Remove broken link from /practice/documentation

---

static/js/careers-filter-and-sort.js
templates/careers/_search.html

- Added functionality to update the URL when search input is cleared
- Removed old function that did handled this in a past iteration as it was triggered by an element that no longer exists in the current design
- View the site locally in your web browser at: https://canonical-com-762.demos.haus/careers/all
- Search for 'python' (or anything else)
- Once your results are loaded click on the 'x' in the search box and see that search params have cleared form URL
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932?modal=detail&selectedIssue=WD-1172

Update URL on input clear

---

templates/careers/application/index.html

Do not render the link if the id is `None`
Update the wording on the link to make it clearer its a link and not an empty section
- Use the following URL to check the link looks good: https://pastebin.canonical.com/p/GCwTmjXj8z/

WD-1449 Improve the link to the JD from the candidates page

---

static/sass/styles.scss
templates/careers/base_job-details.html
templates/careers/job-detail.html

- Separated application form and job description 
- View the site locally in your web browser at: https://canonical-com-759.demos.haus/careers/all
- Click on any job posting on and see that you only see the job description
- Scroll down and click "Apply" and see that you are taken to the form and that the url now has the `/application` in the path
- At the top of the page click "Back to role description" and see that the form is once again hidden and the url does not have `/aplication` in the path 
Fixes https://warthogs.atlassian.net/browse/WD-958

Split role description and application form

---

webapp/greenhouse.py

- Added requisition ID to job description as per request
- View the site locally in your web browser at: https://canonical-com-772.demos.haus/careers/4630475 (or any other job)
- See that the requisition ID has been added to the bottom of the job description and that the copy matches what was requested in the issue
Fixes https://warthogs.atlassian.net/browse/WD-1141

Add req id to job content

---

static/sass/_pattern_search-form.scss
static/sass/styles.scss
templates/shared/_fast_track_jobs.html
templates/shared/_featured_jobs.html

- Fixed search width
- Changed copy from "jobs" to "roles"
- Fixed asymmetrical separators
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/engineering (please also check multiple departments)
- Make sure the bugs listed in linked issue are no longer present
Fixes https://warthogs.atlassian.net/browse/WD-1785

Fix search width and featured roles copy

---

templates/index.html

A new link has been added to the homepage's circle of products image, which leads to the products page (https://canonical.com/#products) when clicked.
Alt text for the image has changed to Canonical Products.
Fixes #168 

Add link with circle of products image to the products page

---

templates/documentation/index.html

Update meta-description on /documentation based on [the copydoc](https://docs.google.com/document/d/10tOsj5kKZRddQYYkb1PgxsES47Qic8XJc9xpRaYHd7s/edit)
- Visit the page at https://canonical-com-790.demos.haus/documentation and check the head for the correct meta description

Update meta-description on /documentation

---

static/js/find-a-partner.js

- Fixed the search filter. Made it work with both lower-case and upper-case search values.
- Check out the demo on https://canonical-com-801.demos.haus/partners/find-a-partner and ensure the search filter works with lower-case and upper-case inputs, eg: `DELL`, `Dell`, and `dell` should all bring out search results for Dell Technologies.
- You can also test the filter for other partners as well. It should work for all.
- [WD-2116](https://warthogs.atlassian.net/browse/WD-2116)
[WD-2116]: https://warthogs.atlassian.net/browse/WD-2116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-2116 make search work with lower and upper case

---

static/sass/styles.scss

Remove the job description overriding styling to fix the breakage of the use of `p-text--x-small-capitalised u-align-text--x-small-to-default u-no-margin--bottom`
- Open the demo and go to /careers/engineering
- See that the titles "Expertise" and  "Featured Roles" are small and capitalised
- Check production is not.
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1413534/220339262-b0b58fa2-1620-4003-94ac-b920eab142fd.png) | ![image](https://user-images.githubusercontent.com/1413534/220338904-b64504e2-054e-4514-aaec-818d871754e1.png) |

Remove the job description overriding styling

---

static/sass/styles.scss
templates/documentation/beyond-canonical.html
templates/documentation/index.html
templates/documentation/work-and-careers.html

- Fix z-indexing on /documentation
- Make navigation drawer flush with navigation
- Go to https://canonical-com-804.demos.haus/documentation on mobile view or a small screen
- Check that when a drop down from the top-navigation is open, it goes over the side-navigation
- Check the navigation drawer is flush with the navigation.
Fixes https://github.com/canonical/canonical.com/issues/803
before:
after:
before:
after:
before:

Fix z-indexing on /documentation

---

templates/shared/_promoted_roles.html

Remove the fast-track roles from departments pages
- Open the demo and go to /careers/engineering
- See there are no fast track/expertise roles

WD-2138 Remove the fast track roles from departments pages

---

static/js/careers-filter-and-sort.js
templates/partial/_careers-available-roles.html

- Fixed the logic detecting and showing the no roles message
- Updated the message to match the Vanilla empty state styling
- Run prettier on the JS file
- Open the demo and go to /careers/all?filter=Administration
- See there is a message warning of no roles
- Click another department and see the message is removed and the roles are listed correctly.

WD-2031 Add a no roles message to careers departments with no open roles

---

templates/careers/base.html

This removes the location filters from the results page of the career explorer game. This is a temporary fix while we wait for the [redesign](https://github.com/canonical/canonical.com/pull/794) to be applied. 
- Open the [demo](https://canonical-com-820.demos.haus/careers/results?core-skills=Developer,Scientist,Organiser,Analyzer,Manager) or complete the game yourself to get to the results page
- See that the location filters have been removed, compared with [live site](https://canonical.com/careers/results?core-skills=Developer,Organiser,Scientist,Analyzer,Manager)
This was mentioned in https://github.com/canonical/canonical.com/issues/819 ("Specific list of actions which produce unexpected or unhelpful …

Remove location filters from explorer results

---

templates/careers/application/index.html
webapp/application.py

- Update smtp credentials on production/staging
- Revert https://github.com/canonical/canonical.com/pull/741
- I made a testing endpoint locally and sent myself an email with those credentials and got it! You can do the same locally on the file `webapp/application.py`:
```python
@application.route("/testing")
def testing():
_send_mail(["<USE YOUR EMAIL>@canonical.com"], "lol", "lol")
return ""
```
- Add credentials to `.env.local`
- connect to the VPN and `dotrun`
- http://0.0.0.0:8002/careers/application/testing
- Check your inbox and make sure you got an email from the right person :)
Fixes https://warthogs.atlassian.net/browse/WD-1005

Enable back withdraw application

---

templates/shared/_fast_track_jobs.html
templates/shared/_featured_jobs.html

- Go to e.g. https://canonical-com-837.demos.haus/careers/finance
- Click on one of the featured roles and check on [GA](https://analytics.google.com/analytics/web/#/realtime/rt-event/a1018242w108544136p153647982/filter.list=14==(none);7==(direct)/) that the event action shows up?

WD-2082 Add analytics to fast track and featured roles

---

templates/partial/_footer.html

Fixing "recruitment" typo in the footer. 
- Go to demo
- Check footer, does it say recruitment or "recruiment"
Fixes https://github.com/canonical/canonical.com/issues/842#event-9057969398

Fixing "recruitment" typo

---

templates/careers/company-culture.html

Wraps hanging paragraph in a col element to fix issues with misaligned grid on Careers Culture page
- Go to Company Culture page, make sure "We're Canonical" section grid is correctly spaced (4 columns of equal width)

Fix grid in "We're Canonical" section

---

static/sass/_pattern_footer.scss
static/sass/_pattern_strip.scss
static/sass/styles.scss
templates/partial/_partners-footer.html
templates/partners/index.html

- Added Silicon section to the partners page ([doc](https://docs.google.com/document/d/1q6dkqQ0zcshrfOmdJA_bAip73EaMSEyXAn8bAD7GqNw/edit#heading=h.c32qy927hx83) out of date, please check against existing page)
- Applied redesign as per [mock up](https://www.figma.com/file/a84HnjH4M3E8KErVkPq9eW/Canonical.com%2Fpartners?node-id=1-1147&t=DeygTIESmpYEySFR-0)
- View the site locally in your web browser at: https://canonical-com-839.demos.haus/partners
- See that the requested changes were made (Only already live partners and Silicon should be on the page, please ignore the rest of the partners on the doc)
- See that the page matches desgin 
Fixes https://warthogs.atlassian.net/browse/WD-3124

/partners redesign 

---

templates/careers/application/_withdrawal_notification-email.html
templates/careers/application/withdrawal.html
webapp/application.py

When a candidate withdraws send email to notify the hiring lead(s)
- go to a candidate's application page
- withdraw the application
- at the end you should see a debug email that should be sent to the hiring lead (emails cannot be sent locally)

on candidate withdrawal send email to hiring lead - WD-2917 

---

templates/careers/company-culture.html

Keep consistency across careers blockquotes, similar to /careers/company-culture
- Go to https://canonical-com-869.demos.haus/careers/company-culture and check that quotes look the same as https://canonical-com-869.demos.haus/careers/company-culture/diversity. The double quotes should be now "inside", as requested in the [Jira ticket](https://warthogs.atlassian.net/browse/WD-3415?atlOrigin=eyJpIjoiNDYxMzgxOWYzOWU5NGI3MWE5YTk3M2VmMmNjYWVmZjciLCJwIjoiaiJ9)

WD-3415 Design consistency for blockquote pattern

---

templates/careers/job-detail.html
webapp/greenhouse.py

Render the input descriptions as input help text.
Parse the descriptions to remove `<p>`'s
- Go to /careers/4754075/application
- Check some inputs have descriptions
- Check they have the appropriate `aria-describedby` attributes
Fixes https://warthogs.atlassian.net/browse/WD-4367

WD-4367 Add help text to career applications form

---

templates/careers/application/index.html
templates/careers/application/partial/_assessment.html
webapp/application.py

1. Simplify the template logic by parsing a reliable job post name before passing it to the context.
2. Added logic to check for the applied job id matches the job post id. If it does its a post from the same job. If not, the role has been transferred and we need to render the job_name.
3. _Drive by_: converted the `elif` to a `else` as we want one to always be true. Which fixed a rendering issue in production.
- Open the demo and go to [these URLs](https://pastebin.canonical.com/p/3MnyxvkY3P/) to check they render as expected.
- Check that the first URL in the pastebin renders correctly after the assessment stage unlike production
Fixes https://warthogs.atlassian.net/browse/WD-4421

WD-4421 Update application job name when transferring roles

---

templates/partners/iot-device.html
templates/partners/partial/_footer.html

Revert to previous design as per discussion with @juanruitina 
- Check that the partners footer is in a 2 6-col layout, check links go to the correct places
Fixes https://warthogs.atlassian.net/browse/WD-4674

Wd 4674 visual update partners pages footer

---

webapp/static_data.py

Changed the LXD product URL from the Linux Containers page to the Ubuntu LXD page
Fixes https://github.com/canonical/canonical.com/issues/892
- Open demo 
- Go to 'products' section and now both the logo and URL for the LXD product should be linked to the requested URL  
- Change made in the webapp > static_data.py file - the new product URL should pull through to the site home page

Change LXD product URL

---

templates/401.html
templates/404.html
templates/500.html
templates/502.html
templates/_error.tmpl
templates/base_index.html
templates/partial/_footer.html
templates/partners/partial/_footer.html

Rebuiuld the 404 page as per teh design (sans thge enrichment isometric illustration).
Driveby: Make  footer stick to the bottom of the window.
- Check against hthe design
Fixes https://warthogs.atlassian.net/browse/WD-3807

Update error pages

---

templates/careers/application/faq.html

Add the "Why is there a requirement for the Written Interview to be submitted anonymously?" section to the FAQ page.
- Go to /career/application/faq in the demo
- Check the content matches the [copy doc](https://docs.google.com/document/d/12_O_QtPqfv9p7kaDFdiP8Xq-kY5xa1XB-C-CRbXjDew/edit)
Fixes https://warthogs.atlassian.net/browse/WD-4941

WD-4941 - Add FAQ section about WI anonymously

---

templates/careers/company-culture/progression.html
webapp/app.py

- Update [images](https://warthogs.atlassian.net/browse/WD-4595?atlOrigin=eyJpIjoiYzQ2NWQ5ZGZkM2JiNDRhNmE0M2M3Mzk2MTg2MWZlMzMiLCJwIjoiaiJ9)
- Update text according to [copy doc](https://docs.google.com/document/d/1NqSg2dt5wbmSY6IwWKo9gbxzOuyKL_gUZnFlAux1RU8/edit?disco=AAAAx5tfmxU)
- Go to https://canonical-com-906.demos.haus/careers/company-culture/progression scroll down to "Explore diverse roles" section and check that it's been updated with the [new images](https://warthogs.atlassian.net/browse/WD-4595?atlOrigin=eyJpIjoiYzQ2NWQ5ZGZkM2JiNDRhNmE0M2M3Mzk2MTg2MWZlMzMiLCJwIjoiaiJ9)
- Check also against [copy doc text update](https://docs.google.com/document/d/1NqSg2dt5wbmSY6IwWKo9gbxzOuyKL_gUZnFlAux1RU8/edit?disco=AAAAx5tfmxU)
Fixes …

Update career progression images and text

---

static/sass/styles.scss

Update the accent color on the site which is used for the navigation tag by Vanilla.
- Open the demo and see the logo is orange and not aubergine anymore
Fixes https://warthogs.atlassian.net/browse/WD-4982

WD-4982 - Make the navigation tag orange

---

static/sass/styles.scss
templates/documentation/_documentation-header.html
templates/documentation/_documentation-tab-navigation.html
templates/documentation/beyond-canonical.html
templates/documentation/index.html
templates/documentation/work-and-careers.html

Based on @mtruj013's [pr](https://github.com/canonical/canonical.com/pull/905). I changed a few things so pushing to a separate pr so as to not break anything.
This is a bit different from the design, as I talked to Daniele since we did the pages and he expressed a preference for a denser treatment on documentation pages, and liked placing headings on the side and clamping the heading hierarchy to h4. 
- Check tab functionality on all 3 tabs
Fixes https://warthogs.atlassian.net/browse/WD-3737

Documentation practice

---

templates/partial/_navigation.html

During demo review I realized that there are repeated links to the documentation page on the careers nav. UX has requested that the first one be removed that the "company culture" children be ordered as follows: Remote work, Diversity, Progression, Sustainability
- Updated careers nav according to above specification 
- View the site locally in your web browser at: https://canonical-com-933.demos.haus/
- See that the updates have been made
Fixes https://warthogs.atlassian.net/browse/WD-4990

Update careers nav

---

templates/partial/_navigation.html
templates/partners/index.html

- Updated partners nav and /partners copy as per request:
- Navigation: under “Partners”, rename “Internet of Things device” to “IoT devices”
- Programmes page: rename “IoT Device” as “IoT devices”.
- See that the changes have been made
Fixes https://warthogs.atlassian.net/browse/WD-4998

Update partners nav and /partners copy

---

templates/careers/application/_withdrawal_notification-email.html
webapp/application.py

- Improved the messaging by using the parsed job title value. Therefore if they apply to Engineering Manager - Web they see that job role title instead of just Web Developer which is the Job title.
- Added information to the hiring lead email to include the current stage name of the candidate to speed up actions.
- Create a job (or reopen a closed application) on the test position
- Run this branch locally and visit the application page
- Withdraw and see the email sent to the candidate
- Click the link to confirm
- See the email sent to the hiring lead contains the current stage
Fixes https://warthogs.atlassian.net/browse/WD-5009

WD-5009 - Improve the withdrawal email to include current stage

---

static/sass/styles.scss
templates/careers/_careers-pagination.html
templates/careers/_search.html
templates/careers/company-culture/sustainability.html
templates/shared/_featured_jobs.html

- Fixed alignment for careers search 
- Fixed third pillar card position on /sustainability
- Fixed featured roles alignment on mobile
All other bugs mentioned in linked ticket were already resolved on this branch.
- View the site locally in your web browser at: https://canonical-com-947.demos.haus/careers/company-culture/remote-work
- See that the alignment of the input field relative to the button has been fixed
- Note: this is a shared partial and can also be checked under /careers and /careers/all
- View the site locally in your web browser at: https://canonical-com-947.demos.haus/careers/company-culture/sustainability
- See that third key pillar is now correctly aligned
- View the site locally in your web …

Fix careers bugs/styling issues

---

static/sass/styles.scss

Fixes https://github.com/canonical/vanilla-framework/issues/4816
- Go to /documentation
- Make screen small as mobile view
- Open side navigation
- Scroll the page, make sure horizontal rules from content don't overflow the side navigation

Fix rules showing on top of side navigation

---

templates/partners/partial/_partners-logos.html

- Filter out Nec logo
- View the site locally in your web browser at: https://canonical-com-964.demos.haus/partners/ihv-and-oem
- See that the logo no longer appears
Fixes https://warthogs.atlassian.net/browse/WD-5138
Before: 
After:

Filter out nec logo

---

static/sass/styles.scss
templates/careers/company-culture.html
templates/index.html

- Fix spacing between headings as [per design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=11270%3A26788&mode=design&t=r71PtO3zN3fjUZBA-1):
before:
after:
- refactor: remove old is-bold class from hrs, it doesn't do anything
- fix logos on homepage to be variable width, equally spaced
- fix local css so wrapping logos are not indented:
before: 
after:
- remove spacing between two headings (pointed out by @marcushas)
before: 
after:
- verify the above list of fixes
Fixes #

Visual fixes

---

templates/careers/application/partial/_late-stage.html

- Include executive review in the late stage so interviews show up on the page
- Open demo
- Visit the candidate page included in the ticket below 
- If you do it before the 17th you should see an interview with the CEO with the label "next interviews" on top
- If you do it after, it will appear as a "past interview"
https://warthogs.atlassian.net/browse/WD-5063

candidate page: add executive review to late stage

---

templates/careers/application/_interview-card-done.html

- Multiple typos in `_interview-card-done.html` fixed.
I didn't think that filing an issue would be appropriate for such a small change, but I can do so if that would be helpful. 🙂

Fix typos in interview-done card

---

redirects.yaml

- Check https://canonical-com-986.demos.haus/enterprise-services/ubuntu-advantage goes to https://ubuntu.com/pro now
Fixes https://warthogs.atlassian.net/browse/WD-5279
Fixes https://github.com/canonical/canonical.com/issues/885

Fix 404 Redirect enterprise services to Ubuntu Pro

---

templates/partial/_navigation.html

- Change nav item from "Global Seller Initiative" to "Global System Integrators" as per ticket 
- Visit the demo: https://canonical-com-990.demos.haus/
- Toggle the partners drop down and see that the change was made
Fixes https://warthogs.atlassian.net/browse/WD-5252

Update partners nav item

---

templates/partial/_footer.html

- Update privacy policy text
- Check out [the demo here](https://canonical-com-992.demos.haus/) and compare it to the work specified in the [task](https://warthogs.atlassian.net/browse/WD-5286).
- Make the privacy policy notice says **"For further information on data collection, please refer to our [privacy policy](https://ubuntu.com/legal/data-privacy)."** for all pages except `/careers` pages.
- For `/careers` pages it should say **"For further information on data collection, please refer to our [recruitment privacy notice](https://ubuntu.com/legal/data-privacy/recruitment) and [privacy policy](https://ubuntu.com/legal/data-privacy)."**
- [WD-5286](https://warthogs.atlassian.net/browse/WD-5286)
[WD-5286]: https://warthogs.atlassian.net/browse/WD-5286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

[copy update] WD-5286 update on footer privacy policy link

---

templates/documentation/work-and-careers.html

- Removed the second "not" in the copy per the [doc](https://docs.google.com/document/d/1U-IkZOMzQlfV0zAAmM0PRVUBoZNBeOa-Qrso3i4rDVU/edit)
- View the site locally in your web browser at: https://canonical-com-1000.demos.haus/documentation/work-and-careers
- See that the typo is fixed
Fixes https://warthogs.atlassian.net/browse/WD-5526

Fix documentation typo

---

webapp/app.py

Restore /blog/tag/lang:kr. As originally [requested on MM](https://chat.canonical.com/canonical/pl/ccunnwh8iigr3bn1gpc37acd5o)
- https://canonical-com-1007.demos.haus/blog/tag/lang:kr should work now
- https://canonical-com-1007.demos.haus/blog should not have blogs in Korean (using this tag).
Fixes https://warthogs.atlassian.net/browse/WD-5635?atlOrigin=eyJpIjoiMzgwMWU1YzE4ZmUzNGJhZTg0NjNiZDJjZTgxMjI5OWUiLCJwIjoiaiJ9

Restore blogs tag page

---

templates/index.html

The `.p-logo-section__logo` is meant to be put on the logo image element. On home page it's set both on the image and on wrapping div which can lead to some unexpected bugs.
This removes unnecessary wrapping divs from logos.
- Go to home page, find logo sections, make sure there is no div with `p-logo-section__logo` class around the images.

Remove unnecessary div from logo sections

---

templates/base_index.html
templates/careers/job-detail.html
templates/partial/_footer.html

- Updated careers pages meta-image
Originally this ticket only covered the individual job posts, but Camille rightly flagged that the meta-image for the careers index page is currently showing up as the suru when she goes to post it on linkedin so I implemented the change on all careers pages
- View the site locally in your web browser at: https://canonical-com-1012.demos.haus/careers/5243483 (or any other job opening)
- View the page source and check that the image is the correct one
- Do the same for the careers pages (don't need to check all of them, this should cover anything with /careers in the path)
Fixes https://warthogs.atlassian.net/browse/WD-5637
Before:
After:
Before:
After:

Update careers pages meta-image

---

templates/careers/index.html

- Updated page title and description as per [doc](https://docs.google.com/document/d/1o8ind3Zav-kwrUDWgiMJnkw2QLpniKgdlWrw9byIvlE/edit)
- View the site locally in your web browser at: https://canonical-com-1015.demos.haus/careers
- View source and see that the change shows up correctly 
Fixes https://warthogs.atlassian.net/browse/WD-5729

Update careers index meta data

---

templates/base_index.html

Replace the broken favicon with a PNG version
- Check the favicon loads in the tab when opening the demo
- Check the demo URL with https://realfavicongenerator.net/favicon_checker
Fixes https://warthogs.atlassian.net/browse/WD-5430

WD-5430 - Replace the broken favicon with a PNG version

---

static/sass/styles.scss
templates/partners/executive-summit.html

- Update summit even dates and links
- Move the Paris Summit to the past events section
- Check out [the demo here](https://canonical-com-1009.demos.haus/partners/executive-summit) and compare it with the changes requested in [the copy doc](https://docs.google.com/document/d/15C3k-htvapwp-WTrYQ2SdHBW20Lp9IinpY9mkvo6q3U/edit).
- [WD-5625](https://warthogs.atlassian.net/browse/WD-5625)
[WD-5625]: https://warthogs.atlassian.net/browse/WD-5625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-5625 Update executive summit events

---

redirects.yaml

Add redirect for /enterprise-services to ubuntu.com/support
- Go to /enterprise-services
- See that it redirects to ubuntu.com/support
Fixes https://warthogs.atlassian.net/browse/WD-5751
Fixes https://github.com/canonical/canonical.com/issues/1004

WD-5751 - Add redirect for /enterprise-services

---

templates/careers/application/_withdrawal-form.html
templates/careers/application/index.html

Navigation on application page was broken. This was because there is a duplication of modal functionality, which already exists on /js/modals.js.
- Go to an application page e.g. https://canonical-com-1040.demos.haus/careers/application/gAAAAABjX6OTC4h0nMj9zgQbSR4AeKZ4rLasVjmZKhoSbNCYqO8tNAilVS75NKwArileTUXZV72MI08EcukQokHOP0ZUp0gthw== and check navigation is no longer broken
- Check that application withdrawal modal opens
Fixes https://warthogs.atlassian.net/browse/WD-6068
Close https://github.com/canonical/canonical.com/issues/1024

WD-6068 Fix navigation on application page

---

templates/blog/article.html

Update the canonical URL for articles authored by Canonical
- Go to /blog
- Open an article by someone else then Canonical and view-source
- See that the `rel="canonical"` points to ubuntu.com/blog
- Go back and open an article from Canonical and view-source
- See that the `rel="canonical"` points to canonical.com/blog
There are some tags which might mix this up a little.
Fixes https://warthogs.atlassian.net/browse/WD-6197

WD-6197 - Update the canonical URL for articles authored by Canonical

---

templates/contact-us.html
templates/index.html
templates/partners/partial/_homepage-form.html

Added modal form for contact-us page and update aria-controls identifer
- Check https://canonical-com-1039.demos.haus/contact-us with [copy doc](https://docs.google.com/document/d/1Qxvhl6_kgCDarcem1wcFPQyHk0JEFUP1zIzNsIrT3_Y/edit) comment
- Open the modal and fill up the form
Fixes https://warthogs.atlassian.net/browse/WD-6223

Add modal form for Canonical /contact-us

---

templates/base_index.html

Null check the query selector as this does not always return results on all pages.
- Follow the steps in the issue and see that it's gone in the demo.
Fixes https://github.com/canonical/canonical.com/issues/998

Null check the UTM search field

---

templates/data/mongodb.html
templates/data/opensearch.html
templates/data/spark.html

Update Kubernetes logos.
- Go to 
https://canonical-com-1089.demos.haus/data/mongodb
https://canonical-com-1089.demos.haus/data/opensearch
https://canonical-com-1089.demos.haus/data/spark
and check that kubernetes logos have been replaced by the https://assets.ubuntu.com/v1/cd1a01d0-kubernetes-logomark-logo.png
Fixes https://warthogs.atlassian.net/browse/WD-6862

Update Kubernetes logos

---

templates/documentation/_documentation-tab-navigation.html
templates/documentation/open-documentation-academy.html

Add the Open Documentation Academy page
- Go to /documentation/open-documentation-academy
- Ensure the content matches [the copy doc](https://docs.google.com/document/d/1nhy653-SOfTmGCIiSZHuGBCrwZlzEZJaA4kFBsw-5dc/edit)
Fixes https://warthogs.atlassian.net/browse/WD-6868

WD-6868 - Add the Open Documentation Academy page

---

templates/careers/_base-department.html
templates/careers/engineering.html
templates/shared/_engineering-fast-track.html

- create 'Apply based on' section for "fast-track" positions in `/careers/engineering`
- modify 'Featured roles' section in `/careers/engineering` according to [Figma designs](https://www.figma.com/file/c4QYGBPZl5hxr5XrziIVZA/23.10-C.com---%2Fcareers%2Fengineering-(Fast-tracks)?type=design&node-id=98-5748&mode=design&t=LRqU0MZl4Xk191vG-4)
- edit the first section in `/careers/engineering` also according to design
- Open /careers/engineering and check the changes in first three sections
- Open other /careers pages and check that nothing changed
Closes …

[WD-6796] modify sections in /careers/engineering

---

static/sass/_pattern_global-nav.scss
templates/microcloud/contact-us.html
templates/microcloud/thank-you.html
templates/partial/_data-navigation.html
templates/partial/_microcloud-navigation.html
templates/partial/_navigation.html

- Added form as per [doc](https://docs.google.com/document/d/1gIqyGENG6YQm0OH7WIS893stAzWZukfCtFD05bHr4pY/edit) and [design](https://www.figma.com/file/hzQYJM9Tui4wpmyZC0k0WS/23.10-C.com---MicroCloud-Rebranding?node-id=4%3A5822&mode=dev)
- Added subnav (no design provided)
- Drive by: slight class rename to make clear that the subnav styles are reusable and not just for one microsite 
**NOTE: Resource tab will 404 as that page hasn't been merged into the feature branch yet**
- View the site locally in your web browser at: https://canonical-com-1102.demos.haus/microcloud/contact-us
- Click through the subnav and ensure that everything works as expected (again, /resources will 404 until https://github.com/canonical/canonical.com/pull/1097 is merged)
Fixes …

Add microcloud subnav and form

---

templates/microcloud/_microcloud-modal.html
templates/microcloud/index.html

- Added microcloud modal and applied design suggestions as noted [here](https://github.com/canonical/canonical.com/pull/1103#issuecomment-1792155801)
- View the site locally in your web browser at: https://canonical-com-1109.demos.haus/microcloud
- See that the requested changes linked above were made
- Click on the modal CTA ("Get in touch" button in hero) 
- There are 2 other CTAs on this page which will not work until https://github.com/canonical/canonical.com/pull/1102 is merged
- No doc or design, should match [current canonical modal style](https://canonical.com/data/mongodb) and [microcloud live modal copy](https://microcloud.is/#get-in-touch)
Fixes https://warthogs.atlassian.net/browse/WD-6693

Add modal and apply minor design updates to landing page

---

templates/microcloud/roadshow.html

- Fixed two "MicroCoud" typos in roadshow page
- Go to `/microcloud/roadshow` - [DEMO LINK](https://canonical-com-1116.demos.haus/microcloud/roadshow)
- Check that there are no more "MicroCoud" typos

fix(microcloud) two typos in roadshow page ("MicroCoud" -> "MicroCloud")

---

templates/careers/base_job-details.html
templates/careers/job-detail.html
webapp/app.py

Fix [Jira ticket](https://warthogs.atlassian.net/browse/WD-6775) /careers/5172749
Swapped the Greenhouse job-boards API endpoint with Harvest API job post endpoint. The GH job boards API doesn't return job posts that have been flagged `inactive` or `not live`
Most of the files changed are due to the different data structure that this API returns, but the data seems to match.
- Go to https://canonical-com-1100.demos.haus/careers/5172749 should work now
- Button to apply should not show on the page (the harvest endpoint will return 401 upon submission of application)
Regression check:
- Go to e.g. https://canonical-com-1100.demos.haus/careers/4417916
- Click "Apply now" and fill out the application
- Go to Greenhouse and check that the application submitted successfully and correctly (check …

Fix application job post id

---

templates/careers/application/index.html

- Add diversity button on application page [here](https://canonical-com-1139.demos.haus/careers/application/gAAAAABlS9tm8wZ21ysWXa4qkfl6aCQrMe_EQSSRGoZSOmGBNs54u1_Gvo3ZYMTK45liyClBHpNOupkoFCoyVzLvP4UjZWllMg==)
- [copy doc](https://docs.google.com/document/d/1RZXj-LH_7Eg-pWJR9tE_V3D5CSDzCzyhyn0WoHLZwpQ/edit)
- [demo link](https://canonical-com-1139.demos.haus/careers/application/gAAAAABlS9tm8wZ21ysWXa4qkfl6aCQrMe_EQSSRGoZSOmGBNs54u1_Gvo3ZYMTK45liyClBHpNOupkoFCoyVzLvP4UjZWllMg==)
- Check that the button and link on it are correct …

WD-7611 - add diversity button on application

---

templates/careers/project-management.html

Update subheading for project management role page
- [demo link](https://canonical-com-1142.demos.haus/careers/project-management)
- Check that the subheading is correct
[WD-5190](https://warthogs.atlassian.net/browse/WD-5190)
Fixes #
[WD-7312]: https://warthogs.atlassian.net/browse/WD-7312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WD-5190]: https://warthogs.atlassian.net/browse/WD-5190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-5190 - fix PM subheading

---

templates/blog/article.html
templates/blog/newsletter-form.html
templates/careers/application/_activate-email.html
templates/careers/job-detail.html
templates/contact-us.html
templates/data/_data-form.html
templates/data/_form-data-kafka.html
templates/data/_form-data-mongodb.html
templates/data/_form-data-opensearch.html
templates/data/_form-data-relational-dbs.html
templates/data/_form-data-spark.html
templates/microcloud/_microcloud-modal.html
templates/microcloud/contact-us.html
templates/partial/_footer.html
templates/partners/become-a-partner.html
templates/partners/partial/_executive-summit-form.html
templates/partners/partial/_homepage-form.html

Opening the privacy notice and privacy policy in a new tab in https://canonical-com-1136.demos.haus/careers
- [demo link](https://canonical-com-1136.demos.haus/)
- Check that the links to privacy notice and privacy policy open in a new tab
[WD-7312](https://warthogs.atlassian.net/browse/WD-7312)
Fixes #
[WD-7312]: https://warthogs.atlassian.net/browse/WD-7312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-7312 - open privacy policy in a new tab on careers

---

templates/data/index.html
templates/data/mysql.html
templates/partial/_data-navigation.html

- List MySQL right after PostgreSQL in the navigation
- On the [home](https://canonical.com/data), point “Learn more” links for PostgreSQL and MySQL to the new pages instead of documentation pages
- On the [MySQL page](https://canonical.com/data/mysql), add consistent spacing below the paragraph in the hero. I reused the code from PostgreSQL (uses the `row--25-75` layout). Also, added a missing line break ("Made to give you - peace of mind" and fixed a minor typo (should be "favourite" instead of "favorite")
Fixes …

WD-7949 - Tweak Data Fabric pages

---

templates/careers/application/index.html

Fixed navigation on candidates application page
- Visit the candidate's application page on `http://0.0.0.0:8002/careers/application/<application-id>` and test the navigation bar
Fixes #1024

Fix navigation by checking for .p-modal before toggling

---

templates/careers/job-detail.html
webapp/greenhouse.py

Fix the title of the careers description pages
Fix a typo in the comments
- Navigate to a career description
- See the title of the page now contains the title of the vacancy

Fix the title of careers pages

---

templates/partial/_standard-navigation.html
templates/partners/index.html
templates/partners/isv-partners.html
templates/partners/partial/_footer.html

- Updated ISV partners page as per [doc](https://docs.google.com/document/d/1qWWpFbwZykjAIt-Kf6iFCXPCnmmuKBbU5mzvILnO-q0/edit) and [mock-up](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?node-id=12110%3A16698&mode=dev)
- Added mention to ISV page on partners landing as per [doc](https://docs.google.com/document/d/1SwCceQv625Kdc3wAvzSFBBA3qt3CxzDmc0DAfo3LJfs/edit)
- Updated partners subnav and shared footer
- View the site locally in your web browser at: https://canonical-com-1154.demos.haus/partners
- See that the link to the [ISV partners page](https://canonical-com-1154.demos.haus/partners/isv-partners) exists, matches relevant doc, and routes correctly
- Check ISV partners page against doc and design
Fixes https://warthogs.atlassian.net/browse/WD-5266

ISV partners revamp

---

webapp/application.py

Updated the candidate withdrawal email template context variable `applicant_name` to be the full name.
- Create a job (or reopen a closed application) on the test position
- Run this branch locally and visit the application page
- Withdraw and see the email sent to the candidate
- See your full name including last name in the email

Display the full name in a candidate withdrawal email

---

templates/data/opensearch.html

Added a link to download PDF datasheet according to [copy doc](https://docs.google.com/document/d/1nVdoKoPrXw8lsvHEtMichlPNfxYU9Uj1zmKowcUXQ_w/edit).
- Navigate to /data/opensearch and click on `Download the datasheet`. Make sure PDF opens from the assets server.
Fixes https://warthogs.atlassian.net/browse/WD-6157

[WD-6157] add link to download datasheet to /data/opensearch

---

static/files/site.webmanifest
templates/base_index.html

- Updated links to favicon icons for different browsers and devices (iOS/Androd). Followed the instructions provided in https://favicon.io/favicon-converter/
- Used existing favicon images from Assets Manager
- Check favicon on different browsers
- Check favicon on mobile devices by adding a webpage to Home screen
Fixes https://warthogs.atlassian.net/browse/WD-8454

[WD-8454] update favicon for all browsers and devices

---

templates/careers/job-detail.html

Legal links enabled on career application forms
- [demo link](https://canonical-com-1171.demos.haus/careers/5143074/application)
- Check that the legal links are enabled and all other helper texts stay smaller and grey
[WD-8618](https://warthogs.atlassian.net/browse/WD-8618)
Fixes #
[WD-8618]: https://warthogs.atlassian.net/browse/WD-8618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-8618 - enable legal links on career forms

---

templates/base_index.html
templates/blog/article.html
templates/blog/index.html
templates/blog/newsletter-form.html

Update newsletter signup from according got the copy doc. Please check the form ob the /blog page and on individual articles
To test this PR on a demo I had to change the link to the success url. The link will be changed back to the prod link before merge. DO NOT merge before the link is changed back
- [demo link](https://canonical-com-1173.demos.haus//blog)
- [copy doc](https://docs.google.com/document/d/1CuQlCuH9d_uqGq0xGQ3cLkIdXVofPXgxgYF6UbMln-E/edit)
- Check that the form is according to copy doc
[WD-8434](https://warthogs.atlassian.net/browse/WD-8434) …

WD-8434 - update newsletter signup form on /blog

---

templates/data/mongodb.html

- Changed Snaps link in mongodb page from https://snapcraft.io/charmed-mysql to https://snapcraft.io/charmed-mongodb
Fixes #1172 

chore: change Snaps link in mongodb page

---

templates/documentation/open-documentation-academy.html

The published email address is currently wrong. It should be 	docsacademy@canonical.com.
Fixed Open Documentation Academy contact email address.
Fixes #

Fix email address in open-documentation-academy.html

---

templates/lxd/_form-lxd-install.html
templates/solutions/_form-big-data-ai.html

- Updated privacy links so that they route to u.com as expected 
- View the site locally in your web browser at: https://canonical-com-1182.demos.haus/solutions/big-data-ai#get-in-touch and https://canonical-com-1182.demos.haus/lxd/install#get-in-touch
- See that the privacy policy link at the bottom no longer throws 404
Fixes https://warthogs.atlassian.net/browse/WD-8870

Fix broken privacy link

---

templates/shared/forms/_country.html
templates/solutions/_form_infrastructure.html

Add missing asterisk to the Country field on /solutions/infrastructure
- [demo link](https://canonical-com-1195.demos.haus/solutions/infrastructure)
- [copy doc](https://docs.google.com/document/d/1dI16QM8pNusM-zmCtMQZSsmPvgQTUj6_ZrMQN00XOPQ/edit)
- Check that the asterisk appears near the field
[WD-9331](https://warthogs.atlassian.net/browse/WD-9331)
Fixes #
[WD-9331]: https://warthogs.atlassian.net/browse/WD-9331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9331 - add missing asterisk to Country field

---

templates/careers/company-culture/diversity.html

Remove a section from /diversity
- [demo link](https://canonical-com-1198.demos.haus/careers/company-culture/diversity)
- [copy doc](https://docs.google.com/document/d/1l1UGJToc0ErHUMN9W8hELvF5sDyVRO7N0xDzncqA2SQ/edit)
- Check that the section is not displayed
[WD-9422](https://warthogs.atlassian.net/browse/WD-9422)
Fixes #
[WD-9422]: https://warthogs.atlassian.net/browse/WD-9422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9422 - remove section from /diversity

---

templates/documentation/open-documentation-academy.html

Add Join the academy buttons to /documentation/open-documentation-academy
- [demo link](https://canonical-com-1199.demos.haus/documentation/open-documentation-academy)
- [copy doc](https://docs.google.com/document/d/1nhy653-SOfTmGCIiSZHuGBCrwZlzEZJaA4kFBsw-5dc/edit)
- [figma](https://www.figma.com/file/599RqqmJN6hQwKMa5DJZDl/Canonical.com%2Fdocumentation?type=design&node-id=0-1&mode=design&t=aeqPaaspxkwSsN5o-0)
- Check that the buttons are correctly added
[WD-9253](https://warthogs.atlassian.net/browse/WD-9253)
Fixes #
[WD-9253]: …

WD-9253 - add buttons to /documentation

---

templates/data/mongodb.html

Added links to datasheets according to the [copy doc](https://docs.google.com/document/d/1mCztOFZYbC3TeUM7j7pGfSoxKzBs20W1pJHZhdLqKs8/edit#heading=h.1jrvb0hvej6k).
- Navigate to https://canonical-com-1202.demos.haus/data/mongodb
- Check if new links work (in the copy doc the stakeholder already applied the changes, so please check those that are highlighted in the screenshots below)
- Check the links that were replaced
Fixes https://warthogs.atlassian.net/browse/WD-9557

[WD-9557] add links to datasheets in /data/mongodb

---

.env
.github/workflows/pr.yaml
Dockerfile
konf/site.yaml
requirements.txt
templates/careers/application/_withdrawal-feedback-not-needed-email.html
templates/careers/application/_withdrawal-interview-canceled-email.html
templates/careers/application/_withdrawal_notification-email.html
templates/careers/application/withdrawal.html
tests/test_application.py
tests/test_google_calendar.py
tests/test_routes.py
webapp/application.py
webapp/google_calendar.py

- Added Google Calendar API class
- Class taken from the [interview scheduler repo](https://github.com/canonical/interview-scheduler/blob/main/scheduler/google_calendar.py)
- Added a `delete_event_from_interview_calendar()` function which as you might guess deletes an interview from the interview calendar (the interview calendar is the shared calendar on which all interviews are scheduled)
- Also added `sendUpdates="all"` to the delete request itself. This ensures a notification is sent to all attendees of the meeting telling them that it was canceled. The old parameter for this was `sendNotifications` (a boolean), but that has since been deprecated.
- Updated the email sent to the hiring lead when a candidate withdraws. Before, it explicitly told them to look for any pending interviews …

auto delete interviews on withdrawal (WD-7721)

---

static/js/forms.js
templates/base_index.html

- Copies the code from [u.com](https://github.com/canonical/ubuntu.com/blob/main/static/js/src/static-forms.js#L150) to the [vanilla loading spinner](https://vanillaframework.io/docs/patterns/buttons#processing) on successful form submission
- fill in a [modal form](https://canonical-com-1207.demos.haus/#get-in-touch) check that the spinner is attached on form submission
- do the same for a [static form](https://canonical-com-1207.demos.haus/partners/become-a-partner)
Fixes https://warthogs.atlassian.net/browse/WD-8603

Add logic for loading-spinner on forms

---

static/sass/styles.scss
templates/data/kafka.html
templates/data/mongodb.html
templates/data/mysql.html
templates/data/opensearch.html
templates/data/postgresql.html
templates/data/spark.html

- update top sections into 50-50 split format, make kafka and other logos bigger and in boxes (Request from Rob Gibbon)
- update sections immediately after so it works better when sandwitched between 50-50 splits
Fixes #

update data fabric pages with bigger logos

---

konf/site.yaml

- Added `SERVICE_ACCOUNT_EMAIL` and `SERVICE_ACCOUNT_PRIVATE_KEY` env variables to the `/blog` route in `site.yaml`, for both production and staging, as this was stopping deployments from succeeding.

Add Google Calendar env keys for canonical-com-blog

---

.djlintrc
.github/workflows/pr.yaml
package.json
requirements.txt
templates/solutions/telco/index.html

- Added djLint fotmatter/linter support
- Defined a configuration file `.djlintrc` for it
- Added a yarn script `lint-jinja` that checks linting in Jinja templates that were changed
- Added GH CI job for running `lint-jinja` script
- Set up djLint in your codebase as described in Discourse topic here: https://discourse.canonical.com/t/configuring-editors-for-formatting-and-linting/188
- Open any Jinja template and format it
- Save the formatted file
- Run `yarn lint-jinja` script in the terminal and check that it has checked one changed file and that the check has passed
- Change another Jinja template and save it without formatting it
- Run `yarn lint-jinja` and check that the file is reported as having a linting error
- Open the file and check where djLint is reporting errors by …

Add djLint formatter/linter for Jinja templates

---

static/js/applications/get-report.js

- Renamed the `form` and `submitButton` identifiers in `get-report.js` because they were clashing with identifiers inside a newly added script from last week.
- Renamed them to `requestAssessmentForm` and `requestAssessmentSubmitButton` to constrain the names to the use case and hopefully avoid such clashes in future.
- View the site locally in your web browser at: http://localhost:8002/
- Navigate to [Professor Dumbledore's candidate page](http://localhost:8002/careers/application/gAAAAABjttUfUHinT891Vx0MEX9ae5PHq3zYdigM-bH4Q_iW0jSeI9zMFf5qRh_oNSWneVktbzr2wzMyeaW3iEnYPFcVFkXkxw==)
- Attempt to download Dumbledore's reports and see if the process works now.

Fix Candidate Reports Download Issue (WD-9878)

---

templates/index.html

- Update link on homepage based on [copydoc](https://docs.google.com/document/d/1GNa1FaTkARdrVwYgHXf5H-6sqOLjkJENDistDDcsi4o/edit)
- Go to https://canonical-com-1229.demos.haus/
- Click the 'AI/ML Ops' link
- See that it redirects to https://canonical-com-1229.demos.haus/solutions/ai  
Fixes https://warthogs.atlassian.net/browse/WD-9989

Update AI/ML-ops link on index to point toward internal page

---

package.json
yarn.lock

- Updated the cookie policy to include google consent mode
- Open the demo and inspect the source _before_ accepting the preferences
- The top of `<head>` section should have a `google-consent-mode` script
- Accept one of the cookie preference options
- The bottom of `<head>` section should have a `google-consent-preferences` script

Updated cookie policy to v3.6.0

---

.djlintrc

Added configuration that defines indentation for HTML files when formatting using djLint.
The formatting should now use 2 spaces as an indentation instead of 4 by default.

add configuration for indentation in djLint conf file

---

templates/partial/_standard-navigation.html
templates/partners/channel-and-reseller.html
templates/partners/index.html
templates/partners/partial/_co-sell-with-canonical.html

- Updated link as per docs: [1](https://docs.google.com/document/d/12tpcvTBOjwCGzqrGMFC0ucYCGATJJn8Tbl2SHUcgf6k/edit), [2](https://docs.google.com/document/d/1q6dkqQ0zcshrfOmdJA_bAip73EaMSEyXAn8bAD7GqNw/edit)
- Ran djlint
- View the site locally in your web browser at: 
- https://canonical-com-1243.demos.haus/partners
- https://canonical-com-1243.demos.haus/partners/channel-and-reseller
- See that the link has been updated in the above pages as well as on the partners nav
Fixes https://warthogs.atlassian.net/browse/WD-10539

Update partner portal link across the site

---

templates/careers/application/partial/_assessment.html

https://github.com/canonical/canonical.com/pull/1245/commits/b495016b51a756083101ecd57748d602eaea03ee
Candidate page shows notification about received written interview (main requirement)
https://github.com/canonical/canonical.com/pull/1245/commits/c6c24299b50234c5aaeef13f98cc5d27b49dc5a6
Fixed djlint errors. Before there was a div opened inside if block and closed outside of it. djlint didn't like that.
https://github.com/canonical/canonical.com/pull/1245/commits/fef0c3af57bcd2f54abae694723c4d28a622c641
djlint --reformat
https://github.com/canonical/canonical.com/pull/1245/commits/6db00c00a55e8fd6eaa1a08659210b238e575980
keep css class names inplace
- View the site locally in your web browser at: …

candidate page notification about received written interview

---

static/sass/_pattern_application.scss

- Fix wrong ordered list numbers on the application page
- Center the numbers in the hiring stages list
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/application/[token]
- Or you can mock an application locally by updating the function `application_index` in `webapp/application.py`:
```py
@application.route("/<string:token>")
def application_index(token):
withdrawn = False
application = { "status": "active", "candidate": { "first_name": "John", "last_name": "Doe" }, "stage_progress": { "application": True, "assessment": True, "early_stage": True, "late_stage": False, "offer": False }, "scheduled_interviews": [], "to_be_rejected": False, "role_name": "Software Engineer", "source": …
```

Fix application page ordered list

---

templates/partial/_microcloud-navigation.html

Remove navigation item according to https://warthogs.atlassian.net/browse/WD-10737
- Go to https://canonical-com-1253.demos.haus/microcloud and check that navigation item "Roadshow" is removed.
Fixes https://warthogs.atlassian.net/browse/WD-10737

Remove roadmap navigation link

---

templates/401.html
templates/404.html
templates/500.html
templates/502.html
templates/partial/_footer.html

- Modified new issue urls from https://github.com/canonical/canonical.com/issues/new to https://github.com/canonical/canonical.com/issues/new?template=ISSUE_TEMPLATE.md which uses a default template.
Fixes #1227

chore: modify new issues url to use a different url with a default template

---

static/sass/styles.scss
templates/index.html

- This fixes a bug we were having on the c.com home page wherein some tabs were not scroll-able.
**Note that on the Ubuntu desktop, the mobile view on dev tools doesn't work. I test on android and it does work**
- Go to and scroll down to the section 'Trusted in every industry'
- Adjust the screen size so that the tabs don't fit in the page
- Check they are scrollable
Fixes https://warthogs.atlassian.net/browse/WD-11287

Fix tabs on homepage not being scrollable

---

static/sass/styles.scss
templates/index.html

- Remove `is-dark` from hr tags
- Add `is-dark` to parent HTML
- Links and HR inherit dark theme colours
- Go to landing page on demo
- Check that links and HR are inhering dark theme colours
Fixes [WD-11489](https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932?selectedIssue=WD-11489)
[WD-11489]: https://warthogs.atlassian.net/browse/WD-11489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Inherit dark colours on homepage

---

templates/index.html

- Add `is-muted` to `hr`s inside top level section, from design comment: https://github.com/canonical/canonical.com/pull/1258#issuecomment-2129355465
- Go to demo landing page
- Check that `hr`s inside top level sections are muted
Fixes #

Add is-muted to hr

---

tests/cassettes/TestApplicationPageHelpers.test_job_post_page.yaml
tests/test_application.py
webapp/app.py

Append back the original content with Requisition ID, as requested.
Originally this was changed to [show active/inactive roles](https://github.com/canonical/canonical.com/pull/1100), but looks like there is no way to get the Requisition ID with only the Harvest Job board API, so had to put back the old greenhouse API.
Also, since it looks like role description looks the same, so I directly assigned the old `job["content"]`.
- Go to https://canonical-com-1260.demos.haus/careers/4754075 and check that "Requisition ID" shows up now, at the end of the page (before the application button).
- Anything else you may think could be breaking with this change.
Fixes https://warthogs.atlassian.net/browse/WD-8203

Fix missing requisition ID

---

requirements.txt

- Bump canonicalwebteam.discourse to 5.5.0
- Go to https://canonical-com-1275.demos.haus/data/docs/postgresql/k8s
- Use chrome dev tools to see that the anchor link in heading don't have trailing numbers

chore: Bump canonicalwebteam.discourse to 5.5.0

---

templates/careers/company-culture/diversity.html
templates/careers/company-culture/identity.html
templates/careers/company-culture/index.html
templates/careers/company-culture/progression.html

- Removed "/" from names of templates in extended clause
- Check if all the changed pages are working properly and resembles the original site
- Links to Demo Pages
-  [Divesrity Page in Careers](https://canonical-com-1282.demos.haus/careers/company-culture/diversity)
-  [Identity Page in Careers](https://canonical-com-1282.demos.haus/careers/company-culture/identity)
- [Company Culture Careers](https://canonical-com-1282.demos.haus/careers/company-culture)
- [Progression Page in Careers](https://canonical-com-1282.demos.haus/careers/company-culture/progressi …

Fixed Naming for templates

---

templates/projects/index.html

- Fixes the Jaas link on /projects
- Go to https://canonical-com-1283.demos.haus/projects
- Click the link for Jaas and see that it takes you to jaas.ai

bug: Fix broken link to jaas.ai on '/projects'

---

secondary-navigation.yaml

- Build secondary-navigation.yaml
- There is no copydoc (as far as I know) so this was built using the previously existing secondary navigations
[microcloud](https://github.com/canonical/canonical.com/blob/main/templates/partial/_microcloud-navigation.html)
[data](https://github.com/canonical/canonical.com/blob/main/templates/partial/_data-navigation.html)
[lxd](https://github.com/canonical/canonical.com/blob/main/templates/partial/_lxd-navigation.html)
- Open the [secondary-navigation.yaml](https://github.com/canonical/canonical.com/pull/1289/files#diff-99fde9a38b5f2b5f5c54ee70c9d160a0f7771bd55895ba02ade9863dc01bce08) and check it contains the same navigaiton data as listed above. It following the same pattern and will use the same logic as found on u.com: …

feat: Build secondary-navigation.yaml for dynamically building the secondary nav items

---

package.json
static/js/navigation.js
static/sass/styles.scss
templates/navigation/navigation.html
templates/search.html
webapp/app.py
yarn.lock

- Adds new route for '/search'
- Build search results page (copied from u.com)
- Updates the vanilla dependency reference
- Small change to the event delegation function to get the navigation search to submit properly
- Go to https://canonical-com-1296.demos.haus/ open the navigation search
- Make a search using the 'enter'
- Make a search clicking the search icon in the bar
- Check clicking the 'X' clears the input
- Check the search results page matches u.com
- Check the next and previous buttons at the bottom of the page work
- Check it works on desktop, mobile and with the reduced nav ie. https://canonical-com-1296.demos.haus/data
Fixes https://warthogs.atlassian.net/browse/WD-12996

Implement search

---

templates/solutions/secure-open-source/index.html

- Removed duplicate text in the /solutions/secure-open-source page (Public cloud section)
- See the demo [here](https://canonical-com-1303.demos.haus/solutions/secure-open-source).
- Please find [copydoc](https://docs.google.com/document/d/1mrvhkrVjCCJE39h96CPG_b_ZHWVN0GHzZ_6TdoudeYs/edit#heading=h.oy44zuppmsv2) here.
Fixes # [WD-13399](https://warthogs.atlassian.net/browse/WD-13399)
Previously
New
[WD-13399]: https://warthogs.atlassian.net/browse/WD-13399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-13399 Removed Duplicate Text

---

static/sass/_pattern_careers-progression.scss
static/sass/styles.scss

- Remove custom stylings for right chevron
- Use new Vanilla icons (left and right chevron) for careers progression carousel controls
- Go to /careers/company-culture/progression
- Scroll to image carousel section, check that the left and right chevrons look the same as the chevrons on [live](https://www.canonical.com/careers/company-culture/progression)
Fixes #1269 and [WD-11919](https://warthogs.atlassian.net/browse/WD-11919)
[WD-11919]: https://warthogs.atlassian.net/browse/WD-11919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove chevron custom stylings

---

templates/microcloud/index.html
templates/partial/_microcloud-navigation.html

The default link is now the stable documentation, not the latest.
Fixes #

update link to MicroCloud documentation

---

navigation.yaml
static/js/navigation/careers/Worker_populate-careers.js
static/js/navigation/careers/populate-careers-roles.js
static/js/navigation/fetch-careers-roles.js
static/js/navigation/main.js
static/sass/_pattern_navigation.scss
static/sass/styles.scss
templates/navigation/_dropdown.html
templates/navigation/partials/_list-item.html

to be merged to https://github.com/canonical/canonical.com/pull/1322 or if that has already been merged, to `canonical-navigation`
- Implements a web worker and associated script (`fetch-careers-roles.js`) to fetch career data in the background on page load (this is because it was quite delayed when fetching on dropdown opening)
- Adds 'slug' value to 'careers' in navigation.yaml to associate with the careers data
- some minor html and scss changes
- Open 'careers' navigation, see that each job role has an associated number of roles. eg. 'Engineering', '20 roles'. You can compare to the live page https://canonical.com/
- Check both mobile and desktop
Fixes https://warthogs.atlassian.net/browse/WD-13581

Implement logic to fetch and auto fill career roles

---

templates/partners/partial/_partner-filters/_programme-filters.html

-  Added "Distributor" to programme filter of partners
- [Demo](https://canonical-com-1331.demos.haus/partners/find-a-partner)
- [Copydoc](https://docs.google.com/document/d/1R3s-aiSrFvbNrHjdfblYo_XX1f_EQ989DkmPS41seZc/edit)
- Partners need to have "distributor" in "data-filter" attribute to get filtered.
Fixes # [WD-13887](https://warthogs.atlassian.net/browse/WD-13887)
[WD-13887]: https://warthogs.atlassian.net/browse/WD-13887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-13887 Add "Distributor" to programme filter of partners

---

static/js/navigation/ga-tracking.js
static/js/navigation/main.js
templates/navigation/navigation.html

- Implement GA tracking for the meganav. This means copying what exists already on c.com, [see here](https://github.com/canonical/canonical.com/blob/main/static/js/navigation.js#L96)
- Open [the demo](https://canonical-com-1342.demos.haus/)
- Check that the GA event are being attached to the appropriate dropdowns, you can inspect this in the network tab and logging in the JS.
- If you want to you can install  Chrome extension 'Google Tag Assistant' and actually look at the tags being fired. But given this is an exact copy of what we currently have, isn't necessary. 
Fixes https://warthogs.atlassian.net/browse/WD-12082

Implement GA tracking for the meganav

---

static/js/navigation/main.js
static/js/utils/throttle.js

- Adds logic to only close the navigation when resizing horizontally. For context: Vanilla added this the feature to close when resizing as there was still some issue going fluidly from mobile to desktop. This was causing a bug on mobile when you scrolled down and the search hid itself.
- Open [the demo](https://canonical-com-1344.demos.haus/) on a mobile device with chrome
- Open then navigation and going to a section which is scroll-able (Products > Private cloud, for ex.)
- Start to scroll down to reveal the rest of the navigation and causing the search bar to hide itself.
- See that the navigation stays open.
- Check that the navigation closes on horizontal resize on desktop.
Fixes https://warthogs.atlassian.net/browse/WD-14167

feat: Only close the navigation when resizing horizontally

---

templates/index.html

- Update dates the suru on the home page to fix a issue where the colours did not match
- Check out [the demo](https://canonical-com-1347.demos.haus/) on firefox
- see that the suru background matches the page background
Fixes https://warthogs.atlassian.net/browse/WD-9552?focusedCommentId=554655
https://github.com/canonical/canonical.com/issues/1201

bug: Replace homepage suru that was incompatible with firefox

---

templates/careers/application/faq.html

- Updated copy on the careers FAQ page (`/careers/application/faq`) according to the [updated copy doc](https://docs.google.com/document/d/12_O_QtPqfv9p7kaDFdiP8Xq-kY5xa1XB-C-CRbXjDew/edit)
- Navigate to FAQ page `http://localhost:8002/careers/application/faq`
- Ensure that copy matches that of the updated copy doc
[WD-14594](https://warthogs.atlassian.net/browse/WD-14594)
[WD-14594]: https://warthogs.atlassian.net/browse/WD-14594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update copy on careers FAQ page

---

templates/careers/application/faq.html

- As per TS request, updated the number "four" to be a digit instead.
- Navigate to FAQ page http://localhost:8002/careers/application/faq
- Ensure that four is displayed as a digit for the "When can I apply again?" question.

update "four" to "4" in faq copy

---

templates/careers/job-detail.html

An issue came through the TS ticketing system and was passed to us, where this application has an input field missing for the Ceph question.
Turned out that this Ceph question has a question type of `multi_select`, while on the frontend for canonical.com we only check for the multi select type of `multi_value_multi_select`, hence the problem.
- Add check for `multi_select` question type
- Navigate to http://localhost:8002/careers/1861978/application and ensure that the field shows up correctly for the "Describe your experience with Ceph" question.
[WD-14817](https://warthogs.atlassian.net/browse/WD-14817)
Before fix:
After fix:
[WD-14817]: …

Fix application question field

---

templates/data/_form-data-kafka.html
templates/data/_form-data-mongodb.html

- Add "is-required" class to required fields for /data/mongodb#get-in-touch and /data/kafka#get-in-touch contact forms
- The Jira issue reports a "Not Provided" payload for the required fields, this could not be replicated locally so this PR should explicitly tell users to fill up the forms with the required labels
- Go to /data/mongodb#get-in-touch and /data/kafka#get-in-touch
- See that the contact fields have required `*` on the labels
Fixes [WD-14682](https://warthogs.atlassian.net/browse/WD-14682)
[WD-14682]: https://warthogs.atlassian.net/browse/WD-14682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add is-required label to required fields

---

templates/solutions/ubuntu-os/index.html

Added assets to the "Everywhere for everyone" section as per figma
- [demo link](https://canonical-com-1372.demos.haus/solutions/ubuntu-os)
- [figma](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/24.10-Canonical.com%2Fsolutions?node-id=510-4340&node-type=frame&t=rBIwmAK7DpxxFpdm-0)
- Check that the page is correct according to figma
[WD-14408](https://warthogs.atlassian.net/browse/WD-14408)
[WD-14408]: https://warthogs.atlassian.net/browse/WD-14408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-14408 - add assets on /solutions/ubuntu-os

---

requirements.txt
webapp/app.py

- Upgrade canonicalwebteam.search to 2.1.1
- Upgrade canonicalwebteam.flask-base to 2.0.0
- Pass `app` to `build_search_view()`
- Go to https://canonical-com-1374.demos.haus/
- Search something
- See rate limit is hit (currently set to 1, so you can search 1 time before hitting it)
Fixes https://warthogs.atlassian.net/browse/WD-15011

chore: Upgrade canonicalwebteam.search to 2.1.1

---

secondary-navigation.yaml

- Secondary navigation for pages inside 
- /data/opensearch 
- /data/postgresql
- /data/opensearch
- [Design](https://www.figma.com/design/p0y7lHJ7edLIeSXM1qbpRZ/23.10-C.com-%26-U.com---Navigation?node-id=201-1141&node-type=canvas&t=wtOPAA7pKwQPInkA-0)
- [Copydoc](https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit#heading=h.wgubbpfalsgo)
- [Demo](https://canonical-com-1378.demos.haus/data/)
Fixes # [WD-15180](https://warthogs.atlassian.net/browse/WD-15180)
[WD-15180]: …

WD-15180 Added secondary navigation for /data/* pages

---

templates/solutions/secure-open-source/index.html

Removes incorrect usage of `p-rule--muted` on the secure open source page. Looks like an `is-muted` (that was doing nothing without `p-rule`) was [changed to a p-rule--muted](https://github.com/canonical/canonical.com/commit/bc874d6a1d66d1d50d2fe48730ec83890aa8f52a#diff-a7ad1fda3162b6860337dc853c6f5d422ca84ebbaab360bb4a25b7dcf070ce8e), which caused a section to behave like a rule and threw off spacing.
- Navigate to [secure open source page](https://canonical-com-1387.demos.haus/solutions/secure-open-source)
- See "data centres" list item and confirm it has no spacing issues, like it does on [production currently](https://canonical.com/solutions/secure-open-source)
Fixes [MM message](https://chat.canonical.com/canonical/pl/85ph1dz6zfdciquqm4idssy7rc)
Before:
After:

fix: incorrect usage of p-rule on secure open source page

---

templates/macros/quote_wrapper.jinja
templates/solutions/telco/_form-telco-5g.html

- Update form ID for dynamic telco 5g forms
- Copy over updated quote macros from Vanilla to fix extra bottom padding issue
- Go to https://canonical-com-1391.demos.haus/solutions/telco/5g-core#get-in-touch and https://canonical-com-1391.demos.haus/solutions/telco/5g-edge#get-in-touch
- Click on Contact Us CTA and check that form ID is 5716, matching the [copy doc](https://docs.google.com/document/d/1mi6NOW_GiCMZ1O4xRCxS2RPhZMjEaOdipD5LFnCvMz4/edit) for forms
- Go to https://canonical-com-1391.demos.haus/solutions/telco/5g-edge
- Scroll down to the quote section, see that there is only one bottom padding for the quote section
Fixes #

Update form id for telco-5g and quote macro

---

secondary-navigation.yaml
templates/navigation/secondary-navigation.html
webapp/navigation.py

- Add `parent` attribute to secondary navigation
- Includes parent link and title
- Shows the parent title & link on secondary navigation 
- Add parent navigation path to data bubbles (/data/mongodb, /data/postgresql, /data/opensearch)
- Go to https://canonical-com-1390.demos.haus/data/mongodb, https://canonical-com-1390.demos.haus/data/postgresql, https://canonical-com-1390.demos.haus/data/opensearch
- [Figma](https://www.figma.com/design/p0y7lHJ7edLIeSXM1qbpRZ/23.10-C.com-%26-U.com---Navigation?node-id=751-3021&node-type=canvas&t=1QDhRKdqjli5aiQn-0)
- Check on small screens
Fixes [WD-15568](https://warthogs.atlassian.net/browse/WD-15568)
[WD-15568]: https://warthogs.atlassian.net/browse/WD-15568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

Add parent path to secondary navigation

---

secondary-navigation.yaml
webapp/app.py

Updated secondary navigation of MongoDB and OpenSearch in data bubble.
Copy doc: https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit?tab=t.0#heading=h.ib9c04garte2
Drive-by: some recent form updates started to cause secondary nav to dissapear on several pages. This was commented out here as a drive-by and reported separately in https://github.com/canonical/canonical.com/issues/1399
- Go to MongoDB page: https://canonical-com-1398.demos.haus/data/mongodb
- make sure secondary navigation items are in order requested by the …

Update data bubble navigation

---

templates/data/postgresql/support.html

Updates title of `data/postgresql/support` page per [copy doc update](https://docs.google.com/document/d/1scPktUiI2XRVoYcR4L6qUZ91iZ0upZA-FaqyJN7uMJg/edit?disco=AAABT_iI3g4)
- Go to [PostgreSQL support page](https://canonical-com-1412.demos.haus/data/postgresql/support). Verify the page title has been updated to match the copy doc.
Fixes [copy doc update](https://docs.google.com/document/d/1scPktUiI2XRVoYcR4L6qUZ91iZ0upZA-FaqyJN7uMJg/edit?disco=AAABT_iI3g4)

Update data/postgresql/support title

---

static/sass/styles.scss
templates/careers/_base-department.html
templates/careers/company-culture/index.html

- Fixed gap between highlighted and base separators  
- Fixed blog section separators for department pages
- View the site locally in your web browser at: https://canonical-com-1413.demos.haus/careers/company-culture
- See that there is no gap between separators in the "We're hiring" section
- View the site locally in your web browser at: https://canonical-com-1413.demos.haus/careers/engineering (or any department page)
- Scroll down to the blog section and see that the separators have been fixed 
Fixes https://github.com/canonical/canonical.com/issues/1397, https://warthogs.atlassian.net/browse/WD-15954
Before:
After:

bug: Fix seperators and remove stale custom styles

---

package.json
secondary-navigation.yaml
templates/data/sitemap.xml
templates/data/spark/what-is-spark.html
yarn.lock

- Built page as per [doc](https://docs.google.com/document/d/1pyX-BOXmIZY6_8imIft1SAp1-S0i8bGYWEo5zoVEgQw/edit?tab=t.0) and [design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=1498-8200&node-type=canvas&m=dev)
- Drive by:
- Bumped Vanilla and Sass versions (sass bump needed for vanilla) 
- View the site locally in your web browser at: https://canonical-com-1409.demos.haus/data/spark/what-is-spark
- Check against doc and design 
- I qa'd the Vanilla bump and didn't notice anything broken, but please also have a look just in case
Fixes https://warthogs.atlassian.net/browse/WD-15058

feat: /data/spark/what-is-spark build

---

secondary-navigation.yaml

- Fixed missing /data/spark subnav
- View the site locally in your web browser at: https://canonical-com-1420.demos.haus/data/spark
- See that the subnav appears as expected
Fixes #

bug: Fix missing subnav

---

webapp/app.py
webapp/google_calendar.py
webapp/greenhouse.py
webapp/partners.py

Specify timeouts on all http requests. 15s for get requests, 30s for post requests. It is a good practice to always set timeouts on network operations. In case a request hangs it might cause a connections/ram leak. It might also cause stale cache pages if cache validation request happens to hang.
- Check everything works as before. (careers pages, blog pages, partners pages)

specify timeouts on all http requests

---

templates/data/valkey.html

Refreshed the /data/valkey page
- Go to https://canonical-com-1432.demos.haus/data/valkey
- Compare to [the design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=1340-1155&node-type=frame)
- Compare to [the copy doc](https://docs.google.com/document/d/1zu_5LIjlcTwyJzJfX3jveX2HfMO8XxkXg5A7E5ZjE6g/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-16792

chore: Refresh valkey page

---

static/sass/_pattern_application.scss

A candidate pointed out that the number of steps on their candidate page is always set to zero. Looking into this, the main step numbers in the stepped list component displaying application stages were missing the proper counter increment. Adding this caused the nested list numbers to display as zero as well, so I needed to add a separate counter for them as well.
- Added counter increment for main stepped list
- Added separate counter for nested lists
- Run the site with `dotrun`
- Navigate to test candidate (Bruno Fernandes) dashboard and verify that the main stepped list numbers are no longer showing up as zero
[WD-16959](https://warthogs.atlassian.net/browse/WD-16959)
---
[WD-16959]: …

fix: candidate dashboard step counter

---

secondary-navigation.yaml
templates/multipass/index.html

- Rebranded multipass landing page
- Migrate from multipass.run to c.com/multipass
- Create secondary navigation for multipass bubble
- Reordered secondary-navigation.yaml by alphabetical order
- Go to https://canonical-com-1437.demos.haus/multipass
- Check against design file and copy doc
- [Design](https://www.figma.com/design/LGm1MP262JtWfrCxQ3MvqQ/Multipass-Bubble?node-id=1-10105&node-type=instance&m=dev) and [copy docs](https://docs.google.com/document/d/1uI5hsuhe5VUpFSSiQas6FVB2F7RhlbNXcr5Pvr_Lm2c/edit?tab=t.0)
- See that secondary navigation matches https://multipass.run/
- Click on Discourse and see that it links to the discourse forum for multipass
- The other links on the secondary nav are not live yet so will return 404
Fixes …

Rebrand /multipass landing page

---

navigation.yaml
secondary-navigation.yaml
static/sass/styles.scss
templates/openstack/_form-openstack.html
templates/openstack/architecture.html
templates/openstack/index.html

- New pages:
- https://canonical-com-1393.demos.haus/openstack
- https://canonical-com-1393.demos.haus/openstack/architecture
- Meganav in Products -> OpenStack now takes user to the new /openstack page
- There is now a sub-navigation for the new OpenStack bubble that consists of a link to the new /openstack/architecture page

Feature openstack

---

templates/openstack/index.html

- The link that leads to a copy doc was not correct for /openstack page, so fixed that
- Added a link to open a contact form modal
- open the page
- Make sure you have "Ubuntu Copy Docs" extension installed in your browser
- click on "copy document" link below the screen
- check that the copy document belongs to /openstack webpage
- Click on "Start with Canonical" button at the very bottom of the page and check that it opens a modal with contact form

fix the link to copy doc for /openstack

---

templates/multipass/docs/document.html
templates/multipass/docs/search-results.html
webapp/app.py

Need to add new doc site to Google Custom Search Engine (https://github.com/canonical/canonicalwebteam.search?tab=readme-ov-file#new-sites)
- Migrate multipass.run/docs to c.com/multipass/docs
- Including Multipass docs and search
- Go to https://canonical-com-1440.demos.haus/multipass/docs
- Check that Multipass docs content load as expected
- Use the docs search bar
- See that it returns search results as expected
Fixes [WD-16619](https://warthogs.atlassian.net/browse/WD-16619)
[WD-16619]: https://warthogs.atlassian.net/browse/WD-16619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Migrate multipass docs pages

---

templates/partners/executive-summit.html

- Updated copy as per [doc](https://docs.google.com/document/d/15C3k-htvapwp-WTrYQ2SdHBW20Lp9IinpY9mkvo6q3U/edit?tab=t.0)
- View the site locally in your web browser at: https://canonical-com-1454.demos.haus/partners/executive-summit
- Check against doc
https://warthogs.atlassian.net/browse/WD-17573

/partners/executive-summit copy updates

---

templates/openstack/index.html

- Updated BE spelling to AE spelling.
- Applied all the copy updates requested recently (from November 29th onward) in the [copy doc](https://docs.google.com/document/d/1v1G2y465b_VYVUG9TIV-A_X1dU4kg5Zvrwd2latidCk/edit?tab=t.0).
- Added and replaced logos in the "Proven record of success" section ~~- this probably needs design input, as it doesn't look particularly good after the changes~~.
- Open https://canonical-com-1448.demos.haus/openstack
- Check that all the recent suggestions in the copy doc linked above have been addressed
Fixes [WD-17510](https://warthogs.atlassian.net/browse/WD-17510)
[WD-17510]: https://warthogs.atlassian.net/browse/WD-17510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(openstack): copy updates (including BE -> AE spelling), logos [WD-17510]

---

templates/solutions/open-source-security/index.html

Adds new testimonial based on copy doc.
Fixes WD-17399 
Copy doc: https://docs.google.com/document/d/1mrvhkrVjCCJE39h96CPG_b_ZHWVN0GHzZ_6TdoudeYs/edit?tab=t.0
- Check the demo: https://canonical-com-1449.demos.haus/solutions/open-source-security
- Scroll down to "What customers say" section and review the last testimonial against the [copy doc](https://docs.google.com/document/d/1mrvhkrVjCCJE39h96CPG_b_ZHWVN0GHzZ_6TdoudeYs/edit?tab=t.0)

Add a testimonial to open source security page

---

navigation.yaml

Replaced heavy images in navigation to their lighter version to reduce the load time of the home page. 
- Open the Network tab in dev console and select All or Img to see images
- Open the home page
- Sort by Size and check how big the loaded images are
- The biggest one slightly exceeds 500 kB, while as before it was over 900 kB.
Fixes https://warthogs.atlassian.net/browse/WD-17291

[WD-17291] replace heavy images in navigation with lighter versions

---

static/files/latest-multipass-releases.json

1. Update Multipass release to 1.15.0
2. Revert download link to canonical.com

Update latest Multipass release

---

templates/index.html

- Remove `12 year LTS for open source docker images` notification banner
- Update **OpenStack** link to `canonical.com`
- Go to https://canonical-com-1463.demos.haus
- Compare page against [copy doc](https://docs.google.com/document/d/1GNa1FaTkARdrVwYgHXf5H-6sqOLjkJENDistDDcsi4o/edit?tab=t.0)
Fixes [WD-17699](https://warthogs.atlassian.net/browse/WD-17699)
[WD-17699]: https://warthogs.atlassian.net/browse/WD-17699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-17699] Copy update on homepage

---

package.json
scripts/build-modules.sh
templates/docs/shared/_docs.html
yarn.lock

- Adds [discourse-rad-parser](https://www.npmjs.com/package/@canonical/discourse-rad-parser) as a dependency
- Include it in the `_docs.html` template
- Go to https://canonical-com-1466.demos.haus/multipass/docs/tutorial
- See there is a dropdown to select operating system
- Check that selecting a different OS changes the content
Fixes https://warthogs.atlassian.net/browse/WD-17714

feat: Install and implement discourse-rad-parser in _docs.html template

---

secondary-navigation.yaml

- Changed Docs link in /lxd page to direct to stable version instead of latest version
- Go to /lxd or https://canonical-com-1468.demos.haus/lxd
- Compare page against [copy doc](https://docs.google.com/document/d/1LJ6ajHYAmKdxSNDaD5kbriDod1t7RcmIwVJtevAeKFQ/edit?tab=t.0). Consists of "Docs" link change
Fixes https://warthogs.atlassian.net/browse/WD-17850

WD-17850 Copy update on the Docs link at /lxd page

---

templates/openstack/architecture.html

- Replace image used for 'Openstack under the hood' to match the [copydoc](https://docs.google.com/document/d/1i8rjvhw3N2gDA5NXuKEPcftXY95zePjsURmQu4dSgGo/edit?tab=t.0#heading=h.8bq4er39iavh)
- Go to https://canonical-com-1469.demos.haus/openstack/architecture
- Check the image used in the section 'Openstack under the hood' matches that in the [copydoc](https://docs.google.com/document/d/1i8rjvhw3N2gDA5NXuKEPcftXY95zePjsURmQu4dSgGo/edit?tab=t.0#heading=h.8bq4er39iavh)
Fixes https://warthogs.atlassian.net/browse/WD-17511

chore(/openstack/architecture): Replace image used for 'Openstack under the hood'

---

templates/docs/shared/_docs.html

- Add toc to doc pages
- Go to a doc page e.g https://canonical-com-1471.demos.haus/data/docs/postgresql/iaas/h-integrate
- Check that h2 and h3 headings are added to TOC on the right
Fixes [WD-17307](https://warthogs.atlassian.net/browse/WD-17307)
[WD-17307]: https://warthogs.atlassian.net/browse/WD-17307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add table of contents to doc pages

---

templates/data/kafka/what-is-kafka.html

- Replaced references to `rock` with `OCI-compliant`
- Go to `data/kafka/what-is-kafka`
- Compare the page against the [copy doc](https://docs.google.com/document/d/1IThZcfKZcv-ArqU_0n8A181AGkQPUn_Iq1O4sqk5GTs/edit?tab=t.0)
Fixes [WD-17929](https://warthogs.atlassian.net/browse/WD-17929)
[WD-17929]: https://warthogs.atlassian.net/browse/WD-17929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-17929] Copy update on data/kafka/what-is-kafka

---

.env
konf/site.yaml
requirements.txt
templates/base_index.html
templates/careers/job-detail.html
tests/test_recaptcha.py
webapp/app.py
webapp/greenhouse.py
webapp/recaptcha.py

Added recaptcha verification on job application submit. Recaptcha is activated on /careers pages.
A flying recaptcha logo is visible in the bottom right:
Error template is re-used to display failed recaptcha verification:
- Check if GREENHOUSE_DEBUG=true (There should be a message in the logs to indicate that)
- Navigate to /careers and try to apply for a job.
- To simulate failed recaptcha set RECAPTCHA_SCORE_THRESHOLD="1.1"
- To simulate cached page (without recaptcha) - revert `templates/base_index.html` and `templates/careers/job-detail.html`. Submit should succeed when RECAPTCHA_ENABLED="false"

[WD-17199] job apply recaptcha

---

templates/data/mongodb/what-is-mongodb.html

- Minor copy update to the "What is MongoDB?" page per [copydoc](https://docs.google.com/document/d/1hET-ylqXq96mOfj4hovqilX5Nl0J8FLw1gkRMJkIjp8/edit?tab=t.0).
- Go to https://canonical-com-1482.demos.haus/data/mongodb/what-is-mongodb
- Verify "MongoDB® Rock container image" is replaced with "MongoDB® OCI-compliant container image"
- Verify "So solid and secure, we call it a Rock." is deleted 
Fixes [#17925](https://warthogs.atlassian.net/browse/WD-17925)

Update what is mongodb page

---

templates/base_index.html
templates/docs/shared/_docs.html
templates/docs/shared/_footer.html

Moved a footer that was implemented for multipass.run's Docs pages some time ago into canonical.com and used it for all Docs pages on canonical.com.
- Open demo instance
- Open Docs pages, for example at /multipass/docs or /mircostack/docs and check that they use their own footer
- Open other pages (not Docs) and check that they still use an existing footer (similar to production)
Fixes https://warthogs.atlassian.net/browse/WD-17951
Normal footer:
Docs footer:

[WD-17951] use different footer for docs pages

---

templates/solutions/ai/index.html

- page refresh: AI solutions
- View the site locally in your web browser at: https://canonical-com-1455.demos.haus/solutions/ai
- Page redesign is applied properly
Fixes WD-17320

Page refresh: /solutions/ai

---

templates/blog/featured-articles.html

- Removed duplicate line-break on canonical.com/blog
- Open the demo at https://canonical-com-1502.demos.haus/blog and check that there are no double line-breaks
Fixes [WD-12149](https://warthogs.atlassian.net/browse/WD-18149)
[WD-12149]: https://warthogs.atlassian.net/browse/WD-12149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: removed repeat linebreak

---

templates/blog/article.html

- DJlint was changing the format of some logic to handle a piece of JSON we use in metadata. This PR disable Djlint for these lines and reverts the formatting changes
- Check the code format is the same as before it was formatted, [see git blame](https://github.com/canonical/canonical.com/blame/077fbdf3579c5e226ee3c6a814ced7440be99294/templates/blog/article.html#L24)
Fixes https://github.com/canonical/canonical.com/pull/1497#discussion_r1916657572

fix(/blog/article): Disable djlint for json data processing

---

static/sass/styles.scss

- Added index to modal close button to render above input elements
- Open the form at http://0.0.0.0:8002/solutions/ai#get-in-touch
- Scroll through the options and confirm that the modal close button renders above all inputs
Fixes [WD-18103](https://warthogs.atlassian.net/browse/WD-18103)
[WD-18103]: https://warthogs.atlassian.net/browse/WD-18103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: render close button above all input elements

---

static/js/navigation/ga-tracking.js

- Updated values for `origin` and `to` in GAEvents to submit correct paths when the event comes from a button.
- Open the demo at https://canonical-com-1512.demos.haus/data/opensearch. Open dev tools and type `dataLayer`. Take note of the entries.
- Click `Contact Us` and in dev tools type `dataLayer` again. You should see an entry similar to:
```
eventAction: "from: /data/opensearch to: data/opensearch#get-in-touch"
```
where the `from:` is the url of the page, and the `to:` is the url of the modal
Fixes [WD-13714](https://warthogs.atlassian.net/browse/WD-13714)
[WD-13714]: https://warthogs.atlassian.net/browse/WD-13714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: push correct origin for button events

---

konf/site.yaml
requirements.txt
static/sass/_pattern_blog-card.scss
static/sass/_pattern_strip.scss
static/sass/styles.scss
templates/case-study/index.html
webapp/app.py

- Build case study index page that includes static and Discourse case study
- Go to https://canonical-com-1509.demos.haus/case-study
- Check that the case studies are showing as expected
- Click through some of them and notice that some are static & some are Discourse-hosted (the old PDF engage pages)
Fixes [WD-17189](https://warthogs.atlassian.net/browse/WD-17189)
[WD-17189]: https://warthogs.atlassian.net/browse/WD-17189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Build case study index page

---

requirements.txt
templates/blog/article.html

- Fixes and adds the meta_description coming from wp blogs.
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
-  Visit https://canonical-com-1518.demos.haus/blog/what-is-iot-device-management and see if value of `meta_description` is "This post explains the key concepts behind loT device management, why it is important and the best practices organizations should follow."

Fix: Correct Meta_description for wordpress Blogs

---

static/sass/styles.scss

Remove the bespoke styling applied to the detailed stepped list which was causing issues on the candidate page. This change was introduced for the /openstack/architecture page but this should be addressed differently and upstream.
- Go to a candidate page in prod and see the numbers are broken
- Go to the demo and see the same candidate page looks correct
Fixes https://github.com/canonical/canonical.com/issues/1451

fix(candidate): Remove the bespoke styling: detailed stepped list

---

requirements.txt
templates/base_index.html
templates/index.html
templates/navigation/partials/_preview-links.html

Improve performance of the website loading via:
- upgrading version of the canonicalwebteam.flask-base package to 2.1.0 to enable JS and CSS compression
- lazy loading images that are not immediately visible on the home page
- deferring JS that is not needed immediately
- Open the demo link below and check the size of the resources via Network tab of the dev console. Compare it to the size of the resources on production. Make sure it's smaller which means the website loads quicker.
- You can also use third-party tools like https://pagespeed.web.dev/ to compare the performance of the demo instance vs production.

upgrade flask-base to enable assets compression

---

templates/partners/become-a-partner.html
templates/partners/channel-and-reseller.html
templates/partners/desktop.html
templates/partners/executive-summit.html
templates/partners/find-a-partner.html
templates/partners/gsi.html
templates/partners/ihv-and-oem.html
templates/partners/iot-device.html
templates/partners/isv-partners.html
templates/partners/public-cloud.html
templates/partners/silicon/index.html

_Note: Continuation of https://github.com/canonical/canonical.com/pull/1523_
- Replaced deprecated `p-block` class with it's current equivalent `p-section--shallow`
- Removed misused class combinations
- Check the following pages against prod and see that they do not have any visual changes: 
Fixes https://warthogs.atlassian.net/browse/WD-14226

fix: remove `p-block` throughout partners bubble

---

templates/lxd/manage.html

- Fixed incorrect modal call
- Drive by: fixed misplaced hr showing up twice above list
- View the site locally in your web browser at: https://canonical-com-1527.demos.haus/lxd/manage
- Click the "Talk to our LXD experts" cta and see that the modal opens as expected
- Under the "Third-party integrations" see that there is not a duplicate hr above the Ansible list items
Fixes #

fix: /lxd/manage modal

---

templates/blog/article.html
templates/blog/blog-card.html
templates/careers/_base-department.html
templates/careers/company-culture/remote-work.html
templates/careers/index.html
templates/contact-us.html
templates/documentation/_documentation-header.html
templates/documentation/beyond-canonical.html
templates/documentation/index.html
templates/documentation/open-documentation-academy.html
templates/documentation/work-and-careers.html
templates/partial/_careers_navigation.html

_Note: There are 20+ files where this needs to be done, I'm splitting them up into separate prs so that it's easier to review_
- Replaced deprecated `p-block` class with it's current equivalent `p-section--shallow`
- Removed misused class combinations eg `p-section u-no-padding--top`
- Ran djlint where needed
- Check the following pages against prod and see that there are no visual changes: 
Fixes https://warthogs.atlassian.net/browse/WD-14226

fix: Remove `p-block` usage 

---

templates/partners/silicon/intel/index.html

Adds links to certified devices.
JIRA: https://warthogs.atlassian.net/browse/WD-18297
Copy doc: https://docs.google.com/document/d/1GstP9FfZfbXO81YcX-9oCJdP9pamlgpl2kKkSqlrWFE/edit?tab=t.0#heading=h.dhplvd7mdy3g
Drive-by: wrap links around images in "Explore how to optimize…" section for consistency. And fixed lazy loading of hero image.
- Open demo https://canonical-com-1521.demos.haus/partners/silicon/intel
- Scroll down to ["Explore Ubuntu-certified Intel Hardware backed by Ubuntu Pro" section](https://canonical-com-1521.demos.haus/partners/silicon/intel#:~:text=Explore%20Ubuntu%2Dcertified%20Intel%20Hardware%20backed%20by%20Ubuntu%20Pro)
- Make sure all images have link below, as per copy doc
Fixes https://warthogs.atlassian.net/browse/WD-18297

Add links to certified devices on Intel partner page

---

static/sass/styles.scss
templates/documentation/_documentation-tab-navigation.html

- Made tabbed list full screen on medium size
- Made side navigation full width like on [u.com](https://ubuntu.com/download/alternative-downloads)
- Open this [demo](https://canonical-com-1529.demos.haus/documentation)
- Use medium size screen from developer tools
- Verify the tabbed list is full width
- Toggle side navigation by clicking on "Toggle side navigation" button.
- Verify the side navigation is full height
Fixes #[WD-8834](https://warthogs.atlassian.net/browse/WD-8834)
[WD-8834]: https://warthogs.atlassian.net/browse/WD-8834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Wd 8834 fix: full width tabbed list on medium screens + fixed side navigation

---

templates/embedding/index.html
templates/shared/forms/form-fields.html
templates/shared/forms/form-template.html

- Pass an optional formId prop when including form-template.html. If it is passed, it will be used for the formId submitted to marketo, otherwise the one specified in form-data.json will be used.
- Added example (to be removed before merging) at embedding/index.html
- Navigate to [embedding#get-in-touch](https://canonical-com-1536.demos.haus/embedding#get-in-touch)
- Fill and submit the form
- Check the payload in network tab and see if it shows correct formId
- Make sure the form submission works.
- Also, navigate to any form that uses formId from form-data.json, for example, [/data/postgresql#get-in-touch](https://canonical-com-1536.demos.haus/data/postgresql#get-in-touch)
- Fill and submit the form
- Make sure the formId is correct in payload and verify the form submission works.
Fixes …

[WD-18726] Introduced an optional formId prop to form-template.html

---

templates/press-centre/card.html
templates/press-centre/index.html
templates/projects/directory.html
templates/projects/index.html
templates/shared/_promoted_roles.html

_Note: Continuation of https://github.com/canonical/canonical.com/pull/1523_
- Replaced deprecated `p-block` class with it's current equivalent `p-section--shallow`
- Removed misused class combinations
- Check the following pages against prod and see that there are no visual changes:
Fixes https://warthogs.atlassian.net/browse/WD-14226

fix: remove final `p-block` instances

---

templates/partners/partial/_homepage-form.html
templates/solutions/infrastructure/_form_infrastructure.html
templates/solutions/open-source-security/_form-open-source-security.html

- Adds the field 'selfReportedAttribution' to three high traffic fields, [as per request](https://warthogs.atlassian.net/browse/WD-18038):
https://canonical-com-1538.demos.haus/#get-in-touch
https://canonical-com-1538.demos.haus/solutions/infrastructure#get-in-touch
https://canonical-com-1538.demos.haus/solutions/open-source-security#get-in-touch (also formated, hence big diff)
- Check out out each of the above demo links
- Check the form has a optional text input labelled 'How did you hear about us?'
- Fill in the form and ensure you see 'selfReportedAttribution' in the payload
- Check the form is received in Marketo
Fixes https://warthogs.atlassian.net/browse/WD-18038

feat: Add 'selfReportedAttribution'  field to 3 high traffic forms for testing

---

navigation.yaml

- Adds /observability to the meganav, see [copydoc](https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit?tab=t.0#heading=h.57yzphrdgf4q)
- Open [the demo](https://canonical-com-1540.demos.haus/)
- Open the navigation dropdown 'Solutions'
- You will see 'Observability' at the bottom of the 'Categories' list
- Click the link and see you are taken to https://canonical-com-1540.demos.haus/observability
Fixes https://warthogs.atlassian.net/browse/WD-18252

feat: Add /observability to the meganav

---

secondary-navigation.yaml
templates/data/mysql/support.html

- View the site locally in your web browser at: https://canonical-com-1487.demos.haus/data/mysql/support
- Page redesign is applied properly
- [Design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=3042-21606&t=88BxnWXVPxmUkG99-0)
- [Copydoc](https://docs.google.com/document/d/17YqM46OZOIBXg2okpsxJ9c7WYjWACKJWRAT1A_ChSMc/edit?tab=t.0#heading=h.3ppydbf0tgen)
Fixes WD-17641

add MySQL support page

---

secondary-navigation.yaml

- Removed the Streaming Tab from secondary-navigation.yaml.
- Verify that the Streaming tab is no longer present in the secondary navigation menu of Canonical.com/data
Jira Issue: https://warthogs.atlassian.net/browse/WD-19130
Copydoc: https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit?tab=t.0#heading=h.ynmgujjj40mc%20-%20it%20was%20not%20added%20to%20the%20copydoc%20and%20so%20should%20not%20be%20added%20to%20the%20navigation

fix(navigation): Remove 'Streaming' link from /data [WD-19130]

---

templates/careers/application/index.html

Hanna and Mark have re-recorded the old “How We Hire” video, and it is now uploaded and live on YouTube [here](https://www.youtube.com/watch?v=e-t1QBZssFU).
TS would like us to replace the old vid on the candidate dashboard with this new one.
- Updated YouTube embed on Candidate Dashboard to point to the new How We Hire video.
- Run the site using `dotrun`
- Navigate to test candidate "Bruno Fernandes" candidate dash: http://localhost:8002/careers/application/gAAAAABl2Dcq_kzb-fhHaxzIeu5P8A-wItXtC9nPndSvP3MjHrxwjC0REX-MX53dQq3Tea-3AUGuYNNEtAwPJHcVMhLOgGJRhQ==
- Ensure that the embedded "How We Hire" video is the [new one](https://www.youtube.com/watch?v=mOFgDpjRiO8), not the [old one](https://www.youtube.com/watch?v=ik8AXTjUbS4). …

Update How We Hire video on Candidate Dashboard

---

templates/base_index.html
templates/case-study/episensor.html
templates/case-study/esa.html
templates/case-study/grundium-ubuntu-pro-for-devices.html
templates/case-study/lucid-aws-fedramp-compliance-case-study.html
templates/case-study/sbi-bits.html
templates/case-study/ubuntu-pro-support-for-games-developer.html

- Add `discourse-tag` meta tag for case studies
- Allow devs to add `meta_discourse_url` to static case studies and link them to the discourse post 
- Go to any static case study page, accessible through /case-study
- Example: /case-study/sbi-bits
- Inspect page and search for `discourse-url`, see that it links the discourse page correctly
Fixes [WD-19234](https://warthogs.atlassian.net/browse/WD-19234)
[WD-19234]: https://warthogs.atlassian.net/browse/WD-19234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add discourse url metatag for case studies

---

templates/data/postgresql/form-data.json
templates/data/streaming/form-data.json
templates/embedding/form-data.json
templates/partners/silicon/intel/form-data.json
templates/shared/forms/form-fields.html
templates/solutions/open-source-security/cyber-resilience-act/form-data.json
templates/solutions/telco/form-data.json

- Set first name, last name and email as active by default on contact forms
- Remove entries for these active fields on affected `forms-data.json` 
- Compiled affected form IDs
- Go to affected forms
- Check that first name, last name and email are showing on the modal
- Submit form and see that it goes through Marketo as expected
Fixes [WD-17910](https://warthogs.atlassian.net/browse/WD-17910)
[WD-17910]: https://warthogs.atlassian.net/browse/WD-17910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Set names and email as active fields on contact forms 

---

static/js/modals.js
templates/edge-computing/base_edge-computing.html
templates/edge-computing/index.html
templates/partners/partial/_homepage-form.html

- Basically copy pasted an existing page at ubuntu.com/edge-computing to a new page at canonical.com. 
- There is another PR [here](https://github.com/canonical/ubuntu.com/pull/14758) that removes the page from ubuntu.com and redirects it to this new webpage.
- Used the same type of modal form as on ubuntu.com/edge-computing. It has already been created on canonical.com before, so just reused that with a different form ID.
- Created a new copy document in canonica.com's GDrive folder (by copying the old one) and referenced that in the new page.
- Open the demo at https://canonical-com-1564.demos.haus/edge-computing
- Observe the page and check that it looks identical to the one at https://ubuntu.com/edge-computing
- Click on "Get in touch" links/buttons and verify that the form works and …

[WD-19429] migrate /edge-computing page from u.com to c.com

---

static/sass/styles.scss
templates/documentation/beyond-canonical.html
templates/documentation/index.html
templates/documentation/open-documentation-academy.html
templates/documentation/work-and-careers.html

- Removed toggle nav
- Fixed side nav going over the top nav
- Open this [demo](https://canonical-com-1537.demos.haus/documentation) in your browser
- Scroll up and down to make sure side nav is not going over the top nav
- Change screen size to mobile/tablet from dev tools
- Make sure there is no button for toggling side navigation
- Do the above for all of the 4 different tabs on the page
Fixes #[WD-18681](https://warthogs.atlassian.net/browse/WD-18681)
[WD-18681]: https://warthogs.atlassian.net/browse/WD-18681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-18681] Removed toggle nav on documentation

---

templates/microcloud/index.html

Updated the Dell logo on the Microcloud page
- Go to https://canonical-com-1574.demos.haus/microcloud
- Check that the Dell logo has changed (compare to [production](https://canonical.com/microcloud))
Fixes https://warthogs.atlassian.net/browse/WD-19550

chore: Update Dell logo on the Microcloud page

---

webapp/app.py

- Allow passing of nested index.html files to childrenPaths in the form generator, this is a copy paste of the work [here](https://github.com/canonical/ubuntu.com/pull/14780/files)
- Open [https://canonical-com-1572.demos.haus/embedding/nest-test](https://canonical-com-1572.demos.haus/embedding/nest-test)
- Test the form opens and submits etc
Fixes https://warthogs.atlassian.net/browse/WD-19631

feat: Allow passing of nested index.html files to childrenPaths in the form generator

---

navigation.yaml
templates/navigation/partials/_preview-links.html

- Added clickable link to `preview_secondary_links` 
- Updated link in meganav
- [Copydoc](https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit?tab=t.0#heading=h.66b5xdgm390p)
- [Demo](https://canonical-com-1556.demos.haus/)  See if the case-study link is clickable in solutions meganav.
Fixes #[WD-19131](https://warthogs.atlassian.net/browse/WD-19131)
[WD-19131]: https://warthogs.atlassian.net/browse/WD-19131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-19131 Updated link in Meganav

---

templates/data/opensearch/what-is-opensearch.html

- opensearch diagram
- replaced 'Rock' references to `OCI-compliant` containers.
- View the site locally in your web browser at: http://localhost:8002/data/opensearch/what-is-opensearch

[WD-17926] copy update for opensearch

---

package.json
static/js/modals.js
templates/solutions/cloud-native-development/form-data.json
templates/solutions/cloud-native-development/index.html
yarn.lock

- Build page on `/solutions/cloud-native-development`
- Build a get in touch modal 
- Go to  https://canonical-com-1577.demos.haus/solutions/cloud-native-development
- Compare page against [Figma](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/canonical.com%2Fsolutions?node-id=2212-4394&t=GzX8JZVNlu5WJdgc-0) and [copy doc](https://docs.google.com/document/d/1xn9QcJ7OfELzRBtUlu-WkSSnC9lYideoUu-YV1yBNIU/edit?tab=t.30h92ifbdc1)
- Check the get in touch modal works fine 
Fixes #https://warthogs.atlassian.net/browse/WD-19255

Build page on /solutions/cloud-native-development

---

webapp/greenhouse.py

- Manually add 'alliances' as a department to the greenhouse dict
- open https://canonical-com-1595.demos.haus/careers
- check it loads
- check all the careers pages load
Fixes #

fix: Hot fix for careers 500ing due to missing department field

---

requirements.txt
webapp/app.py

- Published sitemaps-repo on test PyPi - [package here](https://test.pypi.org/project/canonicalwebteam.sitemaps-parser/1.0.0/)
- Update `requirements.txt` to use the package
- Note: The package is currently on test pypi. It will be migrated outside of test before this feature branch is merged
- Check that demo loads
- Go to /sitemaps_parser
- See that it shows JSON field of directory tree
Fixes [WD-19979](https://warthogs.atlassian.net/browse/WD-19979)
Fixes #
[WD-19979]: https://warthogs.atlassian.net/browse/WD-19979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Update requirements to use sitemaps-parser package

---

package.json
yarn.lock

- Bumped vanilla version to 4.21.1
- View the site locally in your web browser at: https://canonical-com-1598.demos.haus/
- This version shouldn't introduce any breaking changes, but click through a couple pages to double check nothing looks broken
Fixes https://warthogs.atlassian.net/browse/WD-19622

chore: Bump vanilla version

---

templates/data/postgresql/index.html

Updates broken link to `postgresql` docs
- Go to https://canonical-com-1602.demos.haus/data/postgresql
- Check "Get started with Charmed Postgresql" link goes to the docs on charmhub.io
https://chat.canonical.com/canonical/pl/gxopsm88e7ra3mxa48pqn8ke3y

update broken charmhub.io link

---

static/js/navigation/main.js
templates/index.html
templates/navigation/partials/_dropdown-desktop.html
templates/navigation/partials/_tab-panel.html

- Fixed: prevent page from scrolling to top when changing global nav sections
- Fixed: global nav categories detail section disappearing when selecting any tab on the home page
- Fixed: tabs selection glitches when clicked too many times
- View the site in your web browser at: https://canonical-com-1603.demos.haus/
- Verify all three issues documented [here](https://warthogs.atlassian.net/browse/WD-20171) have been fixed.
Fixes #[WD-20171](https://warthogs.atlassian.net/browse/WD-20171)
[WD-20171]: https://warthogs.atlassian.net/browse/WD-20171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-20171] fix: Global nav and tabbed content glitches

---

templates/careers/job-detail.html

- unfliped single-select options in job application
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/5191982/application
- Check countries ordering

unflip single-select options in job application

---

templates/solutions/open-source-security/cyber-resilience-act/index.html

Added CTA section to bottom of the page
- visit [/solutions/open-source-security/cyber-resilience-act](https://canonical-com-1599.demos.haus/solutions/open-source-security/cyber-resilience-act)
- Compare with copy doc at https://docs.google.com/document/d/13VaiP6GGkGB4mE01bIqJ3cg8MfQXulNs9m3cmYb20HQ/edit?tab=t.0
Fixes [#WD-19768](https://warthogs.atlassian.net/browse/WD-19768)

Add CTA section to bottom of page

---

templates/careers/application/index.html
templates/careers/hiring-process/index.html

- Update hiring process quotes
- Add link to hiring process page on candidate dash
- Navigate to [the hiring process page](http://localhost:8002/careers/hiring-process) and ensure that the quotes at the bottom match Hanna's changes in [the copy doc](https://docs.google.com/document/d/1j-G0LCapJ1zRnNgQeoC0_rh15N6ICdpDy7M1tubQuoo/edit?tab=t.0).
- Navigate to this candidate dashboard and ensure that the "Listen to how we hire at Canonical" link has been replaced with a "Read about our hiring process" link, which links to the aforementioned `/careers/hiring-process` page, opening in a new tab.
[TSP-775](https://warthogs.atlassian.net/browse/TSP-775) …

Update hiring process information

---

static/files/latest-multipass-releases.json

- Update the latest release of Multipass to 1.15.1.
- Update urls and description accordingly.

Update the latest release of Multipass to 1.15.1

---

navigation.yaml

- Changed url for ubuntu.com/summit page.
- Linked to https://github.com/canonical/ubuntu.com/pull/14872/
Fixes #

Changed url to new summit page

---

requirements.txt
templates/case-study/index.html
webapp/app.py

- Adds 'tag' filter to /case-study search
- Adds loading state to the search/clear button
- Add card limit to 21 (a multiple of 3, so there isn't an empty space at the bottom of the page)
- Bump discourse version
- Go to https://canonical-com-1618.demos.haus/case-study
- Use the 'language' and 'tags' drop down to test the search filter
- See the filter button is disabled when clicked and displays a spinner
- Try the clear filter button, except the same loading behavior as the search filter
Fixes https://warthogs.atlassian.net/browse/WD-19545

feat: Add 'tag' filter to /case-study search

---

templates/embedding/faqs.html

- updates link from https://canonical.com/embedding/faqs to https://ubuntu.com/legal/intellectual-property-policy
- Go to https://canonical-com-1619.demos.haus/embedding/faqs 
- Click the link for 'IPRights Policy'
- See it takes you to https://ubuntu.com/legal/intellectual-property-policy
Fixes https://warthogs.atlassian.net/browse/WD-20787

fix: Update link to privacy policy on /embedding/faqs

---

templates/lxd/install.html

- Update lxd installation page to recent ubuntu version and
- Link to new image server
- check https://canonical-com-1633.demos.haus/lxd/install

Update lxd installation page to recent ubuntu version and new image server

---

templates/data/streaming/index.html

- Adjust title casing for /data/streaming 
- Spacing was automatically reformatted for proper indentation
[Demo](https://canonical-com-1630.demos.haus/data/streaming)
Check out this feature branch
Run the site using the command ./run serve or dotrun
View the site locally in your web browser at: http://0.0.0.0:8001/
Be sure to test on mobile, tablet and desktop screen sizes
[List additional steps to QA the new features or prove the bug has been resolved]
Fixes #[WD-21247]
[WD-21247]: https://warthogs.atlassian.net/browse/WD-21247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-21247] Title fix for /data/streaming

---

postcss.config.js

- Add classes starting with 'iti' to safelist of purgecss
- Open [demo](https://canonical-com-1647.demos.haus/)
- Check some forms that the country dropdown for mobile works
ex. https://canonical-com-1647.demos.haus/data
Fixes https://warthogs.atlassian.net/browse/WD-21490

fix: Don't purge intl-tel-input styles

---

templates/java/index.html

- Add the new Java page.
Copy doc:
https://docs.google.com/document/d/1sTYQlLM1jWDx-01oC5QY0OdTXNas8KHBoFPR2RW0AQg/edit?tab=t.0
Design:
https://www.figma.com/design/1QpQnDKorotiR48X8zmmo6/Canonical.com-java?node-id=0-1&p=f&t=ZNKqsDZfYIeVUMkE-0
- Go to [/java](https://canonical-com-1646.demos.haus/java)
- Check that it matches the design.
https://warthogs.atlassian.net/browse/WD-20387

feat: Add new Java page

---

tests/test_sitemap.py

- Brought over work from https://github.com/canonical/ubuntu.com/pull/15001
- Implement testing for directory parser
- Added 3 tests:
- `/sitemap_tree.xml` returns a valid XML response
- `/sitemap_parser` returns a valid JSON response
- urls in JSON response are present in the `sitemap_tree.xml`
- See that [`test-python`](https://github.com/canonical/canonical.com/actions/runs/14531208791/job/40771151590?pr=1649) action passes
Fixes [WD-19199](https://warthogs.atlassian.net/browse/WD-19199)
[WD-19199]: https://warthogs.atlassian.net/browse/WD-19199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Implement testing for sitemap parser

---

templates/case-study/ubuntu-pro-support-for-games-developer.html

- Added a button linked to free trial
- View the site in your web browser at: https://canonical-com-1653.demos.haus/case-study/ubuntu-pro-support-for-games-developer
- Scroll to bottom and verify the presence of a green button named "Access a free trial"
- Click on the  button and verify it redirects to the correct destination.
Fixes #[WD-21440](https://warthogs.atlassian.net/browse/WD-21440)
[WD-21440]: https://warthogs.atlassian.net/browse/WD-21440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-21440] - add a link to free trial

---

requirements.txt
tests/test_sitemap.py

- PR to QA missing homepage on sitemap template
- Bump directory-parser
- Fly-by: Update `test_sitemap.py` to include index pages
- See that [test-python](https://github.com/canonical/canonical.com/actions/runs/14590131688/job/40923282481?pr=1654) action passes
- See that index page is present on https://canonical-com-1654.demos.haus/sitemap_tree.xml
Fixes #

chore: Bump directory-parser

---

templates/data/lakehouse/form-data.json
templates/data/lakehouse/index.html
templates/data/sitemap.xml

~**NOTE**: Replace `formId` in `/data/form-data.json` once marketo team provides it. Currently using another id from a similar form.~
- Built a new page i.e., /data/lakehouse
- Add entry to data/sitemap.xml
- Added modal form
- View the site in your web browser at: https://canonical-com-1658.demos.haus/data/lakehouse
- Make sure to test on all screen sizes i.e., mobile, tablet and desktop.
- Verify the page design matches [figma](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/canonical.com-data?node-id=3626-4237&t=4klvTIOH0AJbjFmU-0)
- Verify the page content matches [copydoc](https://docs.google.com/document/d/1iG9Fcg1w9FWyWO84Gj6RFFYdu5xzEDFBMxnjAAQFW34)
Fixes #[WD-20743](https://warthogs.atlassian.net/browse/WD-20743)
[WD-20743]: …

[WD-20743] feat: new /data/lakehouse page

---

navigation.yaml

Added links to Ubuntu Pro free trial and Ubuntu Pro as requested in [the copy doc](https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit?tab=t.0)
- Click the "Products" dropdown in the top navigation and go to the "Security and support" section
- Check that the "Quick links" column has an "[Ubuntu Pro free trial](https://ubuntu.com/pro/free-trial)" link
- Check that the "Quick links" column has an "[Get Ubuntu Pro now](https://ubuntu.com/pro/subscribe) link
Fixes https://warthogs.atlassian.net/browse/WD-21776

chore: Add Ubuntu Pro links to navigation

---

.github/workflows/live-links.yaml

Add `live-links.yaml` file that adds a daily workflow that checks for broken links in the repository and reports it to MM's Web channel (similar to how it works on ubuntu.com)

Add workflow for checking broken links

---

navigation.yaml

- Add a link for the Canonical trust center
- Shorten a link under solutions from “Cloud-native app development” to “Cloud-native apps”
[Demo](https://canonical-com-1682.demos.haus/)
- Click on the `Company` dropdown and check that there is `Company Trust Center` after `Ubuntu Summit`
- Also, Click on `Solutions` and check that `Cloud-native app development` is shortened to `Cloud-native apps`
[Copy docs](https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit?tab=t.0)
Fixes #

copy-update: update canonical.com navigation

---

static/js/modals.js

- Dynamically add `aria-expanded` attribute on contact buttons.
- View the site locally in your web browser at: http://0.0.0.0:8002
- Alternatively, visit the demo [here](https://canonical-com-1679.demos.haus/)
- Click on the Contact us / get in touch buttons and verify the `aria-expanded` attribute is toggled as expected.
Fixes #[WD-21454](https://warthogs.atlassian.net/browse/WD-21454)
[WD-21454]: https://warthogs.atlassian.net/browse/WD-21454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-21454] feat: add aria-expanded label on the contact modal trigger button at canonical.com form generator

---

templates/solutions/index.html

Following up on #1690 now we have an updated asset from @eliman11 :)
Replaces the BT Group signpost logo on /solutions with a higher quality version.
- Go to solutions page demo
- Verify the BT Group signpost logo has been changed to the new asset from the [copydoc](https://docs.google.com/document/d/1vdnlbFSCidiNBXZ1zVKHWNIv1kl6C0vMmQAMYfz3yhU/edit?tab=t.0)
Fixes [WD-22013](https://warthogs.atlassian.net/browse/WD-22013)
Before
After
[WD-22013]: https://warthogs.atlassian.net/browse/WD-22013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-22013]: replace BT Group signpost logo with higher quality asset on `/solutions`

---

templates/consulting/index.html
templates/edge-computing/index.html
templates/navigation/navigation.html
templates/solutions/open-source-security/index.html

- Update instances of `/desktop/organisations` to `/desktop/organizations`
- Update menu and search anchor links to buttons. There is no c.com/search and c.com/navigation (unlike on u.com) so there is no need to have them as anchor links.
- Go to https://canonical-com-1694.demos.haus/microcloud
- Resize the window until you see "Menu" bar, click on it and see that it works as expected
- Click on search button and see that it works as expected
Fixes [WD-22028](https://warthogs.atlassian.net/browse/WD-22028)
[WD-22028]: https://warthogs.atlassian.net/browse/WD-22028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Broken new links

---

templates/data/mysql/index.html
templates/data/postgresql/index.html

- fix: Failing links
- Check the failing linker links now work. These can be found...
https://canonical-com-1696.demos.haus/data/postresql under 'Read the documentation for K8s and VMs' (specifically the 'VMs' link)
https://canonical-com-1696.demos.haus/data/sql under 'Get started with Charmed MySQL'
Fixes https://warthogs.atlassian.net/browse/WD-22064

fix: Failing links

---

templates/careers/includes/_fast-track-jobs.html

- Added missing FT roles in https://canonical.com/careers/engineering
- `Rust Engineering Lead - Linux and Open Source`
- `Performance Engineer - Open Source`
- `Graduate Software Engineer, Open Source and Linux, Canonical Ubuntu`
copy doc: https://docs.google.com/document/d/12GWF6eVKezvENc66p3QZ5ZEO8H2QBIlU56RPZNdCPdI
- goto: https://canonical-com-1712.demos.haus/careers/engineering
- Check the new 3 links

add missing fast track roles in careers page

---

templates/edge-computing/index.html

- Fix the form submission return URL for the `/edge-computing`
- Quick copy fixes
- Check out the demo here: https://canonical-com-1713.demos.haus/edge-computing
- Make sure the form returns to the original page after submission.
- Make sure the latest copy changes are reflected.
- [WD-21650](https://warthogs.atlassian.net/browse/WD-21650)
[WD-21650]: https://warthogs.atlassian.net/browse/WD-21650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use correct form return url for /edge-computing and copy

---

navigation.yaml
secondary-navigation.yaml
templates/anbox-cloud/form-data.json
templates/anbox-cloud/index.html
webapp/handlers.py

- Migrated the following files
- /anbox-cloud/index.html
- Added a form-data.json for anbox-cloud contact modal
- /anbox-cloud/form-data.json
- View the site in your web browser at: https://canonical-com-1714.demos.haus/anbox-cloud
- Verify the page exists and looks identical to https://anbox-cloud.io
- Click on "Contact us" or "Talk to an expert" buttons
- Verify the modal form opens up
- Verify the form submits successfully.
- Click on all the links in bubble navigation (Install, Docs, Forum) and verify they work.
- In the global meganav, click Products > Private Cloud > Anbox Cloud and verify it works.
Fixes #[WD-18551](https://warthogs.atlassian.net/browse/WD-18551)
[WD-18551]: https://warthogs.atlassian.net/browse/WD-18551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

[WD-18551] chore: Migrate anbox-cloud.io to canonical.com

---

.github/workflows/sitemap.yaml

- Run `sitemap.yaml` action on main u.com repo only
- Used in other GH actions to only trigger on main repo e.g [live-links.yaml](https://github.com/canonical/ubuntu.com/blob/main/.github/workflows/live-links.yaml#L9)
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/
Fixes #

chore: run action on main repo only

---

tests/test_sitemap.py
webapp/app.py

- Add test coverage for `build_sitemap` tree
- See that `test-python` action passes
Fixes [WD-22432](https://warthogs.atlassian.net/browse/WD-22432)
[WD-22432]: https://warthogs.atlassian.net/browse/WD-22432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: add tests for build_sitemap tree

---

secondary-navigation.yaml
templates/data/spark/managed.html

* added new page for data/spark/managed
- Check the new page at https://canonical-com-1731.demos.haus/data/spark/managed
Fixes https://warthogs.atlassian.net/browse/WD-22642

Add new page data/spark/managed

---

requirements.txt
templates/search.html
webapp/app.py

- Bump canonicalwebteam.search module to 2.1.2
- Rebrand search page, similar to https://github.com/canonical/ubuntu.com/pull/15216
- Go to https://canonical-com-1765.demos.haus/search
- Check that design matches [Figma](https://www.figma.com/design/RIeBDWnFQVtYOQltavDcXf/Search--==ubuntu.com-and-canonical.com-?node-id=1-84&p=f&m=dev)
- Perform searches for no result and result pages 
Fixes [WD-22374](https://warthogs.atlassian.net/browse/WD-22374)
[WD-22374]: https://warthogs.atlassian.net/browse/WD-22374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Rebrand search page

---

templates/solutions/telco/index.html

- Add two new blog links to /solutions/telco
- Visit [/solutions/telco](https://canonical-com-1770.demos.haus/solutions/telco)
- Scroll down to the 'Learn more' section.
- Under "Access our blog" there should be two new links (the last two): "How enterprises are responding to the growing demand for 5G edge computing" and "BT Group and Canonical deliver 5G to UK stadiums"
https://warthogs.atlassian.net/browse/WD-23334

feat: update /solutions/telco with two new blog links

---

templates/contact-us.html
templates/form-data.json
templates/index.html
templates/shared/forms/form-fields.html

- FIx faling form ID 5311 (homepage_form) used on homepage and contact us page
- Update `form-fields.html` to include checkbox Others text field and radio fields
- Note: incorrect /edge-computing form uses incorrect form ID, requested for the copy doc to update the form [here](https://docs.google.com/document/d/1pWMeqRw3io8DlHhNDq4tZ5EKDvLJbVS4vA1kQthzLMc/edit?disco=AAABkWDVkEg). Once this is resolved, we can remove `_homepage-form.html` entirely
- Go to https://canonical-com-1769.demos.haus/#get-in-touch and https://canonical-com-1769.demos.haus/contact-us#get-in-touch
- Submit payload
- See that it goes through Marketo
Fixes [WD-23250](https://warthogs.atlassian.net/browse/WD-23250)
[WD-23250]: …

fix: migrate homepage form to form generator

---

templates/base_index.html

- add failing form banner `#contact-form-fail`
- Go to https://canonical-com-1774.demos.haus/#contact-form-success
- See that the failing form banner shows
Fixes [WD-23208](https://warthogs.atlassian.net/browse/WD-23208)
[WD-23208]: https://warthogs.atlassian.net/browse/WD-23208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add failing form banner

---

templates/index.html
templates/solutions/index.html

- Replaced correct asset on solutions page
- [demo](https://canonical-com-1786.demos.haus/solutions)
- Check the last section, previously telco and automotive had same assets
Fixes #[WD-23663](https://warthogs.atlassian.net/browse/WD-23663)
[WD-23663]: https://warthogs.atlassian.net/browse/WD-23663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bugfix: WD-23663 Replaced correct asset on solutions page

---

konf/site.yaml

feat: Add maas discourse API keys

---

static/sass/_pattern_homepage.scss

- fixed Color change on hover on disabled button
- [Demo](https://canonical-com-1788.demos.haus/#get-in-touch)
- Try to hover on disabled button and it shall stay same, compare it with live version on canonical.com, try submitting the form and see if the color of button remains same
Fixes # [WD-23689](https://warthogs.atlassian.net/browse/WD-23689)
[WD-23689]: https://warthogs.atlassian.net/browse/WD-23689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bugfix:(WD-23689) Color change on hover on disabled button

---

static/sass/styles.scss
templates/solutions/index.html

- Add anchore logo to solutions page
- Go to [Demo](https://canonical-com-1802.demos.haus/solutions)
- Scroll down to `open source security ` section
- Check that there is Anchore logo
[Copy docs](https://docs.google.com/document/d/1vdnlbFSCidiNBXZ1zVKHWNIv1kl6C0vMmQAMYfz3yhU/edit?tab=t.0)
Fixes #

add anchore logo to solutions page

---

.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md

Since we utilize a security advisory for reporting vulnerabilities, it's worth pointing external contributors to it as well

Update ISSUE_TEMPLATE.md, add a note about security advisory

---

scripts/build-modules.sh
templates/base_index.html

Adblockers, such as those built into brave and firefox are blocking requests for the `cookie-policy.js` file, as it seems to be matching their rules.
Updated the name to a more adblocker-friendly one. 
- View the [demo](https://canonical-com-1805.demos.haus/) in an incognito browser
- Check that there are no cpNs (cookie policy) related errors in the console
- Accept the cookie policy and browse the page
- Also try rejecting the cookie policy, or selecting multiple options and confirm there are no console errors
Fixes https://github.com/canonical/canonical.com/issues/1798
Addresses [WD-23839](https://warthogs.atlassian.net/browse/WD-23839)
[WD-23839]: …

feat: fix blocked cookie policy

---

static/js/forms.js

All the newsletters on canonical.com show an empty/transparent submit button when submitted. There should be a loading spinner visible.
Fixed the newsletter sign up button so it doesn't go blank when submitted
- View the site  in your web browser at: https://canonical-com-1809.demos.haus/blog
- Scroll down to the newsletter section
- Fill in details and click on "Sign up" button
- Verify the presence of a spinner
- Go to https://canonical-com-1809.demos.haus#get-in-touch
- Fill in form and submit
- Verify the presence of a loader in submit button
Fixes #[WD-23691](https://warthogs.atlassian.net/browse/WD-23691)
[WD-23691]: https://warthogs.atlassian.net/browse/WD-23691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-23691] fix: Newsletter 'sign up' buttons goes blank when clicked

---

templates/shared/forms/form-fields.html

- Added `autocomplete` attribute depending on the type of field
-  First name (given-name)
-  Last name (family-name)
- Email (email)
- Phone number (tel)
- Company/Company name (organization)
- Job title (organization-title)
- Open any form, for example https://canonical-com-1810.demos.haus/solutions/industrial#get-in-touch
- Verify the autocomplete fields work in personal information section

feat: add autocomplete attributes to form elements in form-generator template

---

static/js/tabbed-content.js

- Fixed the case where a modal trigger button be within tabbed content
- View the site in your web browser at: https://canonical-com-1814.demos.haus/solutions/cloud-native-development
- Click on the "Get in touch" button and verify the modal opens up
- Close modal, scroll down and find the "Let us build it" tab in "Choose your app modernization journey" section
- Select he tab, and click on "Get in touch" button.
- Verify the modal form opens up.
Fixes #[WD-24063](https://warthogs.atlassian.net/browse/WD-24063)
[WD-24063]: https://warthogs.atlassian.net/browse/WD-24063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-24063] fix: modal form not opening on canonical.com/solutions/cloud-native-development

---

secondary-navigation.yaml

- Add bubble nav to /data/valkey
- Go to [/data/valkey](https://canonical-com-1836.demos.haus/data/valkey).
- Check that there is a secondary nav item for "What is Valkey"
https://warthogs.atlassian.net/browse/WD-24282

feat: add bubble nav to /data/valkey

---

templates/public-sector/index.html

Add ESA video to the public sector page
- Go to /public-sector
- Scroll to the "Our solutions in action" section
- Click on ESA tab
- Play the video and check its the right one.
Fixes https://warthogs.atlassian.net/browse/WD-24528

WD-24528: Add ESA video to the public sector page

---

templates/data/spark/support.html

- Hid extra horizontal line on small screen
- Check out [demo link](https://canonical-com-1859.demos.haus/data/spark/support) and compare with https://canonical.com/data/spark/support to confirm issue was fixed
Fixes #1850 

style: hide duplicated hr rule on /spark/support page

---

templates/observability/what-is-observability.html
templates/solutions/ai/index.html

Similar to https://github.com/canonical/ubuntu.com/pull/15431, some cases were found of cover images without their required aspect ratio classes. This would cause images to not render in Vanilla >= 4.26.1.
- Navigate to the following pages and verify the cover images are rendered as expected:
- [observability/what-is-observability](https://canonical-com-1860.demos.haus/observability/what-is-observability)
- [solutions/ai](https://canonical-com-1860.demos.haus/solutions/ai)
Fixes https://chat.canonical.com/canonical/pl/7czayisdfid83xkc6758yomrkc
Before
After

Fix missing cover image aspect ratios

---

secondary-navigation.yaml
templates/mlops/kubeflow/what-is-kubeflow.html

- Migrated page from the u.com codebase
- Updated deprecated Vanilla classes and switched to using new grid
- Refactored images in favor of the image template
- Added docs link
- View the site locally in your web browser at: https://canonical-com-1857.demos.haus/mlops/kubeflow/what-is-kubeflow and see that the content and design matches https://ubuntu.com/ai/what-is-kubeflow
- Please make sure to double check links against [doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-23608

chore: Migrate /mlops/kubeflow/what-is-kubeflow

---

templates/partial/_footer.html

- update footer styling with dark theme class
- Check out the demo [link](https://canonical-com-1867.demos.haus/)
- Go through other pages like https://canonical-com-1867.demos.haus/solutions/ai and check the footer and ensure the text is visible
- Compare that with https://canonical.com and https://canonical.com/solutions/ai for example
Fixes # https://warthogs.atlassian.net/browse/WD-24694

style(footer): update footer styling with dark theme class

---

templates/anbox-cloud/form-data.json

- Make comment field required in the contact form
- Go to: https://canonical-com-1889.demos.haus/anbox-cloud#get-in-touch
Fixes [WD-25572](https://warthogs.atlassian.net/browse/WD-25572)
[WD-25572]: https://warthogs.atlassian.net/browse/WD-25572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(WD-25572): anbox-cloud - contact form - make comment field required

---

templates/data/mysql/managed.html
templates/data/opensearch/managed.html
templates/data/postgresql/what-is-postgresql.html
templates/data/spark/support.html
templates/documentation/beyond-canonical.html
templates/documentation/work-and-careers.html

Update assets to use the image_template to benefit from the optimisation of the image template
- Check out the demo branch
- Check https://canonical-com-1885.demos.haus/data/mysql/managed
- https://canonical-com-1885.demos.haus/data/opensearch/managed
- https://canonical-com-1885.demos.haus/data/postgresql/what-is-postgresql
- https://canonical-com-1885.demos.haus/data/spark/support
- https://canonical-com-1885.demos.haus/documentation/beyond-canonical
- https://canonical-com-1885.demos.haus/documentation/work-and-careers
and ensure images load properly and are not blurry
Fixes # https://warthogs.atlassian.net/browse/WD-23856

use image template on /data and /documentation pages

---

templates/mlops/kubeflow/index.html

- Add meta image to /mlops/kubeflow
- Check the [demo](https://canonical-com-1893.demos.haus/mlops/kubeflow) meta image is the same as in the [copydoc](https://docs.google.com/document/d/1Wvhl0yYV_w0BJsyZbQFKg_QV6RjMLbmQU3x0rsD2F4Q)
Fixes https://warthogs.atlassian.net/browse/WD-25539

feat: Add meta image to /mlops/kubeflow

---

navigation.yaml
redirects.yaml
secondary-navigation.yaml
static/js/tabbed-content.js
static/sass/_pattern_forms.scss
static/sass/styles.scss
templates/dqlite/index.html
templates/jaas/form-data.json
templates/jaas/index.html
templates/mir/index.html
templates/observability/what-is-observability.html
webapp/app.py

- Migrate the homepage, including updating to use current patterns:
- grid-row
- image template
- tabbed-content.js
- Migrate the form to form builder
- Migrate the secondary nav
- Update the mega nav link
- Migrate redirects.yaml and permanent-redirects.yaml
Flyby:
- Update the form template to align field sets with the grid
- Open the [demo](https://canonical-com-1851.demos.haus/jaas)
- See it matches https://jaas.ai/
- Test on all screen sizes
- Test the form goes through to marketo
Fixes https://warthogs.atlassian.net/browse/WD-24178

feat: Migrate jaas.ai to c.com/jaas

---

package.json
yarn.lock

- Bump Vanilla to 4.30.0
- Open the [demo](https://canonical-com-1897.demos.haus/)
- Have a click around and see nothing is broken
Fixes https://warthogs.atlassian.net/browse/WD-25989

chore: Bump Vanilla to 4.30.0

---

templates/mlops/index.html

- Removing a section in accordance to [this comment](https://docs.google.com/document/d/1k3-ZBUmzaiel-iTvsznJfMeV8ggkzgkSzpjMJIBd0d8/edit?disco=AAABps7phaM) from the copy doc
- Open https://canonical-com-1906.demos.haus/mlops
- Scroll down to "MLOPS SERVICES" section
- Check that the "Open source MLOps in the public cloud" part has been removed
Fixes https://warthogs.atlassian.net/browse/WD-26050

[WD-26050] remove a section from /mlops page

---

templates/maas/contact-us.html

- Added field for acquisition url to send correct url
- Visit [demo](https://canonical-com-1905.demos.haus/maas/contact-us) and fill the form, see the correct acquisition url goes into network payload
Fixes # https://warthogs.atlassian.net/browse/WD-26047

Bugfix: added acquisition url field

---

navigation.yaml
templates/open-source-adoption/index.html

Do not merge until 25/08/2025 10:00 CET
- Create `/open-source-adoption` page
- Add page to main nav
- View the site locally in your web browser at: http://0.0.0.0:8002/open-source-adoption
- **OR** visit the demo: https://canonical-com-1868.demos.haus/open-source-adoption
- Verify page appears in main navigation under `Company` tab
- Very page on tablet/mobile sizes
WD-23575

feat: create open source adoption page

---

secondary-navigation.yaml

- Added secondary navigation
- View the site locally in your web browser at: https://canonical-com-1908.demos.haus/legal
- Verify the presence of secondary navigation
- Click on nav items and make sure they all work as expected
Fixes #[WD-25054](https://warthogs.atlassian.net/browse/WD-25054)
[WD-25054]: https://warthogs.atlassian.net/browse/WD-25054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-25054] feat: added secondary navigation on /legal bubble

---

webapp/application.py

TS have updated the withdrawal reasons in GH. As such we need to update the reasons shown to candidates in the withdrawal flow on the Candidate Dash, along with the GH reason IDs they map to.
- update withdrawal reasons mapping for candidate dash
- View test candidate Bruno Fernandes' candidate dash locally in your web browser:  http://localhost:8002/careers/application/gAAAAABl2Dcq_kzb-fhHaxzIeu5P8A-wItXtC9nPndSvP3MjHrxwjC0REX-MX53dQq3Tea-3AUGuYNNEtAwPJHcVMhLOgGJRhQ==
- Run through the withdrawal process:
- Ensure the new options show up in the withdrawal form
- Select one, enter email (the email for this candidate is `nathan.clairmonte@canonical.com`), select "Send Email"
- Since the site is in debug mode, you …

Update withdrawal reasons

---

templates/data/_form-data-kafka.html
templates/data/_form-data-mongodb.html
templates/data/_form-data-opensearch.html
templates/data/_form-data-relational-dbs.html
templates/data/_form-data-spark.html
templates/data/_form-data-valkey.html
templates/legal/terms-and-policies/snap-store-terms.md
templates/legal/ubuntu-pro/personal/index.md
templates/maas/contact-us.html

- added updated link to privacy policy
- Visit the  forms on [demo ](https://canonical-com-1910.demos.haus/) and see they point to correct privacy link.
- https://canonical-com-1910.demos.haus/data/kafka
- https://canonical-com-1910.demos.haus/data/mongodb
- https://canonical-com-1910.demos.haus/data/opensearch
- https://canonical-com-1910.demos.haus/data/spark
- https://canonical-com-1910.demos.haus/mass
- Also look for changes in md files.
Fixes # https://warthogs.atlassian.net/browse/WD-26098

Bugfix: added updated link to privacy policy

---

redirects.yaml

- Added redirect for blog tag charmed-aether-sd-core
- Run the site using the command `./run serve` or `dotrun`
- Verify that https://canonical-com-1919.demos.haus/blog/tag/charmed-aether-sd-core redirects to  https://canonical-com-1919.demos.haus/solutions/telco 
Fixes # https://warthogs.atlassian.net/browse/WD-25992

Feat: Added redirect for blog tag

---

secondary-navigation.yaml

-  Updated navigation for /mlops
- See [Demo](https://canonical-com-1922.demos.haus/mlops) and check if it matches
Fixes # https://warthogs.atlassian.net/browse/WD-26149

Feat: Updated navigation for /mlops

---

templates/legal/ubuntu-pro/index.md

- Fixed ubuntu pro URL
- View the site locally in your web browser at: https://canonical-com-1934.demos.haus/legal/ubuntu-pro
- Click the `Ubuntu Pro` links see that they submit, check that [this issue](https://github.com/canonical/canonical.com/issues/1928) is fixed 
Fixes [WD-26366](https://warthogs.atlassian.net/browse/WD-26366)
[WD-26366]: https://warthogs.atlassian.net/browse/WD-26366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: ubuntu pro link

---

templates/openstack/resources.html

- Fixed a failing newsletter form
- View the site locally in your web browser at: https://canonical-com-1946.demos.haus/openstack/resources
- Click on "Sign up for newsletter" button
- Fill the form
- Submit and verify the form goes through sucessfully
Fixes #[WD-26911](https://warthogs.atlassian.net/browse/WD-26911)
[WD-26911]: https://warthogs.atlassian.net/browse/WD-26911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-26911] fix: failing newsletter form

---

templates/projects/index.html

- Removed "Aether project" from [/projects](https://canonical-com-1957.demos.haus/projects) ([Copy doc](https://docs.google.com/document/d/1GTnsk_Fk-ZHJQi--6X2TuaURwUCwnxZQjKdWDFBsaS0/edit?tab=t.0) - [Jira](https://warthogs.atlassian.net/browse/WD-26978))
- Go to [/projects](https://canonical-com-1957.demos.haus/projects)
- Check that "Aether project" is not included anymore in the section about "open source projects we support"
Fixes [WD-26978](https://warthogs.atlassian.net/browse/WD-26978)
[WD-26978]: …

fix(projects): remove aether project [WD-26978]

---

secondary-navigation.yaml
webapp/navigation.py

The secondary navigation resolver matched by prefix first, causing generic parent bubbles (e.g., "/data") to override more specific mappings. Pages that are explicit children of another bubble could be misclassified. This happened because:
1. The algorithm processed bubbles in order and stopped at the first prefix match
2. `/data/lakehouse` starts with `/data`, so it matched the 'data' bubble first
3. It never checked the 'data-and-ai' bubble where these paths are explicitly defined as children
Update get_current_page_bubble to:
- First check for exact child path matches across all bubbles using the normalized path.
- Then fall back to prefix matching if no exact child match is found.
Outcome: 
- /data/lakehouse, /data/streaming → Data & AI bubble
- /solutions/ai → AI bubble
- Go to …

Update logic for bubble nav to match exact child path

---

templates/data/spark/what-is-spark.html

Updated three changes regarding Apache Spark, see copy doc: https://docs.google.com/document/d/1pyX-BOXmIZY6_8imIft1SAp1-S0i8bGYWEo5zoVEgQw/edit?tab=t.0
- See live demo: https://canonical-com-1973.demos.haus/data/spark/what-is-spark
https://warthogs.atlassian.net/browse/WD-27608?actionerId=63bbef0b04b5f5c7b5ecd3cf&sourceType=assign

WD-27608: `/data/spark/what-is-spark` copy updates

---

redirects.yaml

Setup redirects for spark docs
- Check out these URLs and ensure that they redirect to the right docs on readthedocs
- https://canonical-com-1988.demos.haus/data/docs/spark/k8s/t-overview
- https://canonical-com-1988.demos.haus/data/docs/spark/k8s/h-run-on-k8s-pod
- https://canonical-com-1988.demos.haus/data/docs/spark/k8s/r-rev-2
- https://canonical-com-1988.demos.haus/data/docs/spark/k8s/h-use-spark-client-from-python
Fixes # https://warthogs.atlassian.net/browse/WD-27525

docs: add spark k8s docs redirect

---

navigation.yaml

- Removed "cloud native operations report" from meganav
- View demo: https://canonical-com-1992.demos.haus/
- Click on "Products" in the top nav, then click on "Kubernetes" subsection, then ensure that there are only 5 secondary links and that "Cloud native operations report" is not one of them
- Copy doc here: https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit?disco=AAABr6Uiqcg
[WD-29304](https://warthogs.atlassian.net/browse/WD-29304)
[WD-29304]: https://warthogs.atlassian.net/browse/WD-29304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-29304 (remove "cloud native operations report" from meganav)
