canonical/canonical.com

- .circleci/config.yml
- package.json
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/3
QA
--
> Add CircleCI tests; fixup package.json scripts

- README.md
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/1
> Add correct port number

- requirements.txt
- webapp/app.py
Bump flask-base to the latest version
Check the demos works, and that the 404 page works.
> Bump flask-base to 0.3.1

- package.json
- static/sass/styles.scss
- templates/base.html
- templates/index.html
- yarn.lock
Added Vanilla to the project
- Run `./run`
- Visit http://0.0.0.0:8002/
- See that the page has the text "Welcome to Canonical", in Ubuntu font.
> Add vanilla

- static/sass/_pattern_footer.scss
- static/sass/_pattern_icons.scss
- static/sass/styles.scss
- templates/index.html
- webapp/app.py
Build the footer
Added dynamic copyright year
Added dark version of the social icons
- Open http://0.0.0.0:8002/
- Check the footer matches [the design](https://drive.google.com/file/d/114QpYLu8SXvqd_5f8caFOvsrC0TTuSSW/view)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1408
> Footer restyle and build

- static/sass/_pattern_footer.scss
- static/sass/_pattern_icons.scss
- static/sass/_pattern_strip.scss
- static/sass/styles.scss
- templates/base.html
- templates/contact-us.html
- templates/index.html
- templates/partial/_footer.html
- Add `Contact us` page
- Run the site using the command `./run`
- View the site locally in your web browser at: [/contact-us](http://0.0.0.0:8002/contact-us)
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1518)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1518
> 1518 contact us page canonical

- static/sass/_pattern_animations.scss
- static/sass/_pattern_footer.scss
- static/sass/styles.scss
- templates/index.html
- Add home page animations
- Go to [http://0.0.0.0:8002/](http://0.0.0.0:8002/) and make sure there are animations on the page.
- Please test it in multiple browsers.
Fixes #23
> Add home page animations

- static/sass/_pattern_lists.scss
- static/sass/_pattern_strip.scss
- static/sass/styles.scss
- templates/careers/admin.html
- templates/careers/careers_base.html
- templates/careers/commercial-ops.html
- templates/careers/design.html
- templates/careers/engineering.html
- templates/careers/finance.html
- templates/careers/hr.html
- templates/careers/legal.html
- templates/careers/management.html
- templates/careers/marketing.html
- templates/careers/project.html
- templates/careers/sales.html
- templates/careers/tech-ops.html
- templates/contact-us.html
- Add career pages
- Go to [/careers/design](http://0.0.0.0:8002/careers/design) and navigate to all other pages.
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1535)
- Make sure the tab navigation is functional
- Make sure the navigation on the left is functional (note that there are no pages created for lifestyle, ethics, etc.)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1535
> Add careers pages

- templates/index.html
- templates/partners/become-a-partner.html
- Add `/partners/become-a-partner` page
- Go to [/partners/become-a-partner](http://0.0.0.0:8002/partners/become-a-partner) 
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1509)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1509
> 1509 add become a partner page

- static/sass/_pattern_buttons.scss
- static/sass/_pattern_cards.scss
- static/sass/_pattern_strip.scss
- static/sass/styles.scss
- templates/partners/find-a-partner.html
- Add `/partners/find-a-partner` page
- Go to [/partners/find-a-partner](http://0.0.0.0:8002/partners/find-a-partner) 
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1510)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1510
> 1510 Add find-a-partner page

- static/sass/_pattern_cards.scss
- templates/careers/index.html
- templates/index.html
- Add `/careers` page
- Go to [/careers](http://0.0.0.0:8002/careers) 
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1563)
- Make sure all the links are taking you to a page and you don't get any 404s
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1563
> Add main careers page

- templates/careers/careers_base.html
- templates/careers/job-detail.html
- add job details template page
- Check out this branch
- Run `./run`
- Visit http://0.0.0.0:8002/careers/job-detail
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1591)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1591
> Add job details template page

- static/sass/_pattern_careers-modal.scss
- static/sass/styles.scss
- templates/careers/apply.html
- templates/careers/careers_base.html
- templates/partial/_careers-modal.html
- Add careers modal to add/remove jobs you want to apply for
- Go to [/careers/apply](http://0.0.0.0:8002/careers/apply)
- Click on`Add more roles` button and see the modal is displayed
- Click `X` button in the top left corner to close it
https://github.com/canonical-web-and-design/web-squad/issues/1604
> Add careers modal to add/remove jobs you want to apply for

- static/sass/_pattern_cards.scss
- static/sass/_pattern_strip.scss
- templates/careers/travel.html
- templates/partners/kubernetes.html
- Add `/partners/kubernetes` page
- Go to [/partners/kubernetes](http://0.0.0.0:8002/partners/kubernetes) and compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1763)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1763
> Add partners/kubernetes page

- static/sass/_pattern_navigation.scss
- static/sass/styles.scss
- templates/base.html
- templates/partners/become-a-partner.html
- webapp/app.py
- Add basic navigation
- Go to [/partners/find-a-partner](http://0.0.0.0:8002/partners/find-a-partner) and check if the navigation works
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1769
> Implement initial basic navigation

- static/sass/_pattern_media-object.scss
- static/sass/styles.scss
- templates/partial/_partners-footer.html
- templates/partners/index.html
- templates/partners/kubernetes.html
- Add `/partners` page
- Go to [/partners](http://0.0.0.0:8002/partners) and compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1771)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1771
> 1771 build partners page

- templates/partial/_partners-footer.html
- templates/partners/desktop.html
- Add search functionality to `/partners/desktop` page
- Go to [/partners/desktop](http://0.0.0.0:8002/partners/desktop) and search for partners and filter partners 
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1766
> 1766 partners desktop page

- static/sass/styles.scss
- templates/partners/cloud.html
Built the partners/cloud page
- Go to /partners/cloud
- Check the design _sort of_ matches [the design](https://github.com/canonical-web-and-design/web-squad/issues/1764)
- Check the copy matches [the copy doc](https://docs.google.com/document/d/1O3KUX41hwsehnAedYV5Pp4i_aMrKDTGYiri5uR6N9fc/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1764
> Partners cloud

- redirects.yaml
Add redirects from the old pages to the new pages when required
- Check the redirects all work: https://docs.google.com/spreadsheets/d/1X7lmjAYSFbse-_uTiKcQWM-y17KK46WUExrK1C0yx0s/edit#gid=0
Fixes  https://github.com/canonical-web-and-design/canonical.com/issues/59
> Add redirects from the old pages to new

- .circleci/config.yml
Change python tests CircleCI endpoint to match the package.json endpoint
- Make sure in this PR that CircleCI has a job called "test-python"
> Change python tests CircleCI endpoint to match the package.json endpoint

- templates/base.html
- templates/contact-us.html
- Update `/contact-us` page
- Go to http://0.0.0.0:8002/contact-us and compare to [copy doc](https://docs.google.com/document/d/1Qxvhl6_kgCDarcem1wcFPQyHk0JEFUP1zIzNsIrT3_Y/edit#)
Fixes #72
> Update /contact-us page

- templates/careers/all.html
- Update `/careers/all` page
- Compare to [copy doc](https://docs.google.com/document/d/1adoe3jR-_O3EC4LECotKiPo2SsC_Ht5YPTR0wr-BhH0/edit)
Fixes #79
> Update /careers/all page

- templates/careers/project-management.html
- Update `/careers/project-management` page
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/project-management
- Compare to [copy](https://docs.google.com/document/d/1IMXbRXvmvSKe_SrKvEiQIRCwz3I9BfVcQRQuHODaG8s)
Fixes #84
> Update /careers/project-management page

- templates/careers/hr.html
- Update `/careers/hr` page
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/hr
- Compare to [copy doc](https://docs.google.com/document/d/14YcOjgNRr6k4JQCSB-Qs5MxVO-JNd2P-HjxzGFDvZkY/edit)
Fixes #83
> 83 update careers hr

- templates/careers/sales.html
- Update `/careers/sales` pae
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/sales
- Compare to [copy](https://docs.google.com/document/d/1fGBFiIfy7C58UXcJ0Q7q6VKxClxBfPyeWBSyO9GrStI/edit#)
Fixes #85
> Update /careers/sales page

- README.md
Update shield style
QA
--
Look at the readme
> Update circleci shield style

- templates/index.html
Update the home page content
- Check it matched [the copydoc](https://docs.google.com/document/d/1WcNN2RlQQrbLSP5ZgcIsAeQAHj5h_yDW6Yd5oBMmU3M/edit#)
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/77
> Update the home page content

- templates/careers/careers_base.html
- templates/partial/_careers-available-roles.html
- templates/partial/_careers-navigation.html
- Update `/careers/<department>` to match new design
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/marketing
- Compare to [design](https://github.com/canonical-web-and-design/canonical.com/issues/103)
Fixes #103
> Update job list to match new design

- templates/partial/_navigation-products.html
- Update `products` links in the navigation
- Click on `Products` button from navigation
- Check that all links take you to a sensible page
Fixes #73
> Update product links in the navigation

- webapp/greenhouse_api.py
- Update the default job application number
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1958
> Update the default application job number

- Dockerfile
Add Dockerfile to project 
- Run the site using the command `./run build`
- `docker build --build-arg TALISKER_REVISION_ID=test --tag canonical.com .`
- `docker run -ti -p 8004:80 canonical.com`
- http://0.0.0.0:8004
- Make sure site works
> Add dockerfile to project

- static/js/highlight-nav-on-scroll.js
- static/js/navigation.js
- static/sass/_pattern_navigation.scss
- templates/index.html
- templates/partial/_navigation.html
- Made the nav sticky on all pages, updated dropdown windows along with it to make sure they're in the correct position.
- Adjusted width of the Canonical logo.
- On the homepage, added JS to highlight the Products and Careers nav items when the corresponding elements are in view.
- Scroll down to the products and careers section, make sure that the relevant item is highlighted in the nav when you do.
- Go to /careers, scroll down the page and see that the nav is sticky. Open the Products dropdown, and see that it is positioned …
> Nav updates

- redirects.yaml
Add redirect from /index.html
- Go to /index.html in production and see there is an error
- Go there on this branch and see it redirects
> Add redirect from /index.html

- static/js/careers-game.js
- static/sass/_pattern_buttons.scss
- static/sass/_pattern_cards.scss
- templates/careers/_skill.html
- templates/careers/_skills.html
- templates/careers/start.html
- refactored careers-game.js to use vanilla JS
- moved HTML from JS to views
- added "See all available roles" link at bottom of page
- Ensure that the game behaves identically to canonical.com/careers/start
- View the page with JS disabled, see that there is a link that will take you to /careers/all
- In browserstack (or locally if you've got a VM for it), test the page in Edge (or IE11 if you're brave) and check you can get through the game
Fixes #170
> refactor careers game

- README.md
Removed a now-out-of-date remark on the site not being deployed to end users.
N/A. Only the README.md file is modified.
N/A
> README: The site is now live

- README.md
> Add canonical logo to the README

- templates/projects/index.html
Update the links to projects
- Go to /projects
- Check the links all work
> Update the links to projects

- templates/contact-us.html
Fix typo in the UK address.
- Check code.
> Typo in the address

- templates/partners/cloud.html
- Update `/partners/cloud` page
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/cloud
- Compare to [copy doc](https://docs.google.com/document/d/1O3KUX41hwsehnAedYV5Pp4i_aMrKDTGYiri5uR6N9fc)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2564
> Update /partners/cloud page

- templates/careers/job-detail.html
- webapp/greenhouse.py
- Render job application questions from api response
- Check a few job posts from different departments and see they all look good, and all the fields are rendered correctly
- Apply to Ant's job by filling in all the fields `/careers/2095959` and check with him if the application was successfully submitted 
Fixes #202
> Render job application questions from api response

- webapp/greenhouse.py
Check department is not Null before parsing it
- Click on a department and check it works
- Click on available roles and check it works
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/212
> Check department is not Null before parsing it

- Dockerfile
- requirements.txt
- Update talisker v0.18.0
- Update docker image to focal
- `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag canonical.com .`
-  `docker run -ti -p "8006:80" --env SECRET_KEY=secret_key canonical.com`
- http://0.0.0.0:8006/
- Play around with the site and make sure it works well
> Update to focal

- templates/partners/become-a-partner.html
- Update `become a partner` form
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/become-a-partner
- Compare form to [copy](https://docs.google.com/document/d/1fMJsk0n9MH2Pmf0vwHT9vGv0A0oAtFixDJJzHkWOGZU/edit)
- Make sure you select "Other" for `job function` and select "United States of America" for `country` as the form changes 
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2562
> Update become a partner form

- webapp/greenhouse.py
Fix the job listing
- CHeck the careers work
> Fix the job listing

- templates/partners/become-a-partner.html
- Fix html entity on /partners/become-a-partner
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/become-a-partner
- See that the ndash isn't visible
> Fix html entity on /partners/become-a-partner

- templates/partners/become-a-partner.html
Removed a hidden required field
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/become-a-partner
- Fill out the form and see that it submits
> Remove hidden comment field to fix form

- webapp/greenhouse.py
- Replace the cherry-picked data with the entire form_data dict
- This is a difficult one to QA as you need access to an open role to QA in greenhouse. 
- If you would like to QA please ping me and we can pair on the QA
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/310
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/309
> Submit all answers to the job application

- templates/contact-us.html
- Updated Austin address 
- Update [copy doc](https://docs.google.com/document/d/1Qxvhl6_kgCDarcem1wcFPQyHk0JEFUP1zIzNsIrT3_Y/edit#heading=h.cke8gkj487s6)
- View the site locally in your web browser at: http://0.0.0.0:8002/contact
- See that he Austin address is now matching the [wiki](https://sites.google.com/a/canonical.com/operations/business-services/canonical-offices/austin)
Fixes #331
> Update Austin address on /contact

- templates/base_index.html
- templates/careers/job-detail.html
- Add google optomise script to all pages
- Add job submit event on /careers/##### pages
- View the site locally in your web browser at: http://0.0.0.0:8002/careers/2114847
- See that there is an event on the submit button and google optomise is running on the page
Fixes #336
> Add google optomise and job submit event

- .env
- .github/pull_request_template.md
- .github/workflows/pr.yaml
- .prettierignore
- .stylelintrc
- README.md
- package.json
- static/js/apply-for-jobs.js
- static/js/careers-filter-and-sort.js
- static/js/careers-game.js
- static/js/dynamic-image-load.js
- static/js/file-validation.js
- static/js/find-a-partner.js
- static/js/highlight-nav-on-scroll.js
- static/js/modal.js
- static/js/navigation.js
- static/js/tabs.js
- static/sass/_pattern_animations.scss
- static/sass/_pattern_buttons.scss
- static/sass/_pattern_cards.scss
- static/sass/_pattern_footer.scss
- static/sass/_pattern_forms.scss
- static/sass/_pattern_headings.scss
- static/sass/_pattern_navigation.scss
- static/sass/_pattern_strip.scss
- static/sass/styles.scss
- templates/careers/_filters.html
- templates/partners/request-login.html
- yarn.lock
- Update README to include info on API key
- Add Prettier as a dep
- Run Prettier over whole site
- Fix invalid HTML
Note: Due to Prettier, it'll be easier to review code by following commits
- Sanity check code
- Verify all tests and checks pass
> Code cleanup

- templates/careers/job-detail.html
Fixed form submission tracking.
- Job submission forms should trigger a GA event
> Moving onsubmit to the form tag

- static/js/careers-game.js
- templates/careers/job-detail.html
- templates/partial/_careers-job-list.html
- tests/test_greenhouse.py
- webapp/app.py
- webapp/greenhouse.py
QA
==
Thoroughly QA the whole careers section please =) https://canonical-com-358.demos.haus/careers
> Reformat; sort by core-skills

- templates/careers/base_job-details.html
- templates/careers/job-detail.html
Condense the layout of the job details page
- Go to /careers/2383894/vp-cloud-alliances-remote
- See that there is more content above the fold than [on live](https://canonical.com/careers/2383894/vp-cloud-alliances-remote)
- Check it looks ok on small screens
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1413534/112471048-53ac1f80-8d63-11eb-9715-49f15469a545.png) | ![image](https://user-images.githubusercontent.com/1413534/112471462-d92fcf80-8d63-11eb-8a3d-07b7f7e86621.png) |
> Condense the layout of the jod details page

- templates/base_index.html
- templates/careers/job-detail.html
Added an OG image for all job descriptions.
- Go to https://www.opengraph.xyz/url/https:%2F%2Fcanonical.com%2Fcareers%2F2383894%2Fvp-cloud-alliances-remote/
- Check that you recoil in horror
- Go to https://www.opengraph.xyz/url/https:%2F%2Fcanonical-com-372.demos.haus%2Fcareers%2F2383894%2Fvp-cloud-alliances-remote/
- See the beauty  
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/340
> Update meta image

- LICENSE.md
- README.md
Add missing license.md and comment in readme.md
- review changes to the readme.md and the addition of license.md
Fixes #381
> Add missing license.md and comment in readme.md

- Dockerfile
Update docker image from node-slim to node since some node dependencies require python that node slim doens't integrate
make sure demo builds
> Update docker image from node-slim to node

- templates/projects/directory.html
> Update contact details for Launchpad

- static/js/careers-game.js
changed 'choises' to 'choices'.
> Fix minor typo

- templates/partners/iot-device.html
- webapp/app.py
- webapp/partners.py
- Build a new page on `/partners/iot-device`
- Please refer to this [brief](https://docs.google.com/document/d/1vOIffTaJL8LeQVj-kuc1XU9p1-SQFVvQWYZHEjcDKZ8/edit) and [copy doc](https://docs.google.com/document/d/1qNEjihmySR6l6LZJ-SkSVTpaBSxuY8imoseN0OLkiMw/edit#)
Fixes [#4635] (https://github.com/canonical-web-and-design/web-squad/issues/4635)
> Build iot device page on /partners/iot-device

- templates/careers/ethics.html
> Fix ethics typo

- .github/workflows/pr.yaml
Fix github dotrun action
Github dotrun check should pass now
> Fix github dotrun action

- package.json
- tests/cypress/cypress.json
- tests/cypress/integration/sample_spec.js
- tests/cypress/plugins/index.js
- tests/cypress/support/commands.js
- tests/cypress/support/index.js
- yarn.lock
- Install cypress on canonical.com
- Setup a single test to access the homepage and accept the cookie policy
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4588
> Setup cypress

- templates/contact-us.html
Update the address of Canonical in London and the map link
- Go to /contact-us
- Click "Where we are"
- See the new address
> Update the address of Canonical in London

- static/sass/_pattern_footer.scss
- static/sass/_pattern_strip.scss
- templates/blog/article.html
- templates/blog/newsletter-form.html
- templates/press-centre/card.html
- templates/press-centre/index.html
- webapp/app.py
Canonical press centre and news section only.
Canonical press is a collection of news, resources, events etc... [See miro board](https://miro.com/app/board/o9J_luilNcw=/). Currently we only have data for news section.
- Check https://canonical-com-502.demos.haus/press-centre
- ~~check https://canonical-com-502.demos.haus/press-centre/news~~ (Reverted back to old ubuntu.com/blog/press-centre design, so no news page)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4874
> Canonical press centre

- templates/partners/isv-partners.html
- Updated copy as per [copy doc](https://docs.google.com/document/d/1qWWpFbwZykjAIt-Kf6iFCXPCnmmuKBbU5mzvILnO-q0/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8002/partners/isv-partners
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5069
> Update copy on /partners/isv-partners

- templates/contact-us.html
- Check the http://localhost:8002/contact-us and click "Where we are" to see the new address and the link to the google map.
Fixes #518
> Update the address of Taipei Office

- templates/projects/directory.html
Replaced myself with @clagom as the active contract for the Vanilla framework project.
- Check the code.
> Update the contract for the Vanilla framework project

- static/sass/_pattern_cards.scss
- templates/partners/desktop.html
**note: the design differs from the [copydoc](https://docs.google.com/document/d/1MBVH4kou0Q7yO_Lq6DPQpZL_rc0K1-nVfvg4aF3biSc/edit#) a little**
- Updates /partners/desktop with the new style of canonial-v3, see [design](https://app.zeplin.io/project/624ed20e0af92866116ea26d/screen/625418364f034e676f297348)
- Adds a `p-card.has-cta` class 
- Compare against design
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5154
> Update /partners/desktop for canonical-v3

- static/sass/_pattern_cards.scss
- templates/partial/_partners-footer.html
- templates/partners/ihv-and-oem.html
Refresh /partners/ihv-and-oem for canonical-v3 to match the [design](https://app.zeplin.io/project/624ed20e0af92866116ea26d/screen/6254183fc6e0f56cbfad4094) and [copydoc](https://docs.google.com/document/d/1p8Et43R14AGiFn9g7ro9VLXZh26gph9Kk5K6_lc8W8U)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5157
> Refresh /partners/ihv-and-oem for canonical-v3

- static/sass/_pattern_cards.scss
- templates/partners/iot-device.html
- Refresh /partners/iot-device for canonical-v3, see [design](https://app.zeplin.io/project/624ed20e0af92866116ea26d/screen/6254183bf20adf6e2dfda669) and [copydoc](https://docs.google.com/document/d/1qNEjihmySR6l6LZJ-SkSVTpaBSxuY8imoseN0OLkiMw/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5156
> Refresh /partners/iot-device for canonical-v3

- templates/practice/documentation.html
Update documentation careers page
- Go to https://canonical-com-537.demos.haus/practice/documentation and check changes against [copy docs](https://docs.google.com/document/d/10tOsj5kKZRddQYYkb1PgxsES47Qic8XJc9xpRaYHd7s/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues
> Update practices documentation

- templates/partners/find-a-partner.html
**Note: I could not find a copydoc for this page**
- Refresh /partners/find-a-partner for canonical-v3 based on [design](https://app.zeplin.io/project/624ed20e0af92866116ea26d/screen/626914ccc85e8501cb62fe69)
- Compare against design
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5196
> Refresh /partners/find-a-partner for canonical-v3

- templates/practice/documentation.html
Update navigation name from "How do we work" to "How we work"
- Check https://canonical-com-539.demos.haus/practice/documentation against [copy docs](https://docs.google.com/document/d/10tOsj5kKZRddQYYkb1PgxsES47Qic8XJc9xpRaYHd7s/edit#heading=h.zic51zh7uz4b) changes
Fixes
> Update documentation careers page

- static/js/tabs.js
- static/sass/_pattern_cards.scss
- static/sass/_pattern_lists.scss
- static/sass/_settings.scss
- static/sass/styles.scss
- templates/careers/_filters.html
- templates/careers/base-tabs.html
- templates/careers/base-template.html
- templates/careers/results.html
- templates/partial/_careers-available-roles.html
- templates/partial/_careers-navigation.html
- templates/practice/documentation.html
The page includes a lot of includes and custom styling, thus there are many small changes in different files.
https://canonical-com-540.demos.haus/careers/engineering
- Compare against [design](https://app.zeplin.io/project/624ed20e0af92866116ea26d/screen/6254185cda83636adde7b435)
- Check all functionality works as expected, can compare against the [live site](https://canonical.com/careers/engineering)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5152
> Update /careers job view for canonical-v3

- templates/partial/_partners-footer.html
- templates/partners/become-a-partner.html
**Note: contact us form will stay the same until head of channels has looked, see [doc](https://docs.google.com/document/d/1fMJsk0n9MH2Pmf0vwHT9vGv0A0oAtFixDJJzHkWOGZU/edit)**
- Refresh /partners/become-a-partner for canonical-v3 based on [design](https://app.zeplin.io/project/624ed20e0af92866116ea26d/screen/626914c7bc6117023aa2b074) and [copydoc](https://docs.google.com/document/d/1Ihh9s3i72saCYaheXRVRn1Meg5lYN5U1gFbdvLMdWcc/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5195
> Refresh /partners/become-a-partner for canonical-v3

- templates/partners/public-cloud.html
Refresh /partners/public-cloud for canonical-v3 based on [design](https://app.zeplin.io/project/624ed20e0af92866116ea26d/screen/6254184ce015d56be0911995) and [copydoc](https://docs.google.com/document/d/1O3KUX41hwsehnAedYV5Pp4i_aMrKDTGYiri5uR6N9fc/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5159
> Refresh /partners/public-cloud for canonical-v3

- static/sass/_pattern_cards.scss
- static/sass/_utilities_accent-border.scss
- templates/careers/working-here.html
- templates/partners/desktop.html
- templates/partners/ihv-and-oem.html
- Create /working-here page
https://canonical-com-541.demos.haus/careers/working-here
- Compare against [design](https://app.zeplin.io/project/624ed20e0af92866116ea26d/screen/625ff2e26832b9166c99aa34)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5153
> Create /working-here page

- static/sass/_pattern_cards.scss
- templates/careers/apply.html
- templates/partners/become-a-partner.html
- templates/partners/channel-and-reseller.html
- templates/partners/desktop.html
- templates/partners/find-a-partner.html
- templates/partners/gsi.html
- templates/partners/ihv-and-oem.html
- templates/partners/iot-device.html
- templates/partners/public-cloud.html
Updates with the design suggestions found [here](https://app.zenhub.com/workspaces/-web-tribe-5931746dba512f05402b61f6/issues/canonical-web-and-design/web-squad/5193)
- Check all the suggestions have been implemented
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5193
> Update with design suggestions

- static/sass/_pattern_cards.scss
- static/sass/_pattern_tabs.scss
- static/sass/styles.scss
- templates/index.html
Added a build of the homepage with the content we currently have.
- Compare to the design: https://app.zeplin.io/project/624ed20e0af92866116ea26d/screen/62541827c1ca0a6779674062
- I've omitted the testimonial section until I can get some design advice from Spencer, and I don't have images to place into the page yet.
> Demo: homepage

- static/sass/styles.scss
Remove light from the strong styling
> Remove light strong font

- static/js/careers-filter-and-sort.js
- templates/base_index.html
- templates/careers/_search.html
- templates/careers/base-tabs.html
- templates/careers/base.html
- templates/partial/_careers-available-roles.html
- tests/test_routes.py
- webapp/greenhouse.py
- Display search resultㄴ after pressing enter.
- Filter and sort search results. 
- Go to  https://canonical-com-575.demos.haus/careers/all
- e.g. Search "cloud" and press enter
- Check the job list displays properly 
- Check filter and sort works with the search result
Fixes #[5701](https://github.com/canonical-web-and-design/web-squad/issues/5701)
> Display search result

- konf/site.yaml
- static/sass/_pattern_blog-card.scss
Fix card double border issue, as described in https://github.com/canonical-web-and-design/canonical.com/issues/571
- Check https://canonical-com-592.demos.haus/blog doesn't have the double border anymore.
Before:
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/571
> Fix card border

- static/sass/_pattern_application.scss
- static/sass/styles.scss
- templates/careers/application/_withdrawal-form.html
Implement design on modal 
- Go to https://canonical-com-616.demos.haus/careers/application/token (Please ping me for token) 
- Click application withdrawal button.
- [Miro](https://miro.com/app/board/uXjVO9E_QFA=/?share_link_id=997105033759) for UX
- [Figma](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?node-id=5742%3A10933) for design
- [Copy doc](https://docs.google.com/document/d/1RZXj-LH_7Eg-pWJR9tE_V3D5CSDzCzyhyn0WoHLZwpQ/edit)
Fixes #614
> Implement design modal

- webapp/greenhouse.py
Send candidates rejection confirmation emails after they self reject their applications
- Go to https://canonical-com-622.demos.haus//careers/application/token (please ping me for tokens) 
- Click `Withdraw application` button, fill in the form and withdraw application and check if you get a confirmation email.
Fixes #618
> Send rejection confirmation email

- webapp/application.py
- fix missing candidate object on application page
- _Please ask me for a failing application page link_
- Make sure that the page isn't broken
> Fix missing candidate object on application page

- templates/careers/application/index.html
- templates/careers/application/partial/_assessment.html
**This PR addresses 2 issues**
- Update copy based on [copydoc](https://docs.google.com/document/d/1RZXj-LH_7Eg-pWJR9tE_V3D5CSDzCzyhyn0WoHLZwpQ/edit#heading=h.pmojv69jw2s7)
- Add 'How we hire at Canonical' video, see [issue](https://github.com/canonical/canonical.com/issues/649)
- Go to /careers/application
- Check the application matches the copydoc
- Check the video is correct and loads
Fixes https://github.com/canonical/canonical.com/issues/649
https://github.com/canonical/canonical.com/issues/642
> Update copy & include video on /application

- webapp/application.py
Reordered the conditionals to prevent keyErrors when `rejection_type` is None
- Ask me for a URL to a hired application
- Load it and check it works
- Check it doesn't in production
> Fix access to the hired view on application page

- templates/contact-us.html
> Please note that you may need to update copyright notices to:
Canonical Limited, Registered in Isle of Man, Company number 110334C
Registered Office:  2nd Floor, Clarendon House, Victoria Street, Douglas IM1 2LN, Isle of Man
- Update the registered address across the website
> Update the company address across the site

- static/js/navigation.js
- static/sass/styles.scss
- templates/base_index.html
- templates/index.html
- templates/partial/_navigation.html
- templates/partners/channel-and-reseller.html
- templates/partners/find-a-partner.html
- templates/partners/ihv-and-oem.html
- templates/partners/public-cloud.html
Update navigation to new vanilla pattern & new items based on the items listed in [the issue](https://github.com/canonical/web-squad/issues/6054) and [the wireframe](https://miro.com/app/board/o9J_luilNcw=/?moveToWidget=3458764526315426035&cot=14)
Based off of this design:
- Go to https://canonical-com-650.demos.haus/
- Check the design matches the [new vanilla pattern](https://vanillaframework.io/docs/patterns/navigation)
- Check all the items listed in [the issue](https://github.com/canonical/web-squad/issues/6054) are present
Fixes https://github.com/canonical/web-squad/issues/6054
> Update navigation to new vanilla pattern with new items

- templates/partial/_navigation.html
Updated the nav banner with the correct asset
- Visit /
- See that the nav uses the correct Canonical asset
> update nav banner

- static/sass/_pattern_application.scss
Fix the stepper styling
- Check application page stepper looks better
Before: 
After:
> Fix the stepper styling

- templates/careers/application/index.html
- webapp/application.py
- webapp/greenhouse.py
Render job post title instead of job title on the application page
- Open the demo and [use this link](https://pastebin.canonical.com/p/J3GpTM3n5H/) to find an example
- Check the title in the hero is correct
> Render job post title instead of job title in application page

- templates/careers/application/index.html
Remove the offer stage from the application view as its confusing
- View the page in [this link](https://pastebin.canonical.com/p/mhCMrMNdPF/) to see the stage has been removed
> Remove the offer stage from the application view

- static/js/navigation.js
- static/sass/_pattern_application.scss
- templates/partial/_navigation.html
- Adds GA tracking to navigation
- Run the project and check that GA tracking is working by using an extension such as 'tag assistant'
> Add Ga tracking to navigation

- tests/test_application.py
- webapp/application.py
- Instead of only getting the current milestone based on the current, this PR aims to look for the all the previous stages in case the latest stage isn't recognized by the app
- Make sure that the application page is still working for different candidates
> Get the current milestone based on the historical list of stages

- webapp/application.py
- Handle the case where there are multiple stages with the same name
- Make sure that the application page is working
> fix the case where there are multiple hold stages

- .github/workflows/pr.yaml
- webapp/greenhouse.py
Go to /careers in the demo. Search for something. See that it works, no errors.
> Fix departments to handle new response format from API

- templates/careers/application/index.html
- Check this application: https://pastebin.canonical.com/p/2TBrXbfgb4/
- Check production and see the error
Fixes https://sentry.is.canonical.com/canonical/canonical-com/issues/30312/?query=is%3Aunresolved
> Fix when a job is not available in an application

- templates/careers/application/index.html
Check the HL image exists before rendering an img
- Open the demo 
- Visit the application page [here](https://pastebin.canonical.com/p/NZSTf8f4MB/)
- See that the HL image is not rendered
- Go to production and see the broken image
> Check the HL image exists before rendering an img

- templates/401.html
- webapp/app.py
- webapp/application.py
- webapp/utils/cipher.py
Show 401 error page when /careers/application token missing or wrong.
Fixes #755
QA
--
Go to https://canonical-com-756.demos.haus/careers/application and https://canonical-com-756.demos.haus/careers/application/made-up-token, see a lovely 401 error page.
> Show 401 error page when /careers/application token missing or wrong

- static/sass/_pattern_footer.scss
- static/sass/styles.scss
- templates/partial/_footer.html
- Updated footer as per [design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?node-id=6990%3A16546)
- View the site locally in your web browser at: https://canonical-com-763.demos.haus/
- Scroll to the bottom of any page and see that the footer matches the proposed design
- Check that links work as expected
Fixes https://warthogs.atlassian.net/browse/WD-1004
> Update footer format

- templates/careers/application/faq.html
Updates based on the requests in [the copy doc](https://docs.google.com/document/d/12_O_QtPqfv9p7kaDFdiP8Xq-kY5xa1XB-C-CRbXjDew/edit#)
- Check the code changes match the copy doc above
> WD-1787 Updates to the application FAQ content

- templates/contact-us.html
- Updated as per [copy doc](https://docs.google.com/document/d/1Qxvhl6_kgCDarcem1wcFPQyHk0JEFUP1zIzNsIrT3_Y/edit#heading=h.x34oyagq7emg)
- View the site locally in your web browser at: http://0.0.0.0:8002/contact-us
- 
Fixes https://warthogs.atlassian.net/browse/WD-1702
> Update address copy on /contact-us

- templates/careers/engineering.html
- templates/careers/finance.html
- templates/careers/people.html
- templates/careers/project-management.html
- templates/careers/web-and-design.html
- Updated copy as per:
- [engineering doc](https://docs.google.com/document/d/12GWF6eVKezvENc66p3QZ5ZEO8H2QBIlU56RPZNdCPdI/edit)
- [finance doc](https://docs.google.com/document/d/1e6A3z1KsVNyShx2mHq3lNrYkXCaHy8x8BA7qzLxeuJ4/edit)
- [people doc](https://docs.google.com/document/d/1sj-WToRUa9N2c5brs8iAoOfOPHJCeHwvHByq8qcSgK4/edit#heading=h.5x9fs59miplh)
- [proj. management doc](https://docs.google.com/document/d/1hc5olKZcPIHFtxYAHvYFS_c-NZIYy3ZT8WqG7r021MI/edit)
- [web & design doc](https://docs.google.com/document/d/1Eq3USN12tdL1sEf0DMYxO9FAJ5Vqkrl_yeYdRsfWNww/)
- View the site locally in your web browser at: 
- https://canonical-com-777.demos.haus/careers/engineering
- …
> Update copy for selected department pages

- templates/careers/application/faq.html
- Update the applicaiton FAQ content to match the [copy doc](https://docs.google.com/document/d/12_O_QtPqfv9p7kaDFdiP8Xq-kY5xa1XB-C-CRbXjDew/edit#)
- Open the demo and visit /careers/application/faq and check it works
- Check the content matches the copy doc above.
> WD-1537 Update the application FAQ content

- templates/careers/legal.html
- Update the legal page content to match the [copy doc](https://docs.google.com/document/d/1TcKYSlfV2G9X_0l-T6rZ-CWd_XJQ_4hHQCPL2CVrCts/edit#).
- Open the demo and visit /careers/legal
- Check the content matches the copy doc above
> WD-1521 Update the legal content

- templates/careers/support-engineering.html
- Update the Support engineering copy to match the [copy doc](https://docs.google.com/document/d/1TkePZPzjdIMRTPIep6C1f8SnTPmkKiGdMyUEPMK9rH8/edit#).
- Open the demo and visit /careers/support-engineering
- Check the copy matches the copy doc above.
> WD-1534 Update support engineering copy

- templates/careers/sales.html
- Updated the copy for the Sales page to match the [copt doc](https://docs.google.com/document/d/1yCukmqr7do6iJgl6hKui9lAslWJ6Gol4O2E5ctCE7PY/edit#)
- Open the demo and visit /careers/sales
- Check the content matches the copy docs above
> WD-1533 Update Sales copy

- templates/careers/marketing.html
- Update the copy of the Marketing page to match the [copy doc](https://docs.google.com/document/d/1larR0nWbVEqeUQbIJdgWemr7I6cqzoUhA9MD6sRQZwE/edit#)
- Open the demo and visit /careers/marketing
- Check the copy matches the copy doc above
> WD-1522 Update Marketing copy

- templates/documentation/work-and-careers.html
Simple copy update to match the [copy doc](https://docs.google.com/document/d/1U-IkZOMzQlfV0zAAmM0PRVUBoZNBeOa-Qrso3i4rDVU/edit#)
- Check the code matches the suggestion
> Update to /documentation/working-and-careers

- templates/careers/administration.html
- Updated the administration copy to match the [copy doc](https://docs.google.com/document/d/1Kfkdy1rwBUP1L-ToUVvgqv8WkwEa8SurILkwJJh8u0U/edit#).
- Open the demo and go to /careers/administration
- Check the copy matches
> WD-1517 Update the Administration copy

- static/sass/_pattern_cards.scss
- templates/careers/base_job-details.html
- templates/careers/job-detail.html
- Centrally align the application form
- Make the job title sticky on the job description
- Improved the JS code when navigating around
- Setup load handling, so refreshing the application page renders the application form
- Auto-focus on the first input of the form when showing it
1. Open the demo and navigation to a job
2. Scroll down on the job description page and see the title follows you
3. Check the behaviour of smaller screens
4. Click "Apply" and see that form appears and the URL is correct
5. Check the first input is auto focused
6. Navigate back to the description and see that behaviors as expected
7. Refresh and navigate in different places to see things continue to work
| Job Description | Applicaiton page |
| --- | --- |
| …
> WD-2112 Centrally align the application form

- templates/careers/base_job-details.html
Fix some cosmetic styling like borders, padding, spacing
Fixes #
> WD-2112 Small fixes on top of https://github.com/canonical/canonical.com/pull/799

- webapp/app.py
- Remove hardcoded domain since greenhouse now should take care of spam
Fixes #437
> Remove hardcoded qq.com

- templates/careers/application/_interview-card.html
Show the Google Meet link for interviews today
- Open the demo and go to this URL: https://pastebin.canonical.com/p/96mkR9mHGY/
- Check you can see the Meet link for the interview today
Fixes https://github.com/canonical/canonical.com/issues/821
> Show the Google Meet link for interviews today

- static/sass/styles.scss
- templates/careers/company-culture.html
- templates/partial/_navigation.html
- tests/test_routes.py
- webapp/app.py
Build culture a.k.a company-culture
- Check https://canonical-com-832.demos.haus/careers/company-culture with [design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?node-id=7794-19900&t=JpE73eNhcYSLeFv2-0)
- Compare with [copy doc](https://docs.google.com/document/d/1PAeP_ZO4JzSBCi-fRp6F7SYtSSRY-4DcWLUf9HJaMxs/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-178?atlOrigin=eyJpIjoiYWM4YTE2MWU2NjhmNGMwY2IyYTViNzdkZDgxM2I5YzMiLCJwIjoiaiJ9
> Build culture page

- templates/projects/index.html
Tiny change fixing an out of date reference to Ubuntu Advantage
> Advantage->Pro

- static/sass/styles.scss
- templates/partial/_partners-footer.html
- templates/partners/index.html
- Update login position on /partners
Fixes #
> Update login position on /partners

- package.json
- static/sass/_pattern_blog-card.scss
- static/sass/_pattern_careers-progression.scss
- yarn.lock
- Updates to vanilla-4.0-alpha
- Check that nothing is broken by upgrading to vanilla-4.0
> Update to vanilla-4.0-alpha

- static/sass/styles.scss
- templates/index.html
- webapp/app.py
- webapp/static_data.py
Fixes #
Header images on the homepage are not centred. Additionally, the link doesn't allow clicking the whole image / or header as a good practice. 
Additionally, some code clean up
Before: (see spacing below the logos)
After:
> 🤓 [homepage] featured products header alignment 

- templates/careers/application/faq.html
Added questions and answer to the application FAQ page regarding "I have submitted my written interview. When can I expect to receive the psychometric link and instructions?"
1. Open the demo and go to /application/faq
2. Check the new questions and answers are correct from [the copy doc](https://docs.google.com/document/d/12_O_QtPqfv9p7kaDFdiP8Xq-kY5xa1XB-C-CRbXjDew/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-3653
> WD-3653 Add Q and A for written interview feedback

- templates/careers/application/faq.html
Updated the content for candidates that want there feedback documents.
- Check the content changed matches the [copy doc](https://docs.google.com/document/d/12_O_QtPqfv9p7kaDFdiP8Xq-kY5xa1XB-C-CRbXjDew/edit?usp=drivesdk)
> Update the candidate feedback reports on FAQ

- static/js/careers-filter-and-sort.js
- static/sass/_pattern_search-panel.scss
- static/sass/_pattern_strip.scss
- static/sass/styles.scss
- templates/base_index.html
- templates/careers/_search.html
- templates/careers/index.html
- templates/partial/_footer.html
Update careers landing page
- Compare https://canonical-com-855.demos.haus/careers with [new design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&t=1cBL9pvtHEGK9o5K-0#447244940)
- Compare https://canonical-com-855.demos.haus/careers with [new content]()
> WD-3257 Update careers landing

- templates/careers/company-culture.html
- Update employee count on `/careers/company-culture`
- Check out the [demo here](https://canonical-com-890.demos.haus/careers/company-culture) and compare it with the update requested on the [copy doc](https://docs.google.com/document/d/1PAeP_ZO4JzSBCi-fRp6F7SYtSSRY-4DcWLUf9HJaMxs/edit#)
- [WD-4529](https://warthogs.atlassian.net/browse/WD-4529)
[WD-4529]: https://warthogs.atlassian.net/browse/WD-4529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [copy update] WD-4529 update employee count

- templates/partial/_partners-footer.html
- templates/partners/index.html
Update [/partners](https://canonical-com-886.demos.haus/partners) according to [the design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=9304-19545&t=dgFWASJMMzGbPoda-0)
Updated the markup to use the new brochure site components
- Check [/partners](https://canonical-com-886.demos.haus/partners) against [the design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=9304-19545&t=dgFWASJMMzGbPoda-0)
- Make sure that the brochure site components are used correctly
Fixes WD-4294
> Udpate /partners

- templates/partners/public-cloud.html
- Applied redesign as per [mock-up](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=9441-22394&t=xdbcdCibsjrniJS0-0)
- View the site locally in your web browser at: https://canonical-com-896.demos.haus/partners/public-cloud
- See that the page matches design 
Fixes https://warthogs.atlassian.net/browse/WD-3744
> Redesign /partners/public-cloud

- templates/partners/iot-device.html
- Applied redesign as per [mock-up](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=8687-24645&t=NcEDX6Dr5rSrJruV-0) 
- View the site locally in your web browser at: https://canonical-com-897.demos.haus/partners/iot-device
- See that the pages matches design
Fixes https://warthogs.atlassian.net/browse/WD-3741
> Redesign /partners/iot-device

- templates/careers/company-culture/diversity.html
Update diversity content to match the request in [the copy doc](https://docs.google.com/document/d/1l1UGJToc0ErHUMN9W8hELvF5sDyVRO7N0xDzncqA2SQ/edit?usp=drivesdk)
Fixes https://warthogs.atlassian.net/browse/WD-4752
> WD-4752 - Update diversity content

- templates/careers/company-culture.html
Fix typo on the company culture page
Fixes https://warthogs.atlassian.net/browse/WD-4751
> WD-4751 - Fix typo on the company culture page

- templates/partners/become-a-partner.html
https://sentry.is.canonical.com/canonical/ubuntu-com/issues/29389
> fix marketo payload fields

- templates/projects/directory.html
- templates/projects/index.html
Remove Bazaar from products pages
Fixes https://warthogs.atlassian.net/browse/WD-4817
> WD-4817 - Remove Bazaar from products

- templates/base_index.html
- templates/contact-us.html
Rebuild Contact us as per the [design](https://warthogs.atlassian.net/browse/WD-3811)
- QA according to the new design. 
Fixes #
> Wd 3811 dev canonical com contact us

- templates/press-centre/card.html
- templates/press-centre/index.html
- templates/shared/_pagination.html
Implement the new press page based on this copydoc https://docs.google.com/document/d/1d1Xi5KyHEYMdHCRNLKIxMrzKoQlqXS8mebkkYPRJJTU/edit
- View the site locally in your web browser at: https://canonical-com-916.demos.haus/press-centre
- QA, refer to the copy doc for punctuation and wording.
Fixes #
> Wd 3736 dev canonical com press centre

- templates/base_index.html
Reverts canonical/canonical.com#925
> Revert "Update favicons, take 2"

- static/sass/styles.scss
- templates/base_index.html
- templates/careers/engineering.html
- templates/shared/_engineering-fast-track.html
Update design, add fast-track roles
- Compare https://canonical-com-860.demos.haus/careers/engineering with [design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=8688-27304&t=IpNj91thUplG2ShT-0) and [copy docs](https://docs.google.com/document/d/12GWF6eVKezvENc66p3QZ5ZEO8H2QBIlU56RPZNdCPdI/edit#heading=h.5x9fs59miplh
)
> Update careers engineering fast track with new design

- .stylelintrc
- static/js/tabbed-content.js
- static/sass/_pattern_footer.scss
- static/sass/_pattern_lists.scss
- static/sass/_pattern_tabs.scss
- static/sass/styles.scss
- templates/base_index.html
- templates/careers/index.html
- templates/index.html
- templates/partial/_footer.html
- templates/partial/_navigation.html
- yarn.lock
- Added tabbed content script. We already had one that handled tab functionality for navigation tabs, but not for [content tabs](https://vanillaframework.io/docs/patterns/tabs#content). I pulled this script from what we have on u.com with slight modifications 
- Updated homepage copy as per [doc](https://docs.google.com/document/d/1GNa1FaTkARdrVwYgHXf5H-6sqOLjkJENDistDDcsi4o/edit)
- Applied new styling
- Open the [demo](https://canonical-com-898.demos.haus/) and check against doc
- Check CTAs and tab functionality
- Check medium/mobile screen styles
Fixes https://warthogs.atlassian.net/browse/WD-3734
Almost complete, two notes:
> canonical.com homepage

- templates/press-centre/index.html
Fixes https://warthogs.atlassian.net/browse/WD-4979
- Check copy against the [design ](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?type=design&node-id=9730%3A24826&mode=design&t=8WBAFdj8N5sbO9r3-1)
Fixes #
> Wd 4979 update copy in the press center page

- webapp/app.py
Exclude blog posts with the tags lang:kr (4491) and lang:cm (3599)
- Open the demo 
- Go to the blog
- Check there are no Korean posts at the top
- Compare with production
Fixes https://warthogs.atlassian.net/browse/WD-5006
> WD-5006 - Exclude blog posts with the tags lang:kr and lang:cm

- static/sass/styles.scss
- templates/partners/thank-you.html
- templates/projects/index.html
- Updated /projects copy as per ticket
- Updated /partners/thank-you copy as per ticket
- View the site locally in your web browser at: https://canonical-com-942.demos.haus/projects
- See that requested changes were made
- View the site locally in your web browser at: https://canonical-com-942.demos.haus/partners/thank-you
- See that requested change was made
Fixes https://warthogs.atlassian.net/browse/WD-5025
> Apply copy updates

- templates/partners/index.html
- Updated copy as per ticket
- View the site locally in your web browser at: https://canonical-com-955.demos.haus/partners
- See that the copy was updated
Fixes https://warthogs.atlassian.net/browse/WD-5060
> Partner changes

- templates/press-centre/index.html
- Updated headings as per ticket
- Don't think it's needed here, since there should be no changes visually
Fixes https://warthogs.atlassian.net/browse/WD-5029
> Update /press-centre headings

- static/js/navigation.js
- static/sass/styles.scss
- templates/index.html
- templates/partial/_navigation.html
- Added fade functionality when nav item is open
- Added /projects to company bubble
- Reinstated products link in nav
- View the site locally in your web browser at: https://canonical-com-953.demos.haus/
Fixes # https://warthogs.atlassian.net/browse/WD-4977
> Apply nav updates

- templates/partial/_footer.html
- Added top padding to list  to match p tag top padding 
- View the site locally in your web browser at: https://canonical-com-958.demos.haus/
- See that the requested change has bee made 
Fixes https://warthogs.atlassian.net/browse/WD-5076
> Update footer link list padding

- templates/documentation/work-and-careers.html
- Add spacing as requested in ticket 
- View the site locally in your web browser at: https://canonical-com-961.demos.haus/documentation/work-and-careers
- See that the requested changes were made
Fixes https://warthogs.atlassian.net/browse/WD-5080
> Add spacing to author names

- static/sass/styles.scss
- templates/partners/ihv-and-oem.html
- templates/partners/iot-device.html
- Update laptop images on /partners/iot-device and /partners/ihv-and-oem as per linked tickets
- View the site locally in your web browser at: https://canonical-com-960.demos.haus/partners/iot-device and https://canonical-com-960.demos.haus/ihv-and-oem
- See that requested changes were made 
Fixes https://warthogs.atlassian.net/browse/WD-5077 , https://warthogs.atlassian.net/browse/WD-5078
> Update partner images

- templates/index.html
- Replaced watermarked image for telco tab
- View the site locally in your web browser at: https://canonical-com-962.demos.haus/
- See that the change has been made
> Update tab img

- templates/base_index.html
Update the theme color to #262626
- Load the demo on a phone and see the chrome of the browser is no longer aubergine
> Update the theme color to #262626

- templates/index.html
- Fixed typo as per ticket
- View the site locally in your web browser at: https://canonical-com-971.demos.haus/
- See that the change was made
Fixes https://warthogs.atlassian.net/browse/WD-5160
> Fix MicroK8s typo

- templates/index.html
The `<br>` is hidden on small screens and so needs a space.
- Check on homepage on small screen and see a space between the words
Fixes https://warthogs.atlassian.net/browse/WD-5154
> WD-5154 - Add space between words on small screens

- templates/blog/article.html
- Fixed double body class declaration which was casing a template assertion error
- View the site locally in your web browser at: https://canonical-com-983.demos.haus/blog
- Check various blogs and see that there are no issues
Fixes https://warthogs.atlassian.net/browse/WD-5195
> Fix double body class declaration

- templates/careers/company-culture/diversity.html
- templates/careers/company-culture/progression.html
- templates/careers/company-culture/remote-work.html
- templates/careers/company-culture/sustainability.html
Address [copy updates](https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932?modal=detail&selectedIssue=WD-5254)
- Compare https://canonical-com-988.demos.haus/careers/company-culture/sustainability with [copy doc](https://docs.google.com/document/d/1wwSOXczrGS45e1DiXbt4GMsHKolniRlywxV_CNHHdCA/edit)
- Compare https://canonical-com-988.demos.hauscareers/company-culture/remote-work with [copy doc](https://docs.google.com/document/d/1wwSOXczrGS45e1DiXbt4GMsHKolniRlywxV_CNHHdCA/edit)
- Compare https://canonical-com-988.demos.haus/careers/company-culture/progression with [copy doc](https://docs.google.com/document/d/1wwSOXczrGS45e1DiXbt4GMsHKolniRlywxV_CNHHdCA/edit)
- Compare https://canonical-com-988.demos.haus/careers/company-culture/diversity with [copy …
> WD-5254  Careers copy updates

- templates/careers/company-culture/index.html
- Updated copy as per [doc](https://docs.google.com/document/d/1PAeP_ZO4JzSBCi-fRp6F7SYtSSRY-4DcWLUf9HJaMxs/edit)
- View the site locally in your web browser at: https://canonical-com-991.demos.haus/careers/company-culture
- See that copy changes were made
- Check different screen sizes to ensure there are no orphans in the text 
Fixes https://warthogs.atlassian.net/browse/WD-4811
> Update /company-culture copy

- templates/blog/index.html
- Limited newsletter sign-up form to the first page
- View the site locally in your web browser at: https://canonical-com-994.demos.haus/blog
- See that the newsletter sign-up form only shows on the first page
Fixes https://warthogs.atlassian.net/browse/WD-5395
> Limit newsletter to first page only

- templates/_error.tmpl
- templates/base_index.html
- Fix footer position on pages with low amount of content 
- View the site locally in your web browser at: https://canonical-com-993.demos.haus/notrealpage
- See that the footer sticks correctly to the bottom
Fixes https://warthogs.atlassian.net/browse/WD-5173
> Fix footer

- templates/partners/find-a-partner.html
- templates/partners/index.html
- templates/press-centre/index.html
- templates/projects/directory.html
Update copy update links on 4 pages on c.com
- Check out the demo here.
- Confirm the copy update link on https://canonical-com-1002.demos.haus/partners matches with https://docs.google.com/document/d/1q6dkqQ0zcshrfOmdJA_bAip73EaMSEyXAn8bAD7GqNw/edit
- Confirm the copy update link on https://canonical-com-1002.demos.haus/find-a-partner matches with https://docs.google.com/document/d/1R3s-aiSrFvbNrHjdfblYo_XX1f_EQ989DkmPS41seZc/edit?usp=sharing
- Confirm the copy update link on https://canonical-com-1002.demos.haus/projects/directory matches with https://docs.google.com/document/d/12i56tfefIWBqyXVZA4ENEBVAkPEDA_vkejavN-Eny8I/edit?usp=sharing
- Confirm the copy update link on https://canonical-com-1002.demos.haus/press-centre matches with …
> [copy update] WD-5487 Update copy doc links on 4 pages

- templates/blog/article.html
Update logo for blogs
- Check https://canonical-com-1017.demos.haus/blog/optimised-real-time-ubuntu-is-now-generally-available-on-intel-socs (or any other blog) has the new Canonical logo
Fixes https://warthogs.atlassian.net/browse/WD-5826
> WD-5826 Update Canonical logo

- templates/base_index.html
Created and added a 48x48 favicon
- Check the code looks right
- Check the image link loads
Fixes https://warthogs.atlassian.net/browse/WD-5431
> WD-5431 - Add a 48x48 favicon

- webapp/greenhouse.py
- Fix broken submissions 
- See that the following applications submit without issue:
- https://canonical-com-1029.demos.haus/careers/5057812/application
- https://canonical-com-1029.demos.haus/careers/2808065/application 
- https://canonical-com-1029.demos.haus/careers/4754075/application
Fixes https://warthogs.atlassian.net/browse/WD-6041
> Fix application submission bug

- templates/partners/find-a-partner.html
- Updated copy as per [doc](https://docs.google.com/document/d/1R3s-aiSrFvbNrHjdfblYo_XX1f_EQ989DkmPS41seZc/edit#heading=h.ar6wjtr6gejj)
- View the site locally in your web browser at: https://canonical-com-1026.demos.haus/partners/find-a-partner
Fixes #https://warthogs.atlassian.net/browse/WD-6036
> [copy update] /partners/find-a-partner

- templates/partners/silicon.html
- Applied copy updates as per [doc](https://docs.google.com/document/d/1nyiz4I1GqBiXe_SKpDzho3yv20LKyYpyhHh0fvvUrOI/edit)
- View the site locally in your web browser at: https://canonical-com-1031.demos.haus/partners/silicon
Fixes https://warthogs.atlassian.net/browse/WD-6017
> [copy update] /partners/silicon

- templates/base_index.html
- templates/index.html
- templates/partners/partial/_homepage-form.html
Add contact form for Canonical.com homepage
- Go to https://canonical-com-1033.demos.haus/ click on "Contact-us"
- Compare against [copy docs](https://docs.google.com/document/d/1saDssfbHdM0pJgJdQmJG7uB6IefXlfCk-c-mCURohB4/edit)
- Check that the form works
Fixes https://warthogs.atlassian.net/browse/WD-5230
>   WD-5230 Add homepage contact form

- templates/careers/application/_withdrawal-form.html
- templates/careers/application/index.html
Reverts canonical/canonical.com#1040
This breaks pages that have candidate reports available. We need to test all stages of the candidate.
> Revert "WD-6068 Fix navigation on application page"

- static/sass/_pattern_strip.scss
- static/sass/styles.scss
- templates/data/_data-form.html
- templates/data/index.html
Build new data page for c.com
- Check [/data](https://canonical-com-1043.demos.haus/data) against [design](https://www.figma.com/file/17XOOU2kMgAW7CsRhGyu4Y/23.10-C.com---Data-Fabric?type=design&node-id=128-1198&mode=design&t=E7BrAN2kszpcKFSM-0)
- Check against [copy docs](https://docs.google.com/document/d/1r1xnNihaTphO_eikifUEO7ocYfTDnbuRIaIfUCmya1c/edit)
- Click on Get in touch, fill up the form and make sure it works.
Fixes https://warthogs.atlassian.net/browse/WD-5872?atlOrigin=eyJpIjoiNGRiMmQzZWRjNDUwNGYyZWFiNmVkMzNmN2Q4ODAzZmQiLCJwIjoiaiJ9
> Build new /data page

- static/sass/styles.scss
- templates/data/_form-data-spark.html
- templates/data/spark.html
- templates/index.html
- Built page as per [doc](https://docs.google.com/document/d/1sM8pgyM-N8VK8fyHgMsW21PdXUiqYrdRkPkipIljNd0/edit) and [mock-up](https://www.figma.com/file/17XOOU2kMgAW7CsRhGyu4Y/23.10-C.com---Data-Fabric?node-id=458%3A7842&mode=dev)
- View the site locally in your web browser at: https://canonical-com-1044.demos.haus/data/spark
Fixes https://warthogs.atlassian.net/browse/WD-5877
> Build /data/spark

- templates/contact-us.html
Fix Capitalisation of word in address 
(none attempted)
Fixes  #1053 
> Fix capitalisation of united in address

- static/sass/styles.scss
- templates/data/_form-data-mongodb.html
- templates/data/mongodb.html
- Built page as per [doc](https://docs.google.com/document/d/1mCztOFZYbC3TeUM7j7pGfSoxKzBs20W1pJHZhdLqKs8/edit) (no mock-up)
I had to make some guesses as to where to put some of the images, the isometric one in the hero I already know will probably need to be moved, but I'll wait for designs instructions to tell me where. As with the rest of my prs for this bubble, please note that any CTA that links to the modal will not work. Main CTA ("Get our guide to MongoDB security and support") is also missing as the datasheet it's supposed to link to is not live yet.
- View the site locally in your web browser at: https://canonical-com-1046.demos.haus/data/mongodb
- Check against doc
Fixes https://warthogs.atlassian.net/browse/WD-5879
> Build /data/mongodb

- templates/data/_form-data-opensearch.html
- templates/data/opensearch.html
- Built page as per [doc](https://docs.google.com/document/d/1nVdoKoPrXw8lsvHEtMichlPNfxYU9Uj1zmKowcUXQ_w/edit#heading=h.eto59uxtlv76) (no design for this one)
- View the site locally in your web browser at: https://canonical-com-1045.demos.haus/data/opensearch
- Check against doc
- Check against design](https://www.figma.com/file/17XOOU2kMgAW7CsRhGyu4Y/23.10-C.com---Data-Fabric?node-id=862%3A8828&mode=dev) some elements that were inconsistent with the rest of the pages have been changed to keep consistency.
- Check there are no errors on [Waves](https://wave.webaim.org/extension/)
Fixes https://warthogs.atlassian.net/browse/WD-5881
> Build /data/opensearch

- static/sass/_pattern_careers-modal.scss
- templates/data/_form-data-kafka.html
- templates/data/kafka.html
Build the /data/kafka page based on the [spark PR](https://github.com/canonical/canonical.com/pull/1044) and the [copy doc](https://docs.google.com/document/d/1bfo97XdFdKlzrMcMoRxiTdzt_bPVndx6j55IPsapuAE/edit)
- Check the page matches [the design](https://www.figma.com/file/17XOOU2kMgAW7CsRhGyu4Y/23.10-C.com---Data-Fabric?type=design&node-id=128-1198&mode=design&t=JrwRIYNoAxR8awNi-0) of the PR links above
- Check the content matches the copy doc above with some small content shifts to match the layout
- Check there are no errors on [Waves](https://wave.webaim.org/extension/)
- Maybe check the HTML is valid using https://validator.w3.org/nu/#textarea
Fixes https://warthogs.atlassian.net/browse/WD-5874
> WD-5874 - Build the /data/kafka page and modal form

- templates/index.html
Introduce changes to home page according to [the copy doc](https://docs.google.com/document/d/1GNa1FaTkARdrVwYgHXf5H-6sqOLjkJENDistDDcsi4o/edit#heading=h.ax24ul9igcqj)
- Check if changes to home page correspond to ones highlighted in the provided copy doc
Closes https://warthogs.atlassian.net/browse/WD-6482
> [WD-6482] add changes to the home page

- templates/careers/company-culture/index.html
- Changed "Employees" to "People" text on /career/company-culture
[WD-6621](https://warthogs.atlassian.net/browse/WD-6621)
Fixes #
[WD-6621]: https://warthogs.atlassian.net/browse/WD-6621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-6621 - update /company-culture page

- templates/data/mongodb.html
- Updated datasheet and whitepaper links as per [doc](https://docs.google.com/document/d/1mCztOFZYbC3TeUM7j7pGfSoxKzBs20W1pJHZhdLqKs8/edit)
- View the site locally in your web browser at: https://canonical-com-1072.demos.haus/data/mongodb
Fixes https://warthogs.atlassian.net/browse/WD-6065
> [copy update] /data/mongodb

- templates/data/_form-data-relational-dbs.html
- templates/data/relational-databases.html
- templates/data/spark.html
Build /data/relational-databases, this page is only for SEO, not to be included in navigation.
- Check https://canonical-com-1066.demos.haus/data/relational-databases compare with [design](https://www.figma.com/file/17XOOU2kMgAW7CsRhGyu4Y/23.10-C.com---Data-Fabric?type=design&node-id=740-58845&mode=design&t=v9km7lC1u0tuQnA6-0) and [copy doc](https://docs.google.com/document/d/1ikYzd23-zop6k7qO7LXzjttvltBL-au8A50XzuDDd5M/edit)
Fixes https://warthogs.atlassian.net/browse/WD-5582
> Build data relational databases page

- tests/test_application.py
- webapp/application.py
- Created a function to check all candidate emails attached to the profile
- Added tests to check expectations
- Load up the demo
- Use the [details attached here](https://pastebin.canonical.com/p/VKBYqyr2vd/) to QA the situations
- Check the test pass in CI
Fixes https://warthogs.atlassian.net/browse/WD-6781
> WD-6781 - Respect candidates with multiple email addresses when checking report

- templates/index.html
Changes related to data bubble
- Navigate to `/data` URL
This is a feature branch that accumulates several different tickets related to data bubble epic: https://warthogs.atlassian.net/browse/WD-3805
> Data bubble migration

- templates/data/docs/mongodb/iaas/document.html
- templates/data/docs/mongodb/iaas/search-results.html
- templates/data/docs/mongodb/k8s/document.html
- templates/data/docs/mongodb/k8s/search-results.html
- templates/data/docs/mysql/iaas/document.html
- templates/data/docs/mysql/iaas/search-results.html
- templates/data/docs/mysql/k8s/document.html
- templates/data/docs/mysql/k8s/search-results.html
- templates/data/docs/opensearch/iaas/document.html
- templates/data/docs/opensearch/iaas/search-results.html
- templates/data/docs/postgresql/iaas/document.html
- templates/data/docs/postgresql/iaas/search-results.html
- templates/data/docs/postgresql/k8s/document.html
- templates/data/docs/postgresql/k8s/search-results.html
- templates/data/docs/spark/k8s/document.html
- templates/data/docs/spark/k8s/search-results.html
- templates/data/sitemap.xml
- templates/sitemap-links.xml
Add /data bubble to sitemaps
Change relative URL to absolute URLs for indexing.
Can only be QAed once deployed.
Fixes https://warthogs.atlassian.net/browse/WD-6606
> Add data bubble to sitemaps

- static/sass/_pattern_strip.scss
- static/sass/styles.scss
- templates/data/index.html
- templates/data/kafka.html
- templates/data/mongodb.html
- templates/data/opensearch.html
- templates/data/spark.html
make hero sections on data bubble more consistent
- review the heroes on the data bubble https://canonical-com-1087.demos.haus//data
Fixes #
> make hero sections on data bubble more consistent

- README.md
- Fix LGPL 3.0 license link
Fixes #
> docs: update README.md license link

- README.md
- templates/data/spark.html
> Merge main into feature branch

- static/js/microcloud-slider.js
- static/sass/styles.scss
- templates/microcloud/resources.html
- Built page as per [doc](https://docs.google.com/document/d/1ffTxn2ymKrWRPUjjx6cN0-OA6rlIuX0YaVbFQHcpsTM/edit) and [design](https://www.figma.com/file/KQSCmTqOjY4gfKvJPyvzj2/Canonical.com-latest-only?node-id=12964%3A15505&mode=dev)
- View the site locally in your web browser at: https://canonical-com-1097.demos.haus/microcloud/resources
- Check against copy and design
Fixes https://warthogs.atlassian.net/browse/WD-6695
> Add resources page and slider

- static/js/microcloud-slider.js
- templates/microcloud/contact-us.html
- templates/microcloud/index.html
- Address comments mentioned [here](https://github.com/canonical/canonical.com/pull/1103#pullrequestreview-1727233647)
> Apply code review

- templates/partners/silicon.html
- Updated text and image in https://canonical-com-1120.demos.haus/partners/silicon
- [copy doc](https://docs.google.com/document/d/1nyiz4I1GqBiXe_SKpDzho3yv20LKyYpyhHh0fvvUrOI/edit)
- [demo link](https://canonical-com-1120.demos.haus/)
- Check that text and links are correct
[WD-7440](https://warthogs.atlassian.net/browse/WD-7440)
Fixes #
[WD-7440]: https://warthogs.atlassian.net/browse/WD-7440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-7440 - update /silicon page

- templates/data/mysql.html
- templates/partial/_data-navigation.html
Build new data bubble page /data/mysql
- Check https://canonical-com-1123.demos.haus/data/mysql against [copy docs](https://docs.google.com/document/d/1KQmCfb4ITlYHOAEoHUwxHExf73qkMSWsLHnFPwFWFag/edit)
- If demos don't work checkout this PR, and check localhost:8002/data/mysql against [copy docs](https://docs.google.com/document/d/1KQmCfb4ITlYHOAEoHUwxHExf73qkMSWsLHnFPwFWFag/edit)
Fixes https://warthogs.atlassian.net/browse/WD-6363
> WD-6363 MySQL page 

- templates/careers/company-culture/diversity.html
- Updated Hanna's job title in https://canonical-com-1130.demos.haus/careers/company-culture/diversity
- [copy doc](https://docs.google.com/document/d/1l1UGJToc0ErHUMN9W8hELvF5sDyVRO7N0xDzncqA2SQ/edit)
- [demo link](https://canonical-com-1130.demos.haus/)
- Check that the job title is correct
[WD-7587](https://warthogs.atlassian.net/browse/WD-7587)
Fixes #
[WD-7587]: https://warthogs.atlassian.net/browse/WD-7587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-7587 - update /diversity page

- templates/data/postgresql.html
- templates/data/spark.html
- templates/partial/_data-navigation.html
- Built page as per [doc](https://docs.google.com/document/d/1GxineF4WLt0YlShaYkrzqWjIOkXjLJEfsnUdWVfWnz4/edit) and [design](https://www.figma.com/file/17XOOU2kMgAW7CsRhGyu4Y/23.10-C.com---Data-Fabric-bubble-(rebranding)?node-id=128%3A1198&mode=dev)
- View the site locally in your web browser at: https://canonical-com-1124.demos.haus/data/postgresql
- Check against doc and design on all screen sizes 
Fixes # https://warthogs.atlassian.net/browse/WD-6433
> Add postgresql page to data bubble and subnav

- templates/careers/application/faq.html
Updated the copy to match the [copy doc](https://docs.google.com/document/d/12_O_QtPqfv9p7kaDFdiP8Xq-kY5xa1XB-C-CRbXjDew/edit)
- Check the copy
> Update time to complete the WI in the FAQ

- templates/data/mysql.html
- templates/lxd/_form-lxd-install.html
- templates/lxd/install.html
Build LXD install page
- Check https://canonical-com-1127.demos.haus/lxd/install against [copy docs](https://docs.google.com/document/d/1LKlXAc39dy69dSCc7PE6WqV2qkCSeXmicKGS4lFicDE/edit) and [design](https://www.figma.com/file/ZU2ufsTJD9tEkXPqhhDMZz/U.com---LXD-(rebranding)?node-id=447%3A1412&mode=dev)
Note: visual designer has changed the original layout that came from the agency, so please compare it loosely.
- Click on "Get in touch" and test that it submits successfully (you can fill it up with "test" for all fields, it'll be ignored in marketo)
Fixes https://warthogs.atlassian.net/browse/WD-7565
[if relevant, …
> WD-7565 LXD install page

- static/sass/_pattern_strip.scss
- static/sass/styles.scss
- templates/lxd/manage.html
- templates/partial/_lxd-navigation.html
- templates/partial/_navigation.html
Build u.com/lxd/manage page
- Check https://canonical-com-1129.demos.haus/lxd/manage against [copy docs](https://docs.google.com/document/d/1doGyKYSTOsX8dHvQ6W9W2U_pHQY6yfiq1bqSAJyredQ/edit) and [design](https://www.figma.com/file/ZU2ufsTJD9tEkXPqhhDMZz/U.com---LXD-(rebranding)?node-id=1%3A3&mode=dev)
Fixes https://warthogs.atlassian.net/browse/WD-7536
> WD-7536 LXD manage page 

- static/sass/_pattern_strip.scss
- templates/lxd/index.html
Build overview LXD page.
- Check https://canonical-com-1125.demos.haus/lxd against [copy docs](https://docs.google.com/document/d/1LJ6ajHYAmKdxSNDaD5kbriDod1t7RcmIwVJtevAeKFQ/edit) and [design](https://www.figma.com/file/ZU2ufsTJD9tEkXPqhhDMZz/U.com---LXD-(rebranding)?node-id=624%3A2725&mode=dev)
Fixes https://warthogs.atlassian.net/browse/WD-6728
> Build new LXD bubble page

- static/sass/_pattern_strip.scss
- static/sass/styles.scss
- templates/data/mysql.html
- templates/lxd/_form-lxd-install.html
- templates/lxd/index.html
- templates/lxd/install.html
- templates/lxd/manage.html
- templates/partial/_lxd-navigation.html
- templates/partial/_navigation.html
/lxd bubble pages
- All PRs have been reviewed already, just QA that nothing is broken https://canonical-com-1138.demos.haus/lxd
- Click on the different navigation items to go to each page.
Fixes https://warthogs.atlassian.net/browse/WD-6727
> LXD bubble feature branch

- templates/solutions/_form-big-data-ai.html
- templates/solutions/big-data-ai.html
- Added /solutions/big-data-ai page as per [doc](https://docs.google.com/document/d/1UX4HyHpByhiG81_FZk71PxAGu6IE-GHfir3_18jNyYM/edit) and [design](https://www.figma.com/file/canUCAgMpSHPKCG183X81U/24.04-Canonical.com---Solutions?type=design&node-id=0%3A1&mode=design&t=rCaDqCZbKBsExtHr-1)
- Added corresponding modal as per [doc](https://docs.google.com/document/d/1ZDYZHdATF7Pqlmkq9s-ucN9YdCu7ZA648vlGkyQFApc/edit)
- View the site locally in your web browser at: https://canonical-com-1140.demos.haus/solutions/big-data-ai
- Check page against doc and design 
- Open modal and check against doc
Fixes https://warthogs.atlassian.net/browse/WD-7812 , https://warthogs.atlassian.net/browse/WD-6655
> Build /solutions/big-data-ai and modal

- templates/partial/_lxd-navigation.html
Update LXD logo [according to request](https://warthogs.atlassian.net/browse/WD-6727?focusedCommentId=357771)
- Check https://canonical-com-1145.demos.haus/lxd has the updated logo
- Compare with current site which has the Ubuntu logo https://canonical.com/lxd
Fixes https://warthogs.atlassian.net/browse/WD-6727
> Update LXD logo

- templates/data/mysql.html
Address [comment to update isometric images](https://docs.google.com/document/d/1KQmCfb4ITlYHOAEoHUwxHExf73qkMSWsLHnFPwFWFag/edit?disco=AAABBySjFEE/)
- Check https://canonical-com-1137.demos.haus/data/mysql  "What can you achieve with" section now looks the same [as design](https://www.figma.com/file/17XOOU2kMgAW7CsRhGyu4Y/23.10-C.com---Data-Fabric-bubble-(rebranding)?node-id=1094%3A13407&mode=dev) or that same section on https://canonical-com-1137.demos.haus/data/postgresql
Fixes https://warthogs.atlassian.net/browse/WD-7814
> Update isometric images

- templates/projects/directory.html
Update the projects directory with the latest changes in the document.
- Open [the demo](https://canonical-com-1146.demos.haus/projects/directory)
- Check the copy matches the copy from [the project sheet](https://docs.google.com/spreadsheets/d/14Smfpq9ttrPt2jPx70NB3QTixH_6h7Ktnp1CihjT1So/edit#gid=0)
Fixes https://warthogs.atlassian.net/browse/WD-5607
> WD-5607 - Update the projects directory

- templates/careers/_search.html
Updated job search field to give wider range of results and sorted them by relevance
- [demo link](https://canonical-com-1150.demos.haus/careers)
- Check that the job search matches expected results
[WD-7800](https://warthogs.atlassian.net/browse/WD-7800)
Fixes #981
[WD-7800]: https://warthogs.atlassian.net/browse/WD-7800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-7800 - adjust job search field

- templates/solutions/big-data-ai.html
- Updated copy doc link to [correct doc](https://docs.google.com/document/d/1UX4HyHpByhiG81_FZk71PxAGu6IE-GHfir3_18jNyYM/edit)
- View the site locally in your web browser at: https://canonical-com-1159.demos.haus/solutions/big-data-ai
- See that the doc linked in the metadata is correct
Fixes https://warthogs.atlassian.net/browse/WD-8280
> /solutions/big-data-ai correct copy doc link

- .github/workflows/pr.yaml
- templates/data/spark-on-kubernetes.html
- Build new spark-on-kubernetes page.
- Check https://canonical-com-1162.demos.haus/data/spark-on-kubernetes against screenshot below. Check against [copy docs](https://docs.google.com/document/d/1N399Pym7aTEuTf_OAJiFrYcbtsy3iUHV-f82afSplcI/edit)
- Check everything looks ok in smaller screens.
Fixes https://warthogs.atlassian.net/browse/WD-7781
> Build new Spark on K8s page

- static/sass/styles.scss
- templates/data/spark-on-kubernetes.html
Improve code snippet [as requested](https://warthogs.atlassian.net/browse/WD-7777?focusedCommentId=392913):
- Improve styling (Design already approved after MM conversation)
- Fix typo
- Check https://canonical-com-1166.demos.haus/data/spark-on-kubernetes doesn't have the code snippet anymore.
Fixes https://warthogs.atlassian.net/browse/WD-7777
> Improve code snippet as requested WD-7777

- templates/contact-us.html
- Updated copy as per [doc](https://docs.google.com/document/d/1Qxvhl6_kgCDarcem1wcFPQyHk0JEFUP1zIzNsIrT3_Y/edit#heading=h.zg0dy9ryqhw)
- View the site locally in your web browser at: https://canonical-com-1178.demos.haus/contact-us
Fixes https://warthogs.atlassian.net/browse/WD-8824
> /contact-us copy update

- templates/contact-us.html
- Follow up of https://github.com/canonical/canonical.com/pull/1178, updated copy as per [doc](https://docs.google.com/document/d/1Qxvhl6_kgCDarcem1wcFPQyHk0JEFUP1zIzNsIrT3_Y/edit)
- View the site locally in your web browser at: https://canonical-com-1179.demos.haus/contact-us
- See that "Correspondence" has been changed to  "mailing"
> Copy update follow up /contact-us

- templates/base_index.html
- templates/solutions/_form_infrastructure.html
- templates/solutions/infrastructure.html
Create infrastructure page
Note: for testing purposes the link for successful form submission will be changed to the demo link. Will be updated before merge
- [demo link](https://canonical-com-1184.demos.haus/solutions/infrastructure)
- [copy doc](https://docs.google.com/document/d/1xbuIA53HKrMatjuiNQwf1ORwLvNXFEF0UqGTbB6sXL0/edit)
- [figma](https://www.figma.com/file/Cova41wSG3JIq9NPNZnC50/Canonical.com%2Fsolutions%2Finfrastructure?type=design&node-id=0-1&mode=design&t=eYW5H4A3x6cEa661-0)
- Check that the page and it's content is according to copy doc …
> WD-8721 - create /solutions/infrastructure page

- templates/data/index.html
- Applied copy updates as per [doc](https://docs.google.com/document/d/1r1xnNihaTphO_eikifUEO7ocYfTDnbuRIaIfUCmya1c/edit) 
- View the site locally in your web browser at: https://canonical-com-1185.demos.haus/data
Fixes https://warthogs.atlassian.net/browse/WD-9043
> Copy update /data

- templates/careers/application/index.html
- webapp/application.py
Add the Enterprise Sales Representative video to the candidate page
Could not use the hiring JSON as this is on the hiring lead level not the individual role
Updated the title text
- Check the code looks right as the position is not open yet.
- Check some candidate pages to check they continue to work as expected
> Add the Enterprise Sales Representative video to the candidate page

- templates/careers/application/faq.html
- Check https://canonical-com-1204.demos.haus/careers/application/faq against [copy doc changes](https://docs.google.com/document/d/12_O_QtPqfv9p7kaDFdiP8Xq-kY5xa1XB-C-CRbXjDew/edit)
Fixes https://warthogs.atlassian.net/browse/WD-9572
> WD-9572 Update written interview FAQs

- templates/solutions/ai/index.html
Update /solutions/ai page according to copy doc
- [demo link](https://canonical-com-1235.demos.haus/solutions/ai)
- [copy doc](https://docs.google.com/document/d/1AtAApqxX9cbWf4a3cakEYbk7OoTfdBBi7FlA3WZz5ZM/edit)
- Check that the page is updated correctly according to the copy doc
[WD-9988](https://warthogs.atlassian.net/browse/WD-9988)
[WD-9988]: https://warthogs.atlassian.net/browse/WD-9988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-9988 - update /solutions/ai page

- package.json
- templates/base_index.html
- yarn.lock
- Updated the coookie policy to v3.6.3
- View the demo in an incognito web browser at: https://canonical-com-1236.demos.haus/
- **Before** accepting cookies, 
- Open developer tools and in the console type in `dataLayer`
- There should be a `{"consent", "default"}` object in the dataLayer
- **After** accepting cookies, 
- There should be a `{"consent", "update"}` object in the dataLayer
> Update cookie policy to v3.6.3

- templates/index.html
- Update text on homepage as per [copydoc](https://docs.google.com/document/d/1GNa1FaTkARdrVwYgHXf5H-6sqOLjkJENDistDDcsi4o/edit)
- Go to the [home page](https://canonical-com-1238.demos.haus/) and see the text has been updated
Before:
After:
Fixes https://warthogs.atlassian.net/browse/WD-10371
> Update text on homepage

- templates/partners/partial/_partner-filters/_programme-filters.html
Update find a partner filters list. Add ISV, IoT Devices and ODM to Programme section
- [demo link](https://canonical-com-1240.demos.haus/partners/find-a-partner)
- [copy doc](https://docs.google.com/document/d/1R3s-aiSrFvbNrHjdfblYo_XX1f_EQ989DkmPS41seZc/edit)
- Check that the page is updated correctly according to the copy doc
[WD-10274](https://warthogs.atlassian.net/browse/WD-10274)
[WD-10274]: https://warthogs.atlassian.net/browse/WD-10274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-10274 - update find a partner filters list

- templates/solutions/ai/index.html
- Update copy on /solutions/ai based on [copydoc](https://docs.google.com/document/d/1AtAApqxX9cbWf4a3cakEYbk7OoTfdBBi7FlA3WZz5ZM/edit)
- Formats file, updated sections have comments
- Go to https://canonical-com-1246.demos.haus/solutions/ai and check the changes match the [copydoc](https://docs.google.com/document/d/1AtAApqxX9cbWf4a3cakEYbk7OoTfdBBi7FlA3WZz5ZM/edit)
Fixes https://warthogs.atlassian.net/browse/WD-10536
> Update copy on /solutions/ai

- templates/documentation/index.html
- templates/documentation/work-and-careers.html
- Updated CTA link as per docs [1](https://docs.google.com/document/d/1U-IkZOMzQlfV0zAAmM0PRVUBoZNBeOa-Qrso3i4rDVU/edit#heading=h.zic51zh7uz4b), [2](https://docs.google.com/document/d/10tOsj5kKZRddQYYkb1PgxsES47Qic8XJc9xpRaYHd7s/edit)
- View the site locally in your web browser at: 
- https://canonical-com-1247.demos.haus/documentation#documentation-with-rigour
- https://canonical-com-1247.demos.haus/documentation/work-and-careers
Fixes https://warthogs.atlassian.net/browse/WD-10745
> Update CTA link

- templates/solutions/infrastructure/index.html
- Refresh page and add case studies as per [copy docs](https://docs.google.com/document/d/1xbuIA53HKrMatjuiNQwf1ORwLvNXFEF0UqGTbB6sXL0/edit#heading=h.fm4s9t47agvc)
- Go to `/solutions/infrastructure` on [demos](https://canonical-com-1255.demos.haus/solutions/infrastructure)
- Check that updates reflect changes in [copy docs](https://docs.google.com/document/d/1xbuIA53HKrMatjuiNQwf1ORwLvNXFEF0UqGTbB6sXL0/edit#heading=h.fm4s9t47agvc)
- Check that assets are loading and links to case studies are correct
Fixes [WD-11254](https://warthogs.atlassian.net/browse/WD-11254)
[WD-11251]: https://warthogs.atlassian.net/browse/WD-11251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WD-11254]: …
> Refresh /solutions/infrastructure page

- templates/contact-us.html
- Remove sales contact numbers
- Djlint formatting
- Go to https://canonical-com-1259.demos.haus/contact-us check that sales have been removed according to https://warthogs.atlassian.net/browse/WD-11266
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932?assignee=626a79c0494f170070572dab&selectedIssue=WD-11266
> Remove sales contact numbers

- templates/careers/application/index.html
- templates/careers/application/partial/_early-stage.html
- templates/careers/application/partial/_late-stage.html
applied djlint --reformat and fixed element nesting.
- View the site locally in your web browser at: `http://0.0.0.0:8002/careers/application/<token>`
- Nothing should have changed in the view
> djlint --reformat, fix elements nesting

- static/js/modals.js
- static/sass/_pattern_homepage-modal.scss
- static/sass/styles.scss
- templates/partners/partial/_homepage-form.html
Fix homepage modal styling
- [demo link](https://canonical-com-1265.demos.haus#get-in-touch)
- Check that the form is using dark theme
[WD-11799](https://warthogs.atlassian.net/browse/WD-11799)
[WD-11799]: https://warthogs.atlassian.net/browse/WD-11799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-11799 - fix homepage modal styling

- templates/solutions/ai/index.html
- templates/solutions/big-data-ai/index.html
- templates/solutions/secure-open-source/index.html
- Format files with djlint (mainly what's causing the large diff)
- Change form submission redirect from `#success` to `#contact-form-success`
- Shows the correct message: **Thank you for contacting our team. We will be in touch shortly.** as seen in the forms copy doc
- Go to demos: [/solutions/ai](https://canonical-com-1267.demos.haus/solutions/ai), [/solutions/secure-open-source](https://canonical-com-1267.demos.haus/solutions/secure-open-source), [/solutions/big-data-ai](https://canonical-com-1267.demos.haus/solutions/big-data-ai)
- Click on `Contact Canonical` and submit form
- On form submission success, check that url has `#contact-form-success` and is showing the correct notification banner (in screenshot below)
- Forms copy docs: …
> Update contact form success banner

- templates/lxd/manage.html
- Go to https://canonical-com-1273.demos.haus/lxd/manage and check [comments have been addressed](https://docs.google.com/document/d/1doGyKYSTOsX8dHvQ6W9W2U_pHQY6yfiq1bqSAJyredQ/edit#heading=h.jdq1ggqzcow3)
Fixes https://warthogs.atlassian.net/browse/WD-11979
> WD-11979 copy update

- static/js/modals.js
- static/sass/_pattern_forms.scss
- templates/partners/partial/_homepage-form.html
Updated contact form according to copy doc
- [demo link](https://canonical-com-1270.demos.haus/contact-us)
- [copy doc](https://docs.google.com/document/d/1m26cLDsx5OoCBFSblGgEUiGHsRtdLWAI6GBh-KnRIq0/edit)
- Check that the forms are correct according to copy doc
[WD-10729](https://warthogs.atlassian.net/browse/WD-10729)
[WD-10729]: https://warthogs.atlassian.net/browse/WD-10729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-10729 - update contact form

- templates/solutions/big-data-ai/index.html
- Applied copy updates as per [doc](https://docs.google.com/document/d/1UX4HyHpByhiG81_FZk71PxAGu6IE-GHfir3_18jNyYM/edit)
- View the site locally in your web browser at: https://canonical-com-1279.demos.haus/solutions/big-data-ai
Fixes https://warthogs.atlassian.net/browse/WD-12465
> Update copy /solutions/big-data-ai

- templates/solutions/ai-infrastructure/index.html
- Apply updates as per [doc](https://docs.google.com/document/d/1oYV0LsLNg2yUn6Y81AMMX-9jDnojUT8H8kLqqizOZ-M/edit)
- View the site locally in your web browser at: https://canonical-com-1281.demos.haus/solutions/ai-infrastructure
Fixes https://warthogs.atlassian.net/browse/WD-12511
> Update copy /solutions/ai-infrastructure

- templates/solutions/sovereign-cloud/_form-sovereign-cloud.html
- templates/solutions/sovereign-cloud/index.html
- Build '/solutions/sovereign-cloud' page based on [copydoc](https://docs.google.com/document/d/1XvdgVN87yqI9xOtFBaK9Z_Au8PTeHlQICzlYrgUKxuQ/edit) and [design](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/24.10-Canonical.com%2Fsolutions%2Fsovereign-cloud?node-id=7-1254&t=NWmCG5I6aETEhEtb-0)
- Build modal form based on [copydoc](https://docs.google.com/document/d/1GkR3cbZbe7-gbwADceV8CkZK1xWI55nx8rSmsCLyuio/edit)
- Go to https://canonical-com-1280.demos.haus/solutions/sovereign-cloud
- Check the content matches that in the [copydoc](https://docs.google.com/document/d/1XvdgVN87yqI9xOtFBaK9Z_Au8PTeHlQICzlYrgUKxuQ/edit)
- Check on all screen sizes
- Check the modal opens and that the content matches the [copydoc](https://docs.google.com/document/d/1GkR3cbZbe7-gbwADceV8CkZK1xWI55nx8rSmsC …
> feat: Build '/solutions/sovereign-cloud' page and modal form

- navigation.yaml
- Builds the c.com navigation.yaml using the [copydoc](https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit) and [ubuntu.com meganav.yaml](https://github.com/canonical/ubuntu.com/blob/d194d348052aafb2e1692ee2f68159f65c869c6b/meganav.yaml) as reference
- Go through the navigation.yaml file and check that all the names, links and descriptions match. **note the use of placeholders where links were missing** 
- Check that everything is appropriately nested.
Fixes https://warthogs.atlassian.net/browse/WD-12079
> feat: Build navigation.yaml which will be used to dynamically build the meganav

- templates/index.html
Add banner to the c.com home page
- [demo link](https://canonical-com-1286.demos.haus/)
- [copy doc](https://docs.google.com/document/d/1GNa1FaTkARdrVwYgHXf5H-6sqOLjkJENDistDDcsi4o/edit)
- Check that the banner is correct according to copy doc 
[WD-12532](https://warthogs.atlassian.net/browse/WD-12532)
[WD-12532]: https://warthogs.atlassian.net/browse/WD-12532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-12532 - add banner to c.com

- templates/lxd/index.html
- Refreshed /lxd page.
- Check if the /lxd page is working fine.
- Check if all the changes are done as according to [copydoc](https://docs.google.com/document/d/1LJ6ajHYAmKdxSNDaD5kbriDod1t7RcmIwVJtevAeKFQ/edit).
- Use this [Figma Design](https://www.figma.com/design/dHmV2b8tplxbBzDW27ypPX/canonical.com%2Flxd?node-id=0-1&t=brs1rvUl7JSpEHe6-0) as visual reference.
- Here is the [demo](https://canonical-com-1284.demos.haus/lxd) generated for the PR.
Fixes # [12107](https://warthogs.atlassian.net/browse/WD-12107)
> WD-12107 Refreshed /lxd page

- package.json
- static/js/navigation.js
- templates/navigation/navigation.html
- templates/navigation/secondary-navigation.html
- yarn.lock
**Don't merge**: Until the branch this PR references has been merged
- Updates the reduced navigation to use the latest vanilla pattern, found here https://github.com/canonical/vanilla-framework/pull/5210
- It moves the search to be all in the 'normal' navigation
- Open [demo](https://canonical-com-1294.demos.haus/)
- Check the search functionality, both on desktop and mobile screen sizes
Fixes https://warthogs.atlassian.net/browse/WD-13043
> refactor: Updates the reduced nav search to use newest Vanilla pattern

- templates/solutions/secure-open-source/index.html
-  Refreshed /solutions/secure-open-source
- Check if all is in accordance to [copydoc](https://docs.google.com/document/d/1mrvhkrVjCCJE39h96CPG_b_ZHWVN0GHzZ_6TdoudeYs/edit#heading=h.oy44zuppmsv2) and [figma design](https://www.figma.com/design/8JrAyKnWMU9FPJE0zJT2gu/Canonical.com%2Fsolutions%2Fsecure-open-source?node-id=0-1&t=GuOVZ4LegRxePrMe-0).
-  Please check demo [here](https://canonical-com-1293.demos.haus/solutions/secure-open-source)
Fixes # [WD-12327](https://warthogs.atlassian.net/browse/WD-12299)
[WD-12327]: …
> WD-12299 Refreshed /solutions/secure-open-source

- templates/solutions/telco/index.html
- Refreshed /solutions/telco
- Added two new sections
- Check if all is in accordance to [copydoc](https://docs.google.com/document/d/1yRSYYY8_UNfZzdLcp_fYxi-STGm40o3UP9vD2vW6brw/edit) and [figma design](https://www.figma.com/design/2QvG4FdcvOpzc9ikdWqKod/Canonical.com%2Fsolutions%2Ftelco?node-id=0-1&t=vGub60kwzbzyIRwr-0).
-  Please check demo [here](https://canonical-com-1292.demos.haus/solutions/telco)
Fixes # [WD-12327](https://warthogs.atlassian.net/browse/WD-12327)
[WD-12327]: https://warthogs.atlassian.net/browse/WD-12327?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
> WD-12327 Refreshed /solutions/telco

- templates/index.html
- templates/microcloud/index.html
- Update Dell logos as per copy doc
- Format image tags on /microcloud file (where most of the diff is)
- List of copy docs: https://docs.google.com/document/d/1XWYk5IWx9US6ympIMNveRlgJOH_cyNCB1eQFHBsr4tA/edit
- Go to https://canonical-com-1302.demos.haus/ and https://canonical-com-1302.demos.haus/microcloud
- Check that the Dell logos are updated to the new logo
Fixes [WD-13284](https://warthogs.atlassian.net/browse/WD-13284)
[WD-13284]: https://warthogs.atlassian.net/browse/WD-13284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update Dell logo

- templates/documentation/open-documentation-academy.html
https://canonical.com/documentation/open-documentation-academy
Changed Weekly Office Hours to Friday.
Added link to Office Hours.
Added Matrix to Stay in touch.
(tested)
> /documentation: updated academy links and office hours day

- templates/solutions/ai/edge.html
- Built page as per [doc](https://docs.google.com/document/d/17eHoiLrhFLrfV8UXD_4bxn-yY1_YToxf4cs8-5kYkxo/edit) and [design](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/24.10-Canonical.com%2Fsolutions?node-id=125-8552&m=dev)
- View the site locally in your web browser at: https://canonical-com-1306.demos.haus/solutions/ai/edge
- Check layout on smaller screens
Fixes https://warthogs.atlassian.net/browse/WD-12553
> Build /ai/edge page

- templates/solutions/secure-open-source/index.html
-Updated copy text
- [Copydoc](https://docs.google.com/document/d/1mrvhkrVjCCJE39h96CPG_b_ZHWVN0GHzZ_6TdoudeYs/edit)
- [Demo](https://canonical-com-1312.demos.haus/solutions/secure-open-source)
Fixes # [WD-13517](https://warthogs.atlassian.net/browse/WD-13517)
[WD-13517]: https://warthogs.atlassian.net/browse/WD-13517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-13517 Copy Update Text

- navigation.yaml
- Adds a few missing links to the navigation.yaml
- Open navigation.yaml and compare to the changes in [the copydoc](https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit)
- There are still some `/PLACE-HOLDER`s for the image urls. These will come later
Fixes https://warthogs.atlassian.net/browse/WD-13624
> Update navigation.yaml with latest changes

- templates/data/opensearch/what-is-opensearch.html
- templates/data/sitemap.xml
- Created /data/opensearch/what-is-opensearch
- There might still be some input required in design
- New folder created for housing this page
- Check if all the requirements are met for new page and it is added to sitemap correctly.
- [Copydoc](https://docs.google.com/document/d/1p_dRRGsePAmoBNCZ-7wO6bUAUzxx8Nnr9NJqITMaVzo/edit#heading=h.ve251si43fmo)
- [Design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=52-2200&t=4pAQid3eF7qF1WNR-0)
- [Demo](https://canonical-com-1311.demos.haus/data/opensearch/what-is-opensearch)
- Check …
> WD-12230 Created /data/opensearch/what-is-opensearch

- templates/contact-us.html
- Updated contact-us page with new address of Canonical office London
- [Copydoc](https://docs.google.com/document/d/1Qxvhl6_kgCDarcem1wcFPQyHk0JEFUP1zIzNsIrT3_Y/edit)
- [Demo](https://canonical-com-1319.demos.haus/contact-us)
Fixes # [WD-13331](https://warthogs.atlassian.net/browse/WD-13331)
[WD-13331]: https://warthogs.atlassian.net/browse/WD-13331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-13331 Updated contact-us page

- Dockerfile
- templates/data/_form-data-opensearch.html
- templates/data/opensearch/index.html
- templates/data/opensearch/managed.html
Added new webpage according to this [copy doc](https://docs.google.com/document/d/19gcIoKEibXTvZCsmtYCSQBMnBUmNUJI6RaLoMHL2_TA/edit) and this [design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=166-4958&t=e5exMaJ2QIAaTFEt-0).
- Open webpage at https://canonical-com-1317.demos.haus/data/opensearch/managed and check if it complies with the copy doc and the design.
Fixes https://warthogs.atlassian.net/browse/WD-12238
> [WD-12238] new webpage at /data/opensearch/managed

- templates/solutions/ubuntu-os/_form-ubuntu-os.html
- templates/solutions/ubuntu-os/index.html
- Built /ubutnu-os page and respective modal
- View the site locally in your web browser at: https://canonical-com-1314.demos.haus/solutions/ubuntu-os
- Compare against [doc](https://docs.google.com/document/d/1X3osSqcm3rWLqYUJr5G4fXEEHCby-j5FEJwClLNx5S4/edit#heading=h.e9t2yuuj3uc1) and [design](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/24.10-Canonical.com%2Fsolutions?node-id=123-2421&m=dev)
- Click on the main CTA's and check form against [doc](https://docs.google.com/document/d/1ne8XUT9GMtMEJZSpv-Uram1-YfOM-GoESeUgvPcG2XQ/edit)
- See that submission goes through as expected
Fixes https://warthogs.atlassian.net/browse/WD-12723
> Build /solutions/ubuntu-os and modal form

- templates/data/opensearch/support.html
- templates/data/sitemap.xml
- Created /data/opensearch/support
- Check if all the requirements are met for the new page.
- [Demo](https://canonical-com-1315.demos.haus/data/opensearch/support)
- [Design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=0-1&t=BSWoNixuloj9DSbO-0)
- [Copydoc](https://docs.google.com/document/d/1ovtXv8RBybw-flvttyqWOzZivUryQMP34T1UGe90HlY/edit)
Fixes # [WD-12234](https://warthogs.atlassian.net/browse/WD-12234)
[WD-12234]: https://warthogs.atlassian.net/browse/WD-12234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> WD-12234 Created /data/opensearch/support

- templates/solutions/ubuntu-os/index.html
- Updated logos and applied copy changes as per [doc](https://docs.google.com/document/d/1X3osSqcm3rWLqYUJr5G4fXEEHCby-j5FEJwClLNx5S4/edit)
- View the site locally in your web browser at: https://canonical-com-1332.demos.haus/solutions/ubuntu-os
Fixes https://warthogs.atlassian.net/browse/WD-13932
> /solutions/ubuntu-os copy updates

- templates/solutions/ubuntu-os/index.html
- Made changes to /solutions/ubuntu-os
- [Demo](https://canonical-com-1338.demos.haus/solutions/ubuntu-os)
- [Copydoc](https://docs.google.com/document/d/1X3osSqcm3rWLqYUJr5G4fXEEHCby-j5FEJwClLNx5S4/edit)
Fixes # [WD-14016](https://warthogs.atlassian.net/browse/WD-14016)
[WD-14016]: https://warthogs.atlassian.net/browse/WD-14016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-14016 CopyUpdate

- templates/data/mongodb/support.html
- templates/data/sitemap.xml
Created /data/mongodb/support
- Perform the checks for the new-webpage.
- [Design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=3-8106&t=Y4hBK1I6bTimfqDu-0)
- [Copydoc](https://docs.google.com/document/d/1XjFTw--fDl7ZpI6LI--UBKkAV4Yiz-gEoo2gcLuVdeA/edit)
- [Demo](https://canonical-com-1340.demos.haus/data/mongodb/support)
Fixes # [WD-12247](https://warthogs.atlassian.net/browse/WD-12247)
[WD-12247]: https://warthogs.atlassian.net/browse/WD-12247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …
> WD-12247 Dev Create /data/mongodb/support

- templates/partners/executive-summit.html
- Update copy and images on /partners/executive-summit based on [copydoc](https://docs.google.com/document/d/15C3k-htvapwp-WTrYQ2SdHBW20Lp9IinpY9mkvo6q3U/edit)
- Go to https://canonical-com-1345.demos.haus//partners/executive-summit and compare against [copydoc](https://docs.google.com/document/d/15C3k-htvapwp-WTrYQ2SdHBW20Lp9IinpY9mkvo6q3U/edit)
Fixes https://warthogs.atlassian.net/browse/WD-14163
> chore: Update copy and images on /partners/executive-summit

- templates/solutions/secure-open-source/index.html
- Update [copy](https://docs.google.com/document/d/1mrvhkrVjCCJE39h96CPG_b_ZHWVN0GHzZ_6TdoudeYs/edit#heading=h.rukg8oj5d0jp) on /solutions/secure-open-source
**You can ignore the images as this should have been made in a page refresh request**
- Check [the demo](https://canonical-com-1349.demos.haus/) match the [copy](https://docs.google.com/document/d/1mrvhkrVjCCJE39h96CPG_b_ZHWVN0GHzZ_6TdoudeYs/edit#heading=h.rukg8oj5d0jp)
Fixes https://warthogs.atlassian.net/browse/WD-14185
> chore: Update copy on /solutions/secure-open-source

- templates/data/mongodb/what-is-mongodb.html
- templates/data/sitemap.xml
Created data/mongodb/what-is-mongodb
Assets are still to be updated
- Perform the checks for the new-webpage.
- [Design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=206-2888&t=PfDFMvTJxAM5v95v-0)
- [Copydoc](https://docs.google.com/document/d/1hET-ylqXq96mOfj4hovqilX5Nl0J8FLw1gkRMJkIjp8/edit#heading=h.gjjixnphncvc)
- [Demo](https://canonical-com-1343.demos.haus/data/mongodb/what-is-mongodb)
Fixes # [WD-12243](https://warthogs.atlassian.net/browse/WD-12243)
[WD-12243]: …
> WD-12243 Dev Create data/mongodb/what-is-mongodb

- templates/data/mongodb/managed.html
- templates/data/sitemap.xml
Created data/mongodb/managed
- Perform the checks for the new-webpage.
- [Design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=5-9238&t=DGhzrunfc5f6o9on-0)
- [Copydoc](https://docs.google.com/document/d/1ZkJA6le_PfFZK8WBDgoUksKlQzX8HgUNL8HNJwWKhv0/edit)
- [Demo](https://canonical-com-1352.demos.haus/data/mongodb/managed)
Fixes # [WD-12252](https://warthogs.atlassian.net/browse/WD-12252)
[WD-12252]: https://warthogs.atlassian.net/browse/WD-12252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> WD-12252 dev create /data/mongodb/managed

- templates/careers/application/_withdrawal-form.html
- templates/careers/application/partial/_assessment.html
- change email prompt text
- fix lint errors
- fix modal "cancel" button
after changes:
before changes:
> update email prompt for candidate page

- static/sass/styles.scss
- templates/openstack/architecture.html
Created /openstack/architecture
/openstack page is yet to be made
- Run through checks for new pages.
- [Design](https://www.figma.com/design/vH19y2J2YqwUfksebSUvTW/OpenStack?node-id=234-4573&node-type=frame&t=iZGNMN0v8P2t4yxm-0)
- [Copydoc](https://docs.google.com/document/d/1i8rjvhw3N2gDA5NXuKEPcftXY95zePjsURmQu4dSgGo/edit)
- [Demo](https://canonical-com-1369.demos.haus/openstack/architecture)
Fixes # [WD-13515](https://warthogs.atlassian.net/browse/WD-13512)
[WD-13515]: …
> WD-13515 Dev Create /openstack/architecture

- templates/data/mongodb/index.html
- templates/data/mysql.html
- Refreshed MySQL
- [Design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=705-1977&node-type=CANVAS&t=t1mHVIAEfPatvrtR-0)
- [Copydoc](https://docs.google.com/document/d/1KQmCfb4ITlYHOAEoHUwxHExf73qkMSWsLHnFPwFWFag/edit)
- [Demo](https://canonical-com-1364.demos.haus/data/mysql)
Fixes # [WD-13776](https://warthogs.atlassian.net/browse/WD-13776)
[WD-13776]: https://warthogs.atlassian.net/browse/WD-13776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Wd 13776 Dev Refresh /data/mysql 

- tests/test_application.py
- webapp/app.py
- webapp/application.py
- webapp/google_calendar.py
- webapp/greenhouse.py
- webapp/requests_session.py
- local sessions (except search views, blog views, charmhub)
- local cipher
> Use local sessions and cipher

- templates/projects/directory.html
Update Ubuntu Desktop Installer owner to Oliver Smith.
> Update desktop installer contact to Oliver Smith

- navigation.yaml
- Add copy doc to navigation.yaml
- Update links to `/data` as they now exist on canonical.com
- Open [demo link](https://canonical-com-1377.demos.haus/)
- Check the links work as expected
Fixes https://warthogs.atlassian.net/browse/WD-15179
> chore: Update links in navigation.yaml & add link to copydoc

- webapp/app.py
- log application submit errors
> [WD-14816] log submit application errors

- secondary-navigation.yaml
- templates/data/_form-data-relational-dbs.html
- templates/macros/quote_wrapper.jinja
- templates/solutions/telco/5g-core.html
- templates/solutions/telco/_form-telco-5g-core.html
- Create new webpage for /solutions/telco/5g-core
- Create dynamic form for contact CTA
- Added /macros/quote_wrapper.jinja from Vanilla, the file is currently being pasted manually but will be able to import from Vanilla directly once it is released
- Add secondary navigation for Telco bubble
- Go to https://canonical-com-1380.demos.haus/solutions/telco/5g-core
- Check that content matches [copy doc](https://docs.google.com/document/d/1h5A07aTGTZl5VfoiX2UwIpb-bHtFr7gBVUejN-uAf-Q/edit) and design matches [Figma](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/24.10-Canonical.com%2Fsolutions?node-id=458-7435&node-type=instance&m=dev)
- Check that contact us modal form works and submits to Marketo successfully
- Check with medium and small screens
Fixes …
> Create /solutions/telco/5g-core webpage

- templates/careers/hiring-process/index.html
- Update copy on /hiring-process based on [copydoc](https://docs.google.com/document/d/1j-G0LCapJ1zRnNgQeoC0_rh15N6ICdpDy7M1tubQuoo/edit)
- Check out [the demo](https://canonical-com-1382.demos.haus/)
- Check the changes match the [copydoc](https://docs.google.com/document/d/1j-G0LCapJ1zRnNgQeoC0_rh15N6ICdpDy7M1tubQuoo/edit)
Fixes https://warthogs.atlassian.net/browse/WD-15340
> chore: Update copy on /hiring-process

- templates/solutions/secure-open-source/index.html
- Fix download link on /solutions/secure-open-source
- Go to https://canonical-com-1388.demos.haus/solutions/secure-open-source
- Check that the download link matches [copy doc](https://docs.google.com/document/d/1mrvhkrVjCCJE39h96CPG_b_ZHWVN0GHzZ_6TdoudeYs/edit#heading=h.jymyfsrbwrwd)
Fixes [WD-15636](https://warthogs.atlassian.net/browse/WD-15636)
[WD-15636]: https://warthogs.atlassian.net/browse/WD-15636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix download link

- secondary-navigation.yaml
- templates/data/postgresql/managed.html
Added a new page for Managed PostgreSQL
[Design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=1716-33705&node-type=frame&t=6rKkPmT85JT1F2Qv-0)
- Go to https://canonical-com-1395.demos.haus/data/postgresql/managed
- Compare with [copy doc](https://docs.google.com/document/d/10YAubAK42OWeaAXY2Ib9OE1q65xyP741R4bnnAA9GCk/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-15582
> Add managed postgresql page

- templates/data/_form-data-kafka.html
- templates/data/kafka.html
- Applied changes as per [doc](https://docs.google.com/document/d/1bfo97XdFdKlzrMcMoRxiTdzt_bPVndx6j55IPsapuAE/edit) and [design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=1399-1827&node-type=canvas&m=dev)
- Drive by:
- Removed placeholder text from corresponding form
- View the site locally in your web browser at: https://canonical-com-1392.demos.haus/data/kafka
- Check against doc and design 
- Be sure to check smaller screens as well
Fixes https://warthogs.atlassian.net/browse/WD-15062
> feat: /data/kafka refresh

- templates/openstack/index.html
**Note: form will be added in separate PR**
- Built page as per [doc](https://docs.google.com/document/d/1v1G2y465b_VYVUG9TIV-A_X1dU4kg5Zvrwd2latidCk/edit?tab=t.0) and [design](https://www.figma.com/design/vH19y2J2YqwUfksebSUvTW/OpenStack?node-id=224-7535&node-type=instance&m=dev)
- View the site locally in your web browser at: https://canonical-com-1394.demos.haus/openstack
Fixes https://warthogs.atlassian.net/browse/WD-14071
> feat: /openstack landing page

- secondary-navigation.yaml
- templates/solutions/open-ran/index.html
- templates/solutions/telco/index.html
- templates/solutions/telco/open-ran.html
- Built new page as per [doc](https://docs.google.com/document/d/1rqBh8oVNeDk-fg1jg-7-SErLgmi0naEzP4r50JhJUb4/edit?tab=t.0) and [design](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/24.10-Canonical.com%2Fsolutions?node-id=703-7693&node-type=instance&m=dev)
- Drive by:
- Updated spacing on /solutions/telco hero per UX request  
- View the site locally in your web browser at: https://canonical-com-1400.demos.haus/solutions/telco/open-ran
- https://canonical-com-1400.demos.haus/solutions/telco and see that the hero spacing has been updated
Fixes https://warthogs.atlassian.net/browse/WD-14843
> feat: /solutions/open-ran build

- secondary-navigation.yaml
- templates/data/kafka/what-is-kafka.html
- Built page as per [doc](https://docs.google.com/document/d/1IThZcfKZcv-ArqU_0n8A181AGkQPUn_Iq1O4sqk5GTs/edit?tab=t.0) and [design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=2135-30990&node-type=instance&m=dev) 
- View the site locally in your web browser at: https://canonical-com-1408.demos.haus/data/kafka/what-is-kafka
Fixes https://warthogs.atlassian.net/browse/WD-15054
> feat: /data/kafka/what-is-kafka build

- package.json
- secondary-navigation.yaml
- templates/data/kafka/support.html
- yarn.lock
- Built page as per [doc](https://docs.google.com/document/d/1eM-xPqx1CtoxSg4aOHlY3QRPu5L3o-jQPkc_q1CAr10/edit?tab=t.0) and [design](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=2124-29581&node-type=frame&m=dev)
- View the site locally in your web browser at: https://canonical-com-1411.demos.haus/data/kafka/support
- Check against doc and design 
Fixes https://warthogs.atlassian.net/browse/WD-15042
> feat: /data/kafka/support build

- templates/data/mongodb/support.html
- Updates `/data/mongodb/support` according to [this doc](https://docs.google.com/document/d/1XjFTw--fDl7ZpI6LI--UBKkAV4Yiz-gEoo2gcLuVdeA/edit?tab=t.0)
- Changes `contact us` links
- Adds `Multiple packaging formats` section
- Check the demo at https://canonical-com-1423.demos.haus/data/mongodb/support
- Check that it matches the [copy doc](https://docs.google.com/document/d/1XjFTw--fDl7ZpI6LI--UBKkAV4Yiz-gEoo2gcLuVdeA/edit?tab=t.0)
Fixes [WD-16794](https://warthogs.atlassian.net/browse/WD-16794)
[WD-16794]: https://warthogs.atlassian.net/browse/WD-16794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> copy update: /data/mongodb/support

- templates/openstack/_form-openstack.html
- templates/openstack/index.html
* Create openstack contact us modal form
- Go to https://canonical-com-1433.demos.haus/openstack#get-in-touch
- Check that form matches [copy doc](https://docs.google.com/document/d/1b1eH239vclLdZ7cE3ZOWBYbCu9OBff4WqRBD0dQPSiA/edit?tab=t.0)
- Check that form submission goes through Marketo
Fixes [WD-15830](https://warthogs.atlassian.net/browse/WD-15830)
[WD-15830]: https://warthogs.atlassian.net/browse/WD-15830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Create Openstack contact form

- .github/.jira_sync_config.yaml
Specify a new Jira epic link for 25.04 GH issues in Jira integration configuration file
> Update Jira epic in .jira_sync_config.yaml file

- templates/data/opensearch/support.html
- Updates /data/opensearch/support to add "multiple packaging formats" section
- View the site locally in your web browser at: https://canonical-com-1425.demos.haus/data/opensearch/support
- Check that /data/opensearch/support matches the [copy doc](https://docs.google.com/document/d/1ovtXv8RBybw-flvttyqWOzZivUryQMP34T1UGe90HlY/edit?usp=sharing)
Fixes [WD-16793](https://warthogs.atlassian.net/browse/WD-16793)
[WD-16793]: https://warthogs.atlassian.net/browse/WD-16793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> copy update: /data/opensearch/support

- templates/openstack/architecture.html
- Updated copy as per [doc](https://docs.google.com/document/d/1i8rjvhw3N2gDA5NXuKEPcftXY95zePjsURmQu4dSgGo/edit?tab=t.0)
- View the site locally in your web browser at: https://canonical-com-1453.demos.haus/openstack/architecture
- Check against doc
Fixes https://warthogs.atlassian.net/browse/WD-17511
> feat: /openstack/architecture copy update

- templates/solutions/infrastructure/index.html
- Updated the [/solutions/infrastructure](https://canonical-com-1452.demos.haus/solutions/infrastructure) page according to the [copy doc](https://docs.google.com/document/d/1xbuIA53HKrMatjuiNQwf1ORwLvNXFEF0UqGTbB6sXL0/edit?tab=t.0).
- Open https://canonical-com-1452.demos.haus/solutions/infrastructure
- Check that all the recent suggestions in the copy doc linked above have been addressed
Fixes [WD-17391](https://warthogs.atlassian.net/browse/WD-17391)
[WD-17391]: https://warthogs.atlassian.net/browse/WD-17391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(/solutions/infrastructure): copy updates and conversion BE -> AE [WD-17391]

- templates/lxd/manage.html
- Fixed links
- Fixed minor code issues
- [Copydoc](https://docs.google.com/document/d/1doGyKYSTOsX8dHvQ6W9W2U_pHQY6yfiq1bqSAJyredQ/edit?tab=t.0)
- [Demo](https://canonical-com-1465.demos.haus/lxd/manage)
Fixes # [WD-17849](https://warthogs.atlassian.net/browse/WD-17849)
[WD-17849]: https://warthogs.atlassian.net/browse/WD-17849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-17849 Copy-Update /lxd/manage

- templates/openstack/architecture.html
- Update based on changes in [the copydoc](https://docs.google.com/document/d/1i8rjvhw3N2gDA5NXuKEPcftXY95zePjsURmQu4dSgGo/edit?tab=t.0)
- Open [demo](https://canonical-com-1464.demos.haus/openstack/architecture)
- Check the changes match [the copydoc](https://docs.google.com/document/d/1i8rjvhw3N2gDA5NXuKEPcftXY95zePjsURmQu4dSgGo/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-17511
> chore: Apply copy changes to /openstack/architecture

- templates/careers/company-culture/index.html
- Updates /careers/company-culture to changes some numbers and switch from British to American English
- View the site locally in your web browser at: https://canonical-com-1461.demos.haus/careers/company-culture
- Check that /careers/company-culture matches the [copy doc](https://docs.google.com/document/d/1PAeP_ZO4JzSBCi-fRp6F7SYtSSRY-4DcWLUf9HJaMxs/edit?usp=sharing)
Fixes [WD-17731](https://warthogs.atlassian.net/browse/WD-17731)
[WD-17731]: https://warthogs.atlassian.net/browse/WD-17731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> copy update: /careers/company-culture

- templates/data/spark/what-is-spark.html
- Replace `Rock` with `OCI-compliant`
- Go to https://canonical-com-1473.demos.haus/data/spark/what-is-spark
- Compare page against [copy doc](https://docs.google.com/document/d/1pyX-BOXmIZY6_8imIft1SAp1-S0i8bGYWEo5zoVEgQw/edit?tab=t.0)
Fixes [WD-17927](https://warthogs.atlassian.net/browse/WD-17927)
[WD-17927]: https://warthogs.atlassian.net/browse/WD-17927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WD-17927] Copy update on data/spark

- templates/solutions/telco/5g-edge.html
Copy update on the /solutions/telco/5g-edge page
- Go to  /solutions/telco/5g-edge or https://canonical-com-1462.demos.haus/solutions/telco/5g-edge 
- Compare page against [copy doc](https://docs.google.com/document/d/1K_aHQNapkDgLdCNpLsB1oEeHxo68TMDJoU-iDYlI7lU/edit?tab=t.0)
Fixes #https://warthogs.atlassian.net/browse/WD-17652
> WD-17652 Copy update on the /solutions/telco/5g-edge page

- webapp/greenhouse.py
When a job post is accessed via the /careers/{job_post_id} endpoint, we currently only check the “Canonical” board for this job post. In cases where the job post is instead on the “Canonical - Jobs” board, this endpoint will return a 404. We do not want to list all jobs on the “Canonical - Jobs” board as there are 100s of duplicates, but if one is requested via the above endpoint we do not want to return a 404 either. This change is to update the site to check the “Canonical - Jobs” board as well to avoid these 404 scenarios.
- Check "Canonical - Jobs" board as well for directly accessed job posts
- View job post which exists on "Canonical - Jobs": http://localhost:8002/careers/6456955
- Ensure that the job post …
> check canonicaljobs board as well for directly accessed job post

- templates/solutions/telco/index.html
- Added link for security declaration PDF.
- Open the [Demo](https://canonical-com-1483.demos.haus/solutions/telco) in your web browser.
- Make sure the content matches the [Copydoc](https://docs.google.com/document/d/1yRSYYY8_UNfZzdLcp_fYxi-STGm40o3UP9vD2vW6brw).
Fixes #[WD-17945](https://warthogs.atlassian.net/browse/WD-17945)
[WD-17945]: https://warthogs.atlassian.net/browse/WD-17945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-17945 Copy updates [canonical.com/solutions/telco]

- static/files/forms-data.json
- templates/solutions/open-source-security/cyber-resilience-act/index.html
Created Page on CRA
- Visit [ /solutions/open-source-security/cyber-resilience-act](https://canonical-com-1488.demos.haus/solutions/open-source-security/cyber-resilience-act)
- Compare with https://www.figma.com/design/8JrAyKnWMU9FPJE0zJT2gu/Canonical.com%2Fsolutions%2Fopen-source-security?node-id=322-3837&node-type=frame&t=s7VX6L8CVxaBok0z-0
- Also correlate with https://docs.google.com/document/d/13VaiP6GGkGB4mE01bIqJ3cg8MfQXulNs9m3cmYb20HQ/edit
Fixes [#WD-17296](https://warthogs.atlassian.net/browse/WD-17296)
> WD-17296-dev-create-solutions-open-source-security-cyber-resilience-act

- templates/solutions/open-source-security/index.html
- Updated the [/solutions/open-source-security](https://canonical-com-1495.demos.haus/solutions/open-source-security) page according to the [copy doc](https://docs.google.com/document/d/1mrvhkrVjCCJE39h96CPG_b_ZHWVN0GHzZ_6TdoudeYs/edit?tab=t.0).
- Open https://canonical-com-1495.demos.haus/solutions/open-source-security
- Check that all the recent suggestions in the copy doc linked above have been addressed
Fixes [WD-18099](https://warthogs.atlassian.net/browse/WD-18099)
[WD-18099]: https://warthogs.atlassian.net/browse/WD-18099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(open-source-security): EU Cyber Resilience Act updates [WD-18099]

- templates/company/index.html
- Add anchor ID to company values
- Go to https://canonical-com-1496.demos.haus/company#values
- See that it links to "Company values" section
Fixes [WD-18131](https://warthogs.atlassian.net/browse/WD-18131)
[WD-18131]: https://warthogs.atlassian.net/browse/WD-18131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add anchor id to company values

- konf/site.yaml
Enable recaptcha. (RECAPTCHA_ENABLED="true")
> RECAPTCHA_ENABLED="true"

- templates/solutions/open-source-security/cyber-resilience-act/index.html
- Copy update on /solutions/open-source-security/cyber-resilience-act
- Go to /solutions/open-source-security/cyber-resilience-act
- Compare page against [copy doc](https://docs.google.com/document/d/13VaiP6GGkGB4mE01bIqJ3cg8MfQXulNs9m3cmYb20HQ/edit)
Fixes #https://warthogs.atlassian.net/browse/WD-18098
> Copy update on /solutions/open-source-security/cyber-resilience-act

- templates/solutions/ai/index.html
Updates Azure and Google Cloud logos.
Copy doc: https://docs.google.com/document/d/1AtAApqxX9cbWf4a3cakEYbk7OoTfdBBi7FlA3WZz5ZM/edit?tab=t.0#heading=h.whd96u4iiwsb
- Open demo: https://canonical-com-1510.demos.haus/solutions/ai
- Go to "Run on any cloud" section
- Check updated logos (compare with links in copy doc)
Fixes https://warthogs.atlassian.net/browse/WD-18115
> Update partner logos on solutions/ai page

- templates/case-study/_case-study-card.html
- templates/case-study/_case-study-modal.html
- templates/case-study/base_case-study.html
- templates/case-study/esa.html
- templates/case-study/grundium-ubuntu-pro-for-devices.html
- templates/case-study/index.html
- templates/case-study/lucid-aws-fedramp-compliance-case-study.html
- templates/case-study/sbi-bits.html
- templates/case-study/ubuntu-pro-support-for-games-developer.html
- templates/macros/_macros-cta.jinja
- templates/macros/_macros-highlights.jinja
- templates/macros/_macros-image.jinja
- templates/macros/_macros-text-list.jinja
- templates/macros/_macros-text.jinja
- templates/solutions/open-source-security/cyber-resilience-act/index.html
- Move case study macros from u.com
- Move case studies from u.com
- Go to https://canonical-com-1508.demos.haus/case-study/esa, see that it loads as expected and compare with https://ubuntu.com/case-study/esa
- Repeat with
- https://canonical-com-1508.demos.haus/case-study/grundium-ubuntu-pro-for-devices and https://ubuntu.com/case-study/grundium-ubuntu-pro-for-devices
- https://canonical-com-1508.demos.haus/case-study/lucid-aws-fedramp-compliance-case-study and https://ubuntu.com/case-study/lucid-aws-fedramp-compliance-case-study
- https://canonical-com-1508.demos.haus/case-study/sbi-bits and https://ubuntu.com/case-study/sbi-bits
- https://canonical-com-1508.demos.haus/case-study/ubuntu-pro-support-for-games-developer and https://ubuntu.com/case-study/ubuntu-pro-support-for-games-develo …
> feat: Move case studies and macros from u.com

- navigation.yaml
- Update meganav to US spelling
- Compare meganav against [copy doc](https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit?tab=t.0)
- Go to https://canonical-com-1517.demos.haus/
Fixes #https://warthogs.atlassian.net/browse/WD-18253
> Update meganav to US spelling

- requirements.txt
- templates/case-study/esa.html
- templates/case-study/grundium-ubuntu-pro-for-devices.html
- templates/case-study/index.html
- templates/case-study/lucid-aws-fedramp-compliance-case-study.html
- templates/case-study/sbi-bits.html
- templates/case-study/ubuntu-pro-support-for-games-developer.html
- webapp/app.py
- Add language and clear filter option on index page
- Clone this branch locally and go to /case-study
- Make sure you have `DISCOURSE_API_KEY` and `DISCOURSE_API_USERNAME` set in ur local env, if you need the API key and username let me know
- Select a language from filter dropdown
- Check that it only shows case studies in that language, clear filter and check that it shows all case studies
Fixes [WD-17516](https://warthogs.atlassian.net/browse/WD-17516)
[WD-17516]: https://warthogs.atlassian.net/browse/WD-17516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Add language filter function for case studies

- static/sass/_pattern_navigation.scss
- Top nav is now sticky
- Open this [demo]()
- Scroll and make sure the top nav is sticky
Fixes #[WD-16811](https://warthogs.atlassian.net/browse/WD-16811)
[WD-16811]: https://warthogs.atlassian.net/browse/WD-16811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WD-16811] Made top nav sticky like on u.com

- navigation.yaml
- templates/solutions/iot-and-devices/form-data.json
- templates/solutions/iot-and-devices/index.html
Create /solutions/iot-and-devices page.
[Demo](https://canonical-com-1494.demos.haus/solutions/iot-and-devices)
[Doc](https://docs.google.com/document/d/1htb7rb55Ks5ZHn7RLzoeU51nZpWOX6YC10CfZ8UJxDM/edit?tab=t.0)
[Form](https://docs.google.com/document/d/1DSxDNpRZKQRH8BGrtkSl7rHuUFKkxDaaB81eZCAAJqc/edit?tab=t.0)
[Figma](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/25.04-Canonical.com%2Fsolutions?node-id=1702-9242&t=PL7R02O6IjWbmZo6-0)
[Assets](https://assets.ubuntu.com/manager?tag=solutions-iot-devices-assets&page=1)
- [List additional steps to QA the …
> copy: create /solutions/iot-and-devices page. WD-17347

- templates/solutions/iot-and-devices/index.html
- Fix minor typo as described in [copy doc](https://docs.google.com/document/d/1htb7rb55Ks5ZHn7RLzoeU51nZpWOX6YC10CfZ8UJxDM/edit?disco=AAABdCdwed4)
- Go to https://canonical-com-1544.demos.haus/solutions/iot-and-devices
- Check that typo is fixed
Fixes [WD-18957](https://warthogs.atlassian.net/browse/WD-18957)
[WD-18957]: https://warthogs.atlassian.net/browse/WD-18957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Fix typo on /solutions/iot-and-devices

- templates/case-study/episensor.html
- templates/macros/_macros-quote-wrapper.jinja
- Add new case study
- Old PR: https://github.com/canonical/ubuntu.com/pull/14664
- View the site locally in your web browser at: https://canonical-com-1542.demos.haus/case-study/episensor
- Make sure that the [copy update](https://docs.google.com/document/d/1NxBHg59oiH-ry7bgMZX-xDxvWbC9IyqHYMei-bQciU4/edit?tab=t.0#heading=h.eto59uxtlv76) and [figma design](https://www.figma.com/design/rEDsQqLe8SfnvoxCcXJYLr/Case-studies?node-id=258-855&m=dev) are applied
Fixes WD-18130
[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)
> Add episensor case study

- templates/case-study/airlock-digital-ubuntu-pro-azure-case-study.html
Adds Airlock Digital case study
[Figma](https://www.figma.com/design/rEDsQqLe8SfnvoxCcXJYLr/Case-studies?node-id=546-1681&t=hg7x71QOGyF2Mole-1)
[Copy doc](https://docs.google.com/document/d/1kFXfHPKZCBmB6_SvKYyjrZ00FHgulxBNb3fxz443Kvs/edit?tab=t.0)
- Open [demo](https://canonical-com-1557.demos.haus/case-study/airlock-digital-ubuntu-pro-azure-case-study)
- Compare against Figma and Copy doc (linked above)
Fixes WD-19036
> Add Airlock Digital case study

- templates/case-study/airlock-digital-ubuntu-pro-azure-case-study.html
- Update 4th pull quote text according to the [copy doc](https://docs.google.com/document/d/1kFXfHPKZCBmB6_SvKYyjrZ00FHgulxBNb3fxz443Kvs/edit?tab=t.0)
- Go to the [Airlock case study](https://canonical-com-1558.demos.haus/case-study/airlock-digital-ubuntu-pro-azure-case-study)
- Scroll down to the **Benefits** section
Fixes [WD-19324](https://warthogs.atlassian.net/browse/WD-19324)
**Before:**
**After:**
[WD-19324]: https://warthogs.atlassian.net/browse/WD-19324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WD-19324] Copy Update - Airlock case study

- templates/careers/hiring-process/index.html
- Visit [/careers/hiring-process](https://canonical-com-1560.demos.haus/careers/hiring-process)
- Make sure the header image is changed
- Make sure the team member spotlight at the last section is modified.
- Copy doc: https://docs.google.com/document/d/1j-G0LCapJ1zRnNgQeoC0_rh15N6ICdpDy7M1tubQuoo/edit?tab=t.0
Fixes [#WD-19331](https://warthogs.atlassian.net/browse/WD-19331)
> update hiring process page

- requirements.txt
- templates/data/mysql/form-data.json
- templates/data/mysql/index.html
- templates/data/mysql/managed.html
- templates/data/postgresql/managed.html
- create /data/mysql/managed page
- replace /data/mysql form with JSON file
[Demo](https://canonical-com-1531.demos.haus/data/mysql/managed)
[Doc](https://docs.google.com/document/d/14GVPv7DKHBMpgW6NL0yK6rOsTdI9OREN5ZaY20YsKb4/edit?tab=t.0)
[Figma](https://www.figma.com/design/uJUwbUAGDog4KCMivrMpnl/24.10-Data-Fabric?node-id=3042-23917&t=4M0EWOk9RvZ8bvE4-0)
[Assets](https://assets.ubuntu.com/manager?tag=data-mysql-managed)
Fixes …
> copy: create /data/mysql/managed page. WD-17656

- templates/case-study/unibap-space-computing.html
- Added [/case-study/unibap-space-computing](https://canonical-com-1566.demos.haus/case-study/unibap-space-computing) page according to the [copy doc](https://docs.google.com/document/d/1yWSxNQuymbzNL8ZU0AMEBgMTIpAMNu6CAa_Pr2dSwsc/edit?tab=t.0).
- Open https://canonical-com-1566.demos.haus/case-study/unibap-space-computing
- Check that the case study page looks as expected
Fixes [WD-19083](https://warthogs.atlassian.net/browse/WD-19083)
[WD-19083]: https://warthogs.atlassian.net/browse/WD-19083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(case-study): add unibap space computing case study

- templates/partners/executive-summit.html
Updated event date.
Compare with [copy doc](https://docs.google.com/document/d/15C3k-htvapwp-WTrYQ2SdHBW20Lp9IinpY9mkvo6q3U/edit?tab=t.0).
https://warthogs.atlassian.net/browse/WD-19465
> Copy update: /partners/executive-summit

- templates/case-study/unibap-space-computing.html
- Updated visuals of the [Unibap case study](https://canonical-com-1571.demos.haus/case-study/unibap-space-computing) - check the Jira ticket linked below for context and links.
- Updated titles - check linked Jira comment below.
- Go to https://canonical-com-1571.demos.haus/case-study/unibap-space-computing
- Check that the images are updated and placed according to the Figma [file](https://www.figma.com/design/rEDsQqLe8SfnvoxCcXJYLr/Case-studies?node-id=553-2272&t=A0lUCARXI7eL74td-1), and titles are updated according to this [comment](https://warthogs.atlassian.net/browse/WD-19596?focusedCommentId=690201)
Fixes [WD-19596](https://warthogs.atlassian.net/browse/WD-19596)
[WD-19596]: https://warthogs.atlassian.net/browse/WD-19596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> fix(case-study): update images for the unibap case study [WD-19596]

- templates/solutions/sovereign-cloud/index.html
- Copy update on solutions/sovereign-cloud
- check https://canonical-com-1583.demos.haus/solutions/sovereign-cloud and compare it to [the copy doc](https://docs.google.com/document/d/1XvdgVN87yqI9xOtFBaK9Z_Au8PTeHlQICzlYrgUKxuQ/edit?tab=t.0)
Fixes WD-19764
> Copy update on solutions/sovereign-cloud WD-19764

- templates/index.html
- Change home page spelling to US
- Make sure the suggested changes from the [copydoc](https://docs.google.com/document/d/1GNa1FaTkARdrVwYgHXf5H-6sqOLjkJENDistDDcsi4o/edit?tab=t.0) are applied
Fixes WD-19341
> US spelling change

- templates/case-study/esa.html
Update /case-study/esa template.
[Doc](https://docs.google.com/document/d/1jc5DY4-9pDYQC04Egdt0If4_jrYn1mIBDwhJfILO46w/edit?tab=t.0)
[Demo](https://canonical-com-1586.demos.haus/case-study/esa)
Fixes [#WD-19769](https://warthogs.atlassian.net/browse/WD-19769)
> copy: update /case-study/esa. WD-19769

- templates/contact-us.html
Update the address for Canonical Shanghai and Beijing offices.
- Visit https://canonical-com-1581.demos.haus/contact-us
- Should show the updated addresses with the correct maps link as mentioned in the [copy doc](https://docs.google.com/document/d/1Qxvhl6_kgCDarcem1wcFPQyHk0JEFUP1zIzNsIrT3_Y/edit?tab=t.0#heading=h.x34oyagq7emg)
Fixes [WD-19673](https://warthogs.atlassian.net/browse/WD-19673)
[WD-19673]: https://warthogs.atlassian.net/browse/WD-19673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Wd 19673 please help to update beijing shanghai office new address in canonical website thanks https canonical com contact us

- templates/solutions/iot-and-devices/index.html
- Replace image 
Before
After
- Go to https://canonical-com-1587.demos.haus/solutions/iot-and-devices
Fixes #https://warthogs.atlassian.net/browse/WD-19879
> Replace image with diagram on /solutions/iot-and-devices

- templates/solutions/infrastructure/index.html
- Update content based on [copydoc](https://docs.google.com/document/d/1xbuIA53HKrMatjuiNQwf1ORwLvNXFEF0UqGTbB6sXL0/edit?tab=t.0)
- Open [the demo](https://canonical-com-1594.demos.haus/solutions/infrastructure)
- Check the changes match the [copydoc](https://docs.google.com/document/d/1xbuIA53HKrMatjuiNQwf1ORwLvNXFEF0UqGTbB6sXL0/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-19763
> chore: Update content on /solutions/infrastructure

- templates/solutions/iot-and-devices/index.html
- Added new link
- Open the [demo](https://canonical-com-1611.demos.haus/solutions/iot-and-devices)
- Compare with the [copydoc](https://docs.google.com/document/d/1htb7rb55Ks5ZHn7RLzoeU51nZpWOX6YC10CfZ8UJxDM/edit?tab=t.0)
Fixes [WD-20365](https://warthogs.atlassian.net/browse/WD-20365)
[WD-20365]: https://warthogs.atlassian.net/browse/WD-20365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: copy update

- static/js/microcloud-slider.js
- static/sass/styles.scss
- templates/microcloud/resources.html
Update /microcloud/resources
- visit https://canonical-com-1612.demos.haus/microcloud/resources
- compare with https://www.figma.com/design/hzQYJM9Tui4wpmyZC0k0WS/23.10-C.com---MicroCloud-Rebranding?node-id=710-5750&t=GYLtA45pEBzLShc4-0
- copy doc: https://docs.google.com/document/d/1ffTxn2ymKrWRPUjjx6cN0-OA6rlIuX0YaVbFQHcpsTM/edit?tab=t.0
Fixes #
> Wd 19232 dev web page refresh update microcloud resources

- templates/microcloud/resources.html
Small link change on microcloud resources
- https://canonical-com-1617.demos.haus/microcloud/resources
- Check link with the comment in the ticket
Fixes [#WD-19232](https://warthogs.atlassian.net/browse/WD-19232)
> Small link change on microcloud resources

- templates/contact-us.html
- Updated contact section details
- [Copy Doc](https://docs.google.com/document/d/1Qxvhl6_kgCDarcem1wcFPQyHk0JEFUP1zIzNsIrT3_Y/edit?tab=t.0)
- Go to `http://0.0.0.0:8002/contact-us` or https://canonical-com-1621.demos.haus/contact-us
- Check the legal section and compare the text and title against the [copy doc](https://docs.google.com/document/d/1Qxvhl6_kgCDarcem1wcFPQyHk0JEFUP1zIzNsIrT3_Y/edit?tab=t.0)
Fixes #[WD-20748](https://warthogs.atlassian.net/browse/WD-20748)
[WD-20748]: https://warthogs.atlassian.net/browse/WD-20748?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
> chore: update legal section copy

- konf/site.yaml
- Added sitemaps secret variable
- Check that the demo runs
Fixes #
> chore: Update site.yaml

- templates/solutions/telco/5g-core.html
- templates/solutions/telco/5g-edge.html
- templates/solutions/telco/open-ran.html
- Fixed stale form import throwing 404s
- Check every page in this bubble and see that all load as expected: https://canonical-com-1659.demos.haus/solutions/telco
Reported on [sentry](https://sentry.is.canonical.com/canonical/canonical-com/issues/100100/?referrer=alert_email)
> fix: Telco form import

- templates/solutions/ubuntu-os/_form-ubuntu-os.html
- templates/solutions/ubuntu-os/index.html
- Updated hero text
- Added link
- US Englished some words
- Visit https://canonical-com-1624.demos.haus/solutions/ubuntu-os
- Compare to the [copy doc suggested changes](https://docs.google.com/document/d/1X3osSqcm3rWLqYUJr5G4fXEEHCby-j5FEJwClLNx5S4/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-20563
> feat: update /solutions/ubuntu-os

- templates/careers/application/index.html
- Updated the hiring video link to work with the CSP
- I have QAed
- If you want to double check load a candidates page from the written interview stage
> Update hiring video link

- templates/careers/application/index.html
> Fix all the hiring videos

- build.js
- navigation.yaml
- static/js/active-nav-scroll.js
- static/sass/styles.scss
- templates/solutions/form-data.json
- templates/solutions/index.html
- Developed solutions landing page
- Created an active navigation that highlights the corresponding section on scroll.
- Added logic for accordion on smaller screens.
- Create contact form as well.
- [Design](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/canonical.com-solutions?node-id=2440-1849&p=f&t=J0hDd1klqbIavtlA-0)
- [Demo](https://canonical-com-1640.demos.haus/solutions)
- [Copydoc](https://docs.google.com/document/d/1vdnlbFSCidiNBXZ1zVKHWNIv1kl6C0vMmQAMYfz3yhU/ed …
> Wd 20030 dev webpage webpage solutions landing page

- navigation.yaml
- Updated the Solutions nav preview links and images
- Select the "Solutions" link on the navigation and verify that the changes match the [copy doc](https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit?tab=t.0#heading=h.66b5xdgm390p) and [figma file](https://www.figma.com/design/p0y7lHJ7edLIeSXM1qbpRZ/23.10-C.com---U.com---Navigation?node-id=325-2294&t=I233qchuR3F2Uow4-0).
[WD-20506](https://warthogs.atlassian.net/browse/WD-20506)
Before change:
After change:
[WD-20506]: https://warthogs.atlassian.net/browse/WD-20506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Dev refresh: Update Solutions nav preview links

- .github/workflows/sitemap.yaml
- konf/site.yaml
- Update `SITEMAP_SECRET` in `konf.yaml`
Fixes #
> fix: Update sitemap action

- .github/workflows/sitemap.yaml
> chore: Remove trailing slash

- templates/solutions/iot-and-devices/index.html
- Added the static banner to the /solutions/iot-and-devices page
- Open the demo and go to /solutions/iot-and-devices
- Check that the link works on the notification
Fixes https://warthogs.atlassian.net/browse/WD-21644
> WD-21644 - 20.04 EOL banner

- templates/solutions/telco/5g-core.html
Copy update based on [copy doc](https://github.com/canonical/canonical.com/pull/1672#issue-3024385727)
- Open [demo](https://canonical-com-1672.demos.haus/solutions/telco/5g-core#:~:text=Cloudify%20your%20data%20centre)
- Review page against the comments in the [copy doc](https://github.com/canonical/canonical.com/pull/1672#issue-3024385727)
Fixes WD-21688
> chore: Update copy of telco 5G core page

- templates/solutions/telco/index.html
- Run the project locally
- Visit http://0.0.0.0:8002/solutions/telco
- See that the latest changes in the [copy doc](https://docs.google.com/document/d/1yRSYYY8_UNfZzdLcp_fYxi-STGm40o3UP9vD2vW6brw/edit?tab=t.0) have been incorporated
https://warthogs.atlassian.net/browse/WD-21695
> copy update: telco/solutions

- templates/case-study/unibap-space-computing.html
- templates/macros/_macros-cta.jinja
- added "Access free trial" cta
- View the site locally in your web browser at: https://canonical-com-1675.demos.haus/case-study/unibap-space-computing
- check against [copy doc](https://docs.google.com/document/d/1yWSxNQuymbzNL8ZU0AMEBgMTIpAMNu6CAa_Pr2dSwsc/edit?tab=t.0#heading=h.4tjfso5hx6tw) and [design suggestions](https://warthogs.atlassian.net/browse/WD-21626)
https://warthogs.atlassian.net/browse/WD-21626
> feat: Update https://canonical.com/case-study/unibap-space-computing

- templates/company/index.html
Updated link to browse customer stories.
Compare with [copy doc](https://docs.google.com/document/d/19TIwT-GU5wADQmohicj14MnpHEqNqp0422WLunFsbJU/edit?tab=t.0).
https://warthogs.atlassian.net/browse/WD-21710
> Copy update: /company

- templates/solutions/index.html
1. Added a new [meta image](https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,w_2748,h_1146/https://assets.ubuntu.com/v1/c55ce9f5-ubuntu%20platform.png)
2. Added a "read the story" link for Lucid Software
3. Updated the IBM cloud partner logo
4. Lowercased "solutions" in "Managed solutions"
5. Added a link to the new [consulting page](https://canonical.com/consulting). 
- Open [demo](https://canonical-com-1690.demos.haus/solutions)
- Compare demo to [copydoc](https://docs.google.com/document/d/1vdnlbFSCidiNBXZ1zVKHWNIv1kl6C0vMmQAMYfz3yhU/edit?tab=t.0) and [wireframe](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/canonical.com-solutions?node-id=2625-7045&t=iCKkA7WjuWaodR87-4).
- Verify the meta image has been set properly. One way to do this is to send the …
> copy update: update `/solutions`

- templates/consulting/index.html
Removed unnecessary space before fullstop in metadata
> WD-22065 Remove unnecessary space before fullstop in metadata

- secondary-navigation.yaml
- templates/dqlite/docs/document.html
- templates/dqlite/docs/search-results.html
- templates/dqlite/index.html
- webapp/app.py
- Added /dqlite/index page
- Added /dqlite/docs
- Added secondary nav for dqlite bubble
- View the site in your web browser at: https://canonical-com-1616.demos.haus/dqlite
- Make sure to test on mobile, tablet and desktop screen sizes
- Verify the page design and content matches [figma](https://www.figma.com/design/zOPfX9CJTPnjrzuc4IBqGi/dqlite.io?node-id=0-1&t=3cwObGNtFBj2Vh7v-1)
- Verify all links in secondary nav are working
- Verify all links on the page are working
Fixes #[WD-18787](https://warthogs.atlassian.net/browse/WD-18787)
[WD-18787]: https://warthogs.atlassian.net/browse/WD-18787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: rebrand and migrate dqlite.io

- templates/solutions/open-source-security/cyber-resilience-act/index.html
- update `/solutions/open-source-security/cyber-resilience-act` per [copy update](https://docs.google.com/document/d/13VaiP6GGkGB4mE01bIqJ3cg8MfQXulNs9m3cmYb20HQ/edit?tab=t.0#heading=h.6d3m0dei0nxs)
- check new page matches copy doc
Fixes [WD-22005](https://warthogs.atlassian.net/issues/WD-22005)
[WD-22005]: https://warthogs.atlassian.net/browse/WD-22005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: CRA copy update

- templates/careers/company-culture/diversity.html
- Updates content based on [copydoc](https://docs.google.com/document/d/1l1UGJToc0ErHUMN9W8hELvF5sDyVRO7N0xDzncqA2SQ/edit?tab=t.0#heading=h.oies5asn2qqj)
- Updates some headings for better accessibility 
- [demo](https://canonical-com-1710.demos.haus/careers/company-culture/diversity)
Fixes https://warthogs.atlassian.net/browse/WD-22103
> Update content on /careers/company-culture/diversity

- templates/solutions/ubuntu-os/workstations.html
- Update text according to doc
- [Copy Doc](https://docs.google.com/document/d/17Tm1WIGjSieQDvvBdXShJ5AkMkXGVcNciUnDLUScq3Y/edit?tab=t.0)
- 
Fixes # [WD-22066](https://warthogs.atlassian.net/browse/WD-22066)
[WD-22066]: https://warthogs.atlassian.net/browse/WD-22066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> updating text

- templates/data/opensearch/index.html
- update opensearch page - refer to [copydoc](https://docs.google.com/document/d/1nVdoKoPrXw8lsvHEtMichlPNfxYU9Uj1zmKowcUXQ_w/edit?tab=t.0)
- go to /data/opensearch page
- [Jira ticket](https://warthogs.atlassian.net/browse/WD-22262)
> copy update: update opensearch page with copydoc

- templates/contact-us.html
- View the site locally in your web browser at: https://canonical-com-1726.demos.haus/contact-us
- Make sure the [copy doc](https://docs.google.com/document/d/1Qxvhl6_kgCDarcem1wcFPQyHk0JEFUP1zIzNsIrT3_Y/edit?tab=t.0) change is applied
Fixes WD-22430
> Update contact us

- navigation.yaml
- secondary-navigation.yaml
- static/js/tabbed-content.js
- static/sass/styles.scss
- templates/careers/hiring-process/index.html
- templates/consulting/index.html
- templates/macros/_vf_tiered-list.jinja
- templates/navigation/secondary-navigation.html
- templates/shared/_blog-card.html
- templates/solutions/financial-services/form-data.json
- templates/solutions/financial-services/index.html
- templates/solutions/index.html
- templates/solutions/telco/index.html
- webapp/navigation.py
- feat: Build /solutions/financial-services
- feat(navigation.yaml): Update telco link to point to internal url
- feat: Allow secondary navigation to not have children links
- refactor(tabbed-content.js): Use generic identifier for select element
- TEMP: Implement temp version of _vf_tiered-list.jinja
- refactor(_blog-card.html): Allow custom headings
- feat: Enforce 16:9 ratio on blog card images
- -fix: The dropdown toggle displays in the secondary nav even if it has no children
- Open [the demo](https://canonical-com-1723.demos.haus/solutions/financial-services)
- Check against:
[copydoc](https://docs.google.com/document/d/1CMEo3IsFkybk1SuKWpvZGxU6e24iNoDZkjrgloYXEkU/edit?tab=t.0) (page)
[copydoc](https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit?tab=t …
> Migrate and rebrand /solutions/financial-services

- secondary-navigation.yaml
- templates/solutions/data-and-ai/form-data.json
- templates/solutions/data-and-ai/index.html
- templates/solutions/index.html
- Created webpage solutions/data-and-ai webpage.
- Updated secondary navigation to show links to related pages.
- Updated link on solutions page to reach to new page.
- Added Contact-us form.
- [Figma](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/canonical.com-solutions?node-id=3685-7767&p=f&m=dev)
- [Demo](https://canonical-com-1738.demos.haus/solutions/data-and-ai)
- [Main copydoc](https://docs.google.com/document/d/1xvIpzJyabI9gvwf06VkxiAkNeSLj4aRReYfSDv8fu2g/edit?tab=t.0)
- [Contact form copydoc](https://docs.google.com/document/d/1YugSdT5VhEy83ARI …
> WD-22237: Created solutions/data-and-ai webpage

- templates/case-study/nova-telecommunications.html
Case study Nova Telecommunications: 
[Jira ticket](https://warthogs.atlassian.net/browse/WD-22367)
- Open the demo and navigate to `/case-study/nova-telecommunications`, or use this link immediately:
[Page demo link](https://canonical-com-1730.demos.haus/case-study/nova-telecommunications)
- Check it matches the [Figma file](https://www.figma.com/design/rEDsQqLe8SfnvoxCcXJYLr/canonical.com-case-study?node-id=966-1294&t=cG9aiEaaunM305RZ-1)
- Check it matches the [Copy doc](https://docs.google.com/document/d/1tAMjpm7fwjfkdCJ8yQE8pwMOXiaccOhORamCYu5wKqE)
> feat: case study nova telecommunications

- navigation.yaml
- secondary-navigation.yaml
- static/sass/styles.scss
- templates/solutions/automotive/form-data.json
- templates/solutions/automotive/index.html
- templates/solutions/index.html
[Demo](https://canonical-com-1724.demos.haus/solutions/automotive)
- Rebranding the Automotive solutions page
- Updated navigation
- Updated old links (pointing to ubuntu.com/automotive) to point to new one
- Check [page](https://canonical-com-1724.demos.haus/solutions/automotive) against
- Desktop
- Mobile
- Table
- Check against:
- [Figma here](https://www.figma.com/design/sjcDIPoa3oruKEbpyAR1nX/ubuntu.com-automotive?node-id=1-3547&t=GPSuXo3PD2KGE4lc-1)
- [Copydoc here](https://docs.google.com/document/d/10jSLdwz2Ks7gnEMXlKWzrpsY6TQFxISUgnQo4y3yOrA/edit?tab=t.xf0th2z9g5cm#heading=h.eto59uxtlv76)
Fixes # [WD-18545](https://warthogs.atlassian.net/browse/WD-18545)
[WD-18545]: https://warthogs.atlassian.net/browse/WD-18545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
> Automotive landing page

- navigation.yaml
- templates/projects/index.html
- Open [demo](https://canonical-com-1751.demos.haus/projects)
- (Or: `dotrun` and view the site locally in your web browser at: http://0.0.0.0:8002/projects)
- Compare against [design](https://www.figma.com/design/QCLKcRpJ6JlCQePAeQZlmD/canonical.com-projects?node-id=2-9367&m=dev) and [copy doc](https://docs.google.com/document/d/1GTnsk_Fk-ZHJQi--6X2TuaURwUCwnxZQjKdWDFBsaS0/edit?tab=t.0)
https://warthogs.atlassian.net/browse/WD-22779
> page refresh: /projects

- static/sass/_pattern_careers-progression.scss
- templates/careers/company-culture/progression.html
- templates/macros/_macro-lite-video.jinja
feat: Create macro for lite-video wrapper
feat: Refresh /careers/company-culture/progression
- Open [the demo](https://canonical-com-1752.demos.haus/careers/company-culture/progression)
- Compare against the [figma design](https://www.figma.com/design/UsovUAf4zELQgGd9bxhiVe/canonical.com-careers?node-id=2641-15957&t=B9dtTb2rTY9y1WNG-0)
- Compare against the [copydoc](https://docs.google.com/document/d/1NqSg2dt5wbmSY6IwWKo9gbxzOuyKL_gUZnFlAux1RU8/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-22704
> Refresh /careers/company-culture/progression

- templates/solutions/automotive/buyers-guide/_form.html
- templates/solutions/automotive/buyers-guide/index.html
Moved https://ubuntu.com/automotive/buyers-guide to https://canonical.com/solutions/automotive/buyers-guide
- Check that the contents of https://ubuntu.com/automotive/buyers-guide is the same as https://canonical-com-1749.demos.haus/solutions/automotive/buyers-guide
Fixes # [WD-22836](https://warthogs.atlassian.net/browse/WD-22836)
[WD-22836]: https://warthogs.atlassian.net/browse/WD-22836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Migration: Buyer's guide engage page from u.com

- templates/solutions/ubuntu-os/workstations.html
Updated workstations page per copy doc.
Compare with [copy doc](https://docs.google.com/document/d/17Tm1WIGjSieQDvvBdXShJ5AkMkXGVcNciUnDLUScq3Y/edit?tab=t.0).
https://warthogs.atlassian.net/browse/WD-23184
> Copy update: c.com/solutions/ubuntu-os/workstations

- package.json
- tests/cypress/cypress.json
- tests/cypress/integration/sample_spec.js
- tests/cypress/plugins/index.js
- tests/cypress/support/commands.js
- tests/cypress/support/index.js
- yarn.lock
Remove Cypress support and configuration files
- View the demo page and ensure the web page runs correctly
Fixes # [21704](https://warthogs.atlassian.net/browse/WD-21704)
> chore: remove Cypress and related test files from project dependencies

- templates/solutions/data-and-ai/index.html
Added instances of “Apache”, “Kubeflow”, and “®” and an additional legal disclaimer about Kyuubi at the bottom of the page.
- Check out the demo for the PR and navigate to `/solutions/data-and-ai` (shortcut: https://canonical-com-1766.demos.haus/solutions/data-and-ai)
- Check out the [task](https://warthogs.atlassian.net/browse/WD-23242) and the [copy doc](https://docs.google.com/document/d/1xvIpzJyabI9gvwf06VkxiAkNeSLj4aRReYfSDv8fu2g/edit?tab=t.0), and make sure the changes in the PR reflect the requested changes. 
- [WD-23242](https://warthogs.atlassian.net/browse/WD-23242)
[WD-23242]: https://warthogs.atlassian.net/browse/WD-23242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [copy update] WD-23242 - Update on /solutions/data-and-ai

- templates/mlops/feast/form-data.json
- templates/mlops/feast/index.html
- Created the mlops feast page in line with the [design](https://www.figma.com/design/HxgLTBbKjr8lnMjNKVueUE/canonical.com-mlops?node-id=0-1) and [doc](https://docs.google.com/document/d/1LIoohkRa1CgRf3KFazsF518Rf5A1Ym_pKUyqA1h1uRA/edit?tab=t.0).
- Created the contact form in line with the [doc](https://docs.google.com/document/d/1z-Xv7wSCDO3FMX6xQ-vF87aThNVMDlUYnczFfOEhcNg/edit?tab=t.0).
- Go to https://canonical-com-1771.demos.haus/mlops/feast
- Ensure the page is in line with the design.
- Ensure the contact form in line with the doc.
> Create a new page at /mlops/feast (WD-22833/WD-23198)

- templates/solutions/financial-services/index.html
- Copy updates for /solutions/financial-services
- Go to https://canonical-com-1789.demos.haus/solutions/financial-services
- Check it matches the [copy doc](https://docs.google.com/document/d/1CMEo3IsFkybk1SuKWpvZGxU6e24iNoDZkjrgloYXEkU/edit?tab=t.0)
Fixes [WD-23641](https://warthogs.atlassian.net/browse/WD-23641)
[WD-23641]: https://warthogs.atlassian.net/browse/WD-23641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> copy update: solutions/financial-services

- templates/solutions/financial-services/index.html
- Updates 'Perforce OpenLogic, 2025' to 'IDC' in multiple places
- Open [the demo](https://canonical-com-1797.demos.haus/solutions/financial-services)
- Check the changes match the [copydoc](https://docs.google.com/document/d/1CMEo3IsFkybk1SuKWpvZGxU6e24iNoDZkjrgloYXEkU/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-23791
> feat: Update source reference on /solutions/financial-services

- navigation.yaml
- package.json
- static/js/tabbed-content.js
- static/sass/styles.scss
- templates/careers/hiring-process/index.html
- templates/consulting/index.html
- templates/solutions/automation/form-data.json
- templates/solutions/automation/index.html
- templates/solutions/financial-services/index.html
- templates/solutions/telco/index.html
- yarn.lock
- Create solutions/automation page
- Create solutions/automation contact form
- Check out the [demo](https://canonical-com-1801.demos.haus/solutions/automation) here and compare it to the [design](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/canonical.com-solutions?node-id=3998-8602&t=Gxy2ybQeRd5DdSDf-0), and [copy doc](https://docs.google.com/document/d/12KMzjaVbi0ZWpw4BBkBTyOsaexGQdRkwsvW_t3Gw7x4/edit?tab=t.0).
- Here is the [form copy doc](https://docs.google.com/document/d/174eFlm8V6Oj_ZcSXe4Rc2ODTZMAqN_QqjYFmUolt7qQ/edit?tab=t.0).
- [WD-23241](https://warthogs.atlassian.net/browse/WD-23241)
[WD-23241]: https://warthogs.atlassian.net/browse/WD-23241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [new page] WD-23241 - feat: create solutions/automation page

- templates/anbox-cloud/form-data.json
- templates/consulting/form-data.json
- templates/data/lakehouse/form-data.json
- templates/data/mysql/form-data.json
- templates/data/postgresql/form-data.json
- templates/data/streaming/form-data.json
- templates/form-data.json
- templates/mlops/feast/form-data.json
- templates/openstack/form-data.json
- templates/partners/silicon/intel/form-data.json
- templates/shared/forms/form-fields.html
- templates/solutions/automation/form-data.json
- templates/solutions/automotive/form-data.json
- templates/solutions/cloud-native-development/form-data.json
- templates/solutions/data-and-ai/form-data.json
- templates/solutions/financial-services/form-data.json
- templates/solutions/form-data.json
- templates/solutions/industrial/form-data.json
- templates/solutions/iot-and-devices/form-data.json
- templates/solutions/open-source-security/cyber-resilience-act/form-data.json
- templates/solutions/telco/form-data.json
- Make `email`, `company`, `job title` , and `country` fields all mandatory on form generator contact fields
- Update all ` form-data.json` to remove redundant contact fields
- Go to all affected modals
- https://canonical-com-1812.demos.haus/anbox-cloud#get-in-touch
- https://canonical-com-1812.demos.haus/consulting#get-in-touch
- https://canonical-com-1812.demos.haus/data/lakehouse#get-in-touch
- https://canonical-com-1812.demos.haus/data/mysql#get-in-touch
- https://canonical-com-1812.demos.haus/data/postgresql#get-in-touch
- https://canonical-com-1812.demos.haus/data/streaming#get-in-touch
- https://canonical-com-1812.demos.haus#get-in-touch
- https://canonical-com-1812.demos.haus/mlops/feast#get-in-touch
- https://canonical-com-1812.demos.haus/openstack#get-in-touch
- …
> [WD-24062] feat: mandatory contact fields on form generator

- .github/workflows/deploy.yaml
Packed the charm from inside the charm directory. This is to fix breaking `charm pack` commands.
> feat: updated readme

- templates/contact-us.html
- Add phone number to contact-us page
- Go to [contact-us page](https://canonical-com-1817.demos.haus/contact-us)
- Scroll down to `OUR OFFICES` section and check that there is a phone number in `Canonical Group Limited`
[Copy-docs
](https://docs.google.com/document/d/1Qxvhl6_kgCDarcem1wcFPQyHk0JEFUP1zIzNsIrT3_Y/edit?tab=t.0)
> copy-update: add phone number to contact-us page

- templates/public-sector/index.html
- templates/solutions/industrial/index.html
- Refresh /public-sector
- Go to https://canonical-com-1815.demos.haus/public-sector
- Compare with [design](https://www.figma.com/design/b5QxE663Ie6ihMC83vI7nJ/canonical.com-public-sector?node-id=2-10873&m=dev) and [copy doc](https://docs.google.com/document/d/1umM1XMEzqeXklPkyCjDr98Q-RvwCcNNXgwNwfLoynTo/edit#heading=h.h8lo4gnw0yf)
Fixes [WD-23648](https://warthogs.atlassian.net/browse/WD-23648)
[WD-23648]: https://warthogs.atlassian.net/browse/WD-23648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Refresh /public-sector

- templates/careers/includes/_fast-track-jobs.html
- updated graduate job post link
- goto https://canonical-com-1830.demos.haus/careers/engineering
- click on graduate job
> Update Graduate job post link

- templates/case-study/lucid-aws-fedramp-compliance-case-study.html
- templates/case-study/ubuntu-pro-support-for-games-developer.html
- templates/consulting/index.html
- templates/data/kafka/index.html
- templates/data/valkey/what-is-valkey.html
- templates/edge-computing/index.html
- templates/openstack/index.html
- templates/solutions/data-and-ai/index.html
- templates/solutions/industrial/index.html
- templates/solutions/telco/index.html
- templates/solutions/telco/open-ran.html
Change image loading from 'auto|lazy' to 'lazy' for consistency
- Check out demo link and ensure nothing is affected and images work
Fixes # https://warthogs.atlassian.net/browse/WD-24332
> Change image loading from 'auto|lazy' to 'lazy' for consistency

- navigation.yaml
- package.json
- secondary-navigation.yaml
- templates/data/kafka/support.html
- templates/data/mongodb/support.html
- templates/data/mysql/support.html
- templates/data/opensearch/support.html
- templates/data/postgresql/support.html
- templates/data/spark/support.html
- templates/data/valkey/index.html
- templates/mlops/kubeflow/index.html
- templates/solutions/ai/big-data-ai/index.html
- templates/solutions/ai/index.html
- templates/solutions/telco/5g-edge.html
- templates/solutions/telco/open-ran.html
- yarn.lock
- Updated Meganav and secondary navigation.
- Created /mlops/kubeflow page.
- [Demo](https://canonical-com-1818.demos.haus/mlops/kubeflow)
- [Design](https://www.figma.com/design/BKzVESz3IAoj50kAaHAnH2/canonical.com-kubeflow?node-id=7-10909&m=dev)
- [Doc](https://docs.google.com/document/d/1Wvhl0yYV_w0BJsyZbQFKg_QV6RjMLbmQU3x0rsD2F4Q/edit?tab=t.0)
Fixes # [WD-19874](https://warthogs.atlassian.net/browse/WD-19874)
[WD-19874]: https://warthogs.atlassian.net/browse/WD-19874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> feat: created charmed kubeflow index page

- templates/solutions/index.html
- Copyupdate
- [Demo](https://canonical-com-1865.demos.haus/solutions)
- [Copydoc](https://docs.google.com/document/d/1vdnlbFSCidiNBXZ1zVKHWNIv1kl6C0vMmQAMYfz3yhU/edit?disco=AAABl-VKY5I)
Fixes # [WD-24630](https://warthogs.atlassian.net/browse/WD-24630)
[WD-24630]: https://warthogs.atlassian.net/browse/WD-24630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-24630: Updated link

- navigation.yaml
- secondary-navigation.yaml
- templates/data/kafka/support.html
- templates/data/mongodb/support.html
- templates/data/mysql/support.html
- templates/data/opensearch/support.html
- templates/data/postgresql/support.html
- templates/data/spark/support.html
- templates/data/valkey/index.html
- templates/mlops/feast/index.html
- templates/mlops/kubeflow/form-data.json
- templates/mlops/kubeflow/index.html
- templates/mlops/kubeflow/what-is-kubeflow.html
- templates/solutions/ai/big-data-ai/index.html
- templates/solutions/ai/index.html
- templates/solutions/telco/5g-edge.html
- templates/solutions/telco/open-ran.html
- yarn.lock
- Applied rebrand and migrated microsite to /mlops/kubeflow bubble
- View the site locally in your web browser at: https://canonical-com-1866.demos.haus/mlops/kubeflow
- Click through bubble and see that there are no errors or broken links observed 
Fixes https://warthogs.atlassian.net/browse/WD-19870
> feat: Rebrand and migrate charmed-kubeflow.io/

- templates/careers/application/faq.html
- Careers application FAQ content refresh
- Go to /careers/application/faq
- Check the content matches the content from the [copy doc](https://docs.google.com/document/d/12_O_QtPqfv9p7kaDFdiP8Xq-kY5xa1XB-C-CRbXjDew/edit?tab=t.0)
> Copy update: Careers application FAQ content refresh

- templates/careers/application/faq.html
Replace Written Interview with written assessment in the careers FAQ
- Check the copy in the code is correct
> Replace Written Interview with assessment

- templates/solutions/open-source-security/index.html
- [Open demo](https://canonical-com-1880.demos.haus/solutions/open-source-security)
- Compare with [copy doc](https://docs.google.com/document/d/1mrvhkrVjCCJE39h96CPG_b_ZHWVN0GHzZ_6TdoudeYs/edit?tab=t.0)
- Compare with [design](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/canonical.com-solutions---Sites?node-id=4595-23581&m=dev)
https://warthogs.atlassian.net/browse/WD-24640
> copy update: open source security

- webapp/app.py
- Order tags alphabetically
- Open the [demo](https://canonical-com-1892.demos.haus/case-study)
- Click the 'Select tag' dropdown and see the tags are ordered alphabetically 
Fixes https://warthogs.atlassian.net/browse/WD-25030
> feat(/case-study): Order tags alphabetically

- static/js/canonical-cla/components/ContactDetailsForm/IndividualContactForm.tsx
- static/js/canonical-cla/utils/constants.ts
- Individual CLA form: remove phone number field
Fixes [LP-2846](https://warthogs.atlassian.net/browse/LP-2846)
[LP-2846]: https://warthogs.atlassian.net/browse/LP-2846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(CLA Form): Remove phone number field from Individual form

- templates/careers/includes/_fast-track-jobs.html
- updated graduate job link
- goto https://canonical-com-1904.demos.haus/careers/engineering
- click on graduate link
> update graduate job link

- templates/solutions/automation/index.html
- Adjust the images to match this [design](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/canonical.com-solutions---Sites?node-id=3998-8602&m=dev)
- Open the [demo](https://canonical-com-1902.demos.haus/solutions/automation)
- Compare against the [design](https://www.figma.com/design/brgzRViEncgKKD4KzVnyXy/canonical.com-solutions---Sites?node-id=3998-8602&m=dev)
Fixes https://warthogs.atlassian.net/browse/WD-25048?
> fix: Adjust image sizes on /solutions/automation

- static/js/canonical-cla/components/ContactDetailsForm/OrganizationContactForm.tsx
- static/js/canonical-cla/utils/constants.ts
- Added Contact job title field
- Added a legal confirmation checkbox 
- View website at: https://canonical-com-1918.demos.haus/legal/contributors/agreement?type=organization
- Make sure the form submit is disabled when the new checkbox is unchecked
- Make sure the form submit gets enabled when all fields are filled and checkbox is enabled
Fixes [LP-2845](https://warthogs.atlassian.net/browse/LP-2845)
[LP-2845]: https://warthogs.atlassian.net/browse/LP-2845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(CLA): Add organisation form new fields

- templates/openstack/compare/index.html
- Replaced basic section's instance with divided section
- View the site  in your web browser at: https://canonical-com-1926.demos.haus/openstack/compare
- Scroll down to the section “Openstack distributions: useful resources for your project”
- Verify it matches the [figma](https://www.figma.com/design/Q8VkClYK41uoVziGIUyUqx/canonical.com-openstack---Sites?node-id=219-18809&m=dev)
Fixes #[WD-26363](https://warthogs.atlassian.net/browse/WD-26363)
[WD-26363]: https://warthogs.atlassian.net/browse/WD-26363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WD-26363] chore: use Divided section pattern

- templates/solutions/open-source-security/index.html
- Removes 'End Of Life', as per [copydoc](https://docs.google.com/document/d/1mrvhkrVjCCJE39h96CPG_b_ZHWVN0GHzZ_6TdoudeYs/edit?tab=t.0)
- Check the changes match the [copydoc](https://docs.google.com/document/d/1mrvhkrVjCCJE39h96CPG_b_ZHWVN0GHzZ_6TdoudeYs/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-26364?actionerId=557058%3Af58131cb-b67d-43c7-b30d-6b58d40bd077&sourceType=assign
> feat: Update copy on /open-source-security

- package.json
- postcss.config.js
- secondary-navigation.yaml
- templates/macros/_vf_resources.jinja
- templates/mlops/index.html
- yarn.lock
Update canonical.com/mlops page according to specs:
- [Figma](https://www.figma.com/design/HxgLTBbKjr8lnMjNKVueUE/canonical.com-mlops--Sites?node-id=68-888&p=f&t=Dk8smjYlXeEOHnZQ-0)
- [Copydoc](https://docs.google.com/document/d/1k3-ZBUmzaiel-iTvsznJfMeV8ggkzgkSzpjMJIBd0d8/edit?tab=t.0)
Locally:
- View the site locally in your web browser at: http://0.0.0.0:8002/mlops
Using Demos:
- Go to https://canonical-com-1925.demos.haus/mlops
Fixes [WD-23682](https://warthogs.atlassian.net/browse/WD-23682)
[WD-23682]: …
> WD-23682 - Refresh canonical.com/mlops

- secondary-navigation.yaml
- Update openstack secondary navigation based on the [copydoc](https://docs.google.com/document/d/1v1G2y465b_VYVUG9TIV-A_X1dU4kg5Zvrwd2latidCk/edit?tab=t.0)
- Open the [demo](https://canonical-com-1933.demos.haus/openstack)
- Check the navigation matches the navigation in the [copydoc](https://docs.google.com/document/d/1v1G2y465b_VYVUG9TIV-A_X1dU4kg5Zvrwd2latidCk/edit?tab=t.0)
*note* /features will currently 404
Fixes https://warthogs.atlassian.net/browse/WD-24830
> feat: Update openstack secondary navigation

- templates/case-study/machine-learning-for-financial-services.html
Add case study page
Check copy matches what is described on https://warthogs.atlassian.net/browse/WD-26377
Path for the case study is `/case-study/machine-learning-for-financial-services`
Fixes #WD-26377
> WD-26377: [Case Study] Machine learning for financial services

- templates/data/sitemap.xml
- templates/data/warehouse/index.html
- [Jira Ticket](https://warthogs.atlassian.net/browse/WD-26370?atlOrigin=eyJpIjoiOThlNjQ1NGZjZGVjNDZkOTgzNTg3NjZiODUxNTc5MmMiLCJwIjoiaiJ9)
- [Copydoc](https://docs.google.com/document/d/15XNmiCI8x4lom0FgMmSD5YnW7IjtKjy8vq8NZQzsB7k/edit?tab=t.0)
- [Figma design](https://figma.com/design/uJUwbUAGDog4KCMivrMpnl/canonical.com-data---Sites?node-id=3865-2434)
Note: To be merged with [this issue](https://github.com/canonical/canonical.com/pull/1936).
- Navigate to http://localhost:8002/data/warehouse and identify any inconsistencies with the Copydocs.
Fixes …
> [WD-26370] Add canonical.com/data/warehouse

- secondary-navigation.yaml
- templates/solutions/data-and-ai/index.html
Jira Ticket: https://warthogs.atlassian.net/browse/WD-26492
Copydoc: https://docs.google.com/document/d/1xvIpzJyabI9gvwf06VkxiAkNeSLj4aRReYfSDv8fu2g/edit?tab=t.0
**Note:** Not to be merged until [this issue](https://warthogs.atlassian.net/browse/WD-26370) is ready to go.
Fixes copydoc: https://docs.google.com/document/d/1xvIpzJyabI9gvwf06VkxiAkNeSLj4aRReYfSDv8fu2g/edit?tab=t.0
N/A
> [WD-26492] Update canonical.com/data-and-ai copydoc

- templates/case-study/nova-telecommunications.html
Minor copy updates per the [copy doc](https://docs.google.com/document/d/1tAMjpm7fwjfkdCJ8yQE8pwMOXiaccOhORamCYu5wKqE/edit?tab=t.0)
- View the site at: `https://canonical-com-1966.demos.haus/case-study/nova-telecommunications`
- In the [copy doc](https://docs.google.com/document/d/1tAMjpm7fwjfkdCJ8yQE8pwMOXiaccOhORamCYu5wKqE/edit?tab=t.0) check that all suggested changes were applied (you can resolve them as well if you want, or I can do it later)
> WD-27219 Update Nova case study

- templates/partial/_footer.html
Fix footer typo
Fixes https://warthogs.atlassian.net/browse/WD-27259
> Fix typo in footer HTML

- templates/data/kafka/index.html
Copy update: update product name from Canonical's Kafka to Charmed Apache Kafka
- Check out the [demo link](https://canonical-com-1976.demos.haus/data/kafka)
- Compare with [Copy docs](https://docs.google.com/document/d/1bfo97XdFdKlzrMcMoRxiTdzt_bPVndx6j55IPsapuAE/edit?usp=sharing) changes
Fixes # [27614](https://warthogs.atlassian.net/browse/WD-27614?atlOrigin=eyJpIjoiZmFhYWI1OWJhYWRmNDAzZjk1MmI3YWU4ZmY1N2EzYjQiLCJwIjoiaiJ9)
> copy update: /data/kafka

- templates/solutions/industrial/index.html
See copy doc: https://docs.google.com/document/d/1QiU75g49lRKebt82oyLSxR3-PU96Sk87nqauAZ4vvIY/edit
- Add link to IEC 62443-4-1 press release
- Add customer testimonial
- Add missing sub-heading in 'Industrial micro clouds'
- See live demo: https://canonical-com-1972.demos.haus/solutions/industrial
Fixes WD-27346
> WD-27346: `/solutions/industrial` copy updates

- README.md
- requirements.txt
- webapp/app.py
- Add `/juju/latest.json` endpoint
- Brought over from https://github.com/canonical/juju.is/blob/7f820e2dc971250674228fbc8a0590957580d013/webapp/app.py#L86
- Go to https://canonical-com-1982.demos.haus/juju/latest.json
- Check that a valid JSON response is returned
Fixes [WD-28112](https://warthogs.atlassian.net/browse/WD-28112)
[WD-28112]: https://warthogs.atlassian.net/browse/WD-28112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add /juju/latest.json endpoint

- templates/data/kafka/index.html
Refactored to use vanilla patterns and a new grid system.
This was supposed to be part of a copy update #1976 , but due to the deadline approaching, it could not go along with it.
- Check out the demo [link](https://canonical-com-1981.demos.haus/data/kafka)
- Check that if appears correctly on 
- mobile
- desktop
- tablet
Fixes # [27614](https://warthogs.atlassian.net/browse/WD-27614)
> refactor: /data/kafka page to use vanilla patterns
